lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertType.cpp
This PR covers the first item in https://github.com/NVIDIA/cuda-quantum/issues/57.
The changes here will be validated by updating the CI pipelines as captured by subsequent items in that issue.
=> Temporary fix for AST visitor reentrancy bugs.

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/qpe.cpp
The bridge currently only makes use of the floating point powf operation, but we can use the others as well and get rid of some casts, etc.
=> Make use of the various math dialect power operations.

docs/sphinx/api/languages/python_api.rst, python/CMakeLists.txt, python/_cudaq.cpp, python/runtime/cudaq/builder/py_QuakeValue.cpp, python/runtime/cudaq/spin/py_matrix.cpp, python/runtime/cudaq/spin/py_matrix.h, python/runtime/cudaq/spin/py_spin_op.cpp, python/tests/unittests/test_SpinOperator.py, python/tests/unittests/test_observe.py, python/tests/unittests/test_sample.py, runtime/cudaq/matrix.h, runtime/cudaq/spin/CMakeLists.txt, runtime/cudaq/spin/matrix.cpp, runtime/cudaq/spin/spin_op.cpp, runtime/cudaq/spin_op.h, unittests/spin_op/SpinOpTester.cpp
Implement to_matrix on spin_op. The return type is a complex_matrix.
#50
=> Implement spin_op::to_matrix()

python/cudaq.py
[Issue 104 ](https://github.com/NVIDIA/cuda-quantum/issues/104): Removes unused functions and imports from the cudaq python module.
=> Remove outdated functions from cudaq.py

runtime/cudaq/platform/default/DefaultQuantumPlatform.cpp, runtime/cudaq/platform/mqpu/MultiQPUPlatform.cpp, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/managers/qir/QIRForwards.h, runtime/cudaq/qis/managers/qir/QubitQIRExecutionManager.cpp, runtime/cudaq/qis/qubit_qis.h, runtime/cudaq/qis/qudit.h, unittests/CMakeLists.txt, unittests/qudit/CMakeLists.txt, unittests/qudit/SimpleQuditTester.cpp, unittests/qudit/simple_qudit/CMakeLists.txt, unittests/qudit/simple_qudit/SimpleQuditExecutionManager.cpp
Refactor on the `cudaq::ExecutionManager` to better support qudit programming and simulation, apart from MLIR compilation. 
Extract commonalities between ExecutionManager subtypes into new `BasicExecutionManager`. 
#49
=> Improve the ExecutionManager Extension Point

test/QTX/Transforms/op_decomposition.mlir, test/QTX/Transforms/split_arrays.mlir, utils/CircuitCheck/CMakeLists.txt, utils/CircuitCheck/CircuitCheck.cpp, utils/CircuitCheck/UnitaryBuilder.cpp, utils/CircuitCheck/UnitaryBuilder.h
Some improvements to the CircuitCheck tool are necessary as part of refactoring/improving the operations decomposition pass. This PR is a first step that simplifies the implementation by removing support for QTX---which will disappear with the future dialects unification.
=> [CircuitCheck] Remove QTX support

.github/workflows/test_in_devenv.yml, unittests/integration/ghz_nisq_tester.cpp
Changes
* Throws a failure in the github CI if ctest or llvm-lit fails
=> Fix ctest command in CI

include/cudaq/Optimizer/Dialect/Common/Ops.td
This PR fixes some matrices (row-major vs col-major) issues, improves the docs and remove the use of `llvm::Optional` (which was already deprecated some time ago)
=> [common-ops] Improve docs and fix matrices

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/using/advanced/cudaq_ir.rst, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, lib/Optimizer/Transforms/QTXToQuake.cpp, lib/Optimizer/Transforms/QuakeObserveAnsatz.cpp, lib/Optimizer/Transforms/QuakeToQTX.cpp, lib/Optimizer/Transforms/QuakeToQTXConverter.cpp, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/kernel_builder.cpp, utils/CircuitCheck/UnitaryBuilder.cpp, utils/CircuitCheck/UnitaryBuilder.h
Remove the redundant `q` prefix and add `ref` for clarity.
=> Change qextract to extract_ref everywhere.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, test/Quake/quake-ops.qke, test/Quake/to_cfg.qke
Improve the documentation of these ops. Make the documentation more unifrom, add examples, add longer descriptions.
Add a load and store operation to the dialect.
=> Make the CC ops more uniform.

docs/sphinx/specification/quake-dialect.md
Small fixes to the quake dialect documentation.
=> [docs] Small fixes to quake dialect example

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/Decomposition.cpp, lib/Optimizer/Transforms/DecompositionPatterns.cpp, lib/Optimizer/Transforms/DecompositionPatterns.h, test/Transforms/DecompositionPatterns/CCXToCCZ.qke, test/Transforms/DecompositionPatterns/CCZToCX.qke, test/Transforms/DecompositionPatterns/CR1ToCX.qke, test/Transforms/DecompositionPatterns/CRxToCX.qke, test/Transforms/DecompositionPatterns/CRyToCX.qke, test/Transforms/DecompositionPatterns/CRzToCX.qke, test/Transforms/DecompositionPatterns/CXToCZ.qke, test/Transforms/DecompositionPatterns/CZToCX.qke, test/Transforms/DecompositionPatterns/HToPhasedRx.qke, test/Transforms/DecompositionPatterns/R1ToPhasedRx.qke, test/Transforms/DecompositionPatterns/RxToPhasedRx.qke, test/Transforms/DecompositionPatterns/RyToPhasedRx.qke, test/Transforms/DecompositionPatterns/RzToPhasedRx.qke, test/Transforms/DecompositionPatterns/SToPhasedRx.qke, test/Transforms/DecompositionPatterns/TToPhasedRx.qke, test/Transforms/DecompositionPatterns/XToPhasedRx.qke, test/Transforms/DecompositionPatterns/YToPhasedRx.qke, test/Transforms/DecompositionPatterns/ZToPhasedRx.qke
This PR adds a decomposition pass together is a database of decomposition patterns written in native code.
Still todo:
=> [optimizer] Decomposition pass

python/cudaq.py, runtime/cudaq/domains/chemistry/uccsd.h, unittests/mqpu/mqpu_tester.cpp
Also, fix MQPUTester clang compile error
=> Update python command line flags (forgotten). 

python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/compiler/one_qubit.py
=> Bind r1 gate to python

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/MultiControlDecomposition.cpp, test/Transforms/multicontrol_decomposition.qke
A pass to decompose multi controlled operations.
=> [optimizer] Multicontrol decomposition

runtime/cudaq/algorithms/optimizers/ensmallen/CMakeLists.txt, tools/nvqpp/nvq++.in
Couple fixes to build and use CUDA Quantum in macOS
=> Fixes for macOS

.github/workflows/cla_assistant.yml, .github/workflows/clean_caches.yml, .github/workflows/publish_docs.yml
Mostly some ergonomic improvements after configuring the docs.
I also created a separate account with which access tokens used by bots are associated. I believe that should work as configured, but I'll need to confirm the next time someone needs to sign the CLA.
=> Workflow improvements

docs/sphinx/api/languages/cpp_api.rst, docs/sphinx/examples/python/advanced_vqe.py, python/runtime/cudaq/algorithms/py_optimizer.cpp, python/runtime/cudaq/algorithms/py_vqe.cpp, python/tests/unittests/test_optimizer.py, python/tests/unittests/test_vqe.py, runtime/cudaq/algorithms/gradient.h, runtime/cudaq/algorithms/gradients/CMakeLists.txt, runtime/cudaq/algorithms/gradients/central_difference.h, runtime/cudaq/algorithms/gradients/forward_difference.h, runtime/cudaq/algorithms/gradients/parameter_shift.h, runtime/cudaq/gradients.h
Checklist:
- [X ] I have added tests to cover my changes.
- [X ] I have read the CONTRIBUTING document.
Added forward difference gradient evaluation.
=> Added forward difference gradient evaluation.

tools/nvqpp/fixup-linkage.pl, unittests/integration/noise_tester.cpp
Needed a little persuasion.
#250
=> Fix #250: linkage of top-level (global) function.

python/CMakeLists.txt, python/_cudaq.cpp, python/tests/backends/test_Quantinuum.py, python/utils/LinkedLibraryHolder.h, python/utils/TestingUtils.cpp, python/utils/TestingUtils.h, runtime/common/Logger.h, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, runtime/cudaq/simulators.h, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, tools/nvqpp/nvq++.in, unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in, unittests/backends/quantinuum/QuantinuumTester.cpp, utils/mock_qpu/quantinuum/mock_quantinuum.py
Update the mock Quantinuum server to actually simulate the submitted QIR Base Profile code. Other mock QPU servers that we create or pull-in should follow this pattern. 
#253
=> Base profile Simulation with the Mock QPUs

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/FactorQuantumAlloc.cpp, test/Quake/combine.qke
This pass addresses #275. Allocations of vectors of quantum references are factored into a series of individual reference allocations.
Add dealloc to test.
=> [pass] Factor quantum allocations.

lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/MemToReg.cpp, test/AST-Quake/loop_unroll-2.cpp, test/Quake/loop.qke
Fix roundtrip bug with cc.loop.
=> Add more cases to loop unrolling tests.

lib/Optimizer/Transforms/DecompositionPatterns.cpp, test/Transforms/DecompositionPatterns/CHToCX.qke
Closes #293 
This PR adds the ability to decompose single control Hadamard operations.
=> [opt] Add ch decomposition

tools/nvqpp/nvq++.in
Fix the style of the file while I'm here.
=> [bug] Fix a bunch of bugs in the nvq++ driver.

lib/Optimizer/Transforms/MultiControlDecomposition.cpp, test/Transforms/multicontrol_decomposition.qke
Fix errors regarding negated controls and `XOp` and `ZOp` specialization in the multi control decomposition pass.
=> [bug] Fix multicontrol decomposition

runtime/cudaq/builder/kernel_builder.cpp, tools/cudaq-translate/cudaq-translate.cpp, tools/nvqpp/nvq++.in
=> Add unwind lowering pass to the default pipeline

utils/CircuitCheck/CircuitCheck.cpp, utils/CircuitCheck/UnitaryBuilder.cpp
This PR fix the checking of ancilla clean up in the CircuitCheck, and improve diagnostics of when checks fails.
=> [CircuitCheck] Fix cleanup check, improve diagnostic

runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config
Adds the multi control decomposition pass to the quantinuum target pipeline (JIT)
=> [target] Add multi-control decomposition to pipeline

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ASTBridge.cpp, test/AST-Quake/nested_scope.cpp
=> Issue #341: make sure the proper symbol is generated if extern "C"

lib/Optimizer/Transforms/LoopAnalysis.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config
This fixes a couple of bugs from internal item 1.
=> Updates for release.

lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/LoopNormalize.cpp
Make loop normalization greedy so it looks like loop unrolling.
=> Open up loop analysis to allow multiple inductions in the loop.

include/cudaq/Optimizer/CodeGen/Passes.h, lib/Optimizer/CodeGen/LowerToBaseProfileQIR.cpp, lib/Optimizer/Transforms/BasisConversion.cpp, runtime/common/RuntimeMLIR.cpp, test/AST-Quake/base_profile.cpp, test/AST-Quake/to_qir.cpp, tools/cudaq-opt/cudaq-opt.cpp
For the release. ~Includes both #405 and #406.~
=> Improve the error messages concerning QIR base profile compliance.

python/tests/backends/test_IonQ.py, python/tests/backends/test_Quantinuum.py, python/tests/backends/test_Quantinuum_LocalEmulation.py, python/utils/LinkedLibraryHolder.cpp, runtime/common/RuntimeMLIR.cpp, runtime/common/RuntimeMLIR.h, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, tools/nvqpp/nvq++.in
Much needed - help everyone see the base profile code when errors occur in submission.
=> Add environment variable allowing one to print the IR before remote submission

lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/LoopAnalysis.h, lib/Optimizer/Transforms/LoopNormalize.cpp, test/AST-Quake/loop_normal.cpp
Fix misc. bugs to normalize more loops. Add tests.
=> Extend loop normalization to linear expressions on induction variable.

lib/Optimizer/Transforms/LowerToCFG.cpp
=> Fix assertion error when lowering cc::if.

runtime/cudaq/builder/QuakeValue.cpp
This updates the computation of the offsets in a memory sequence, such as a std::vector's data, to the new CC dialect semantics. This replaces the code that generated raw byte-wise arithmetic.
=> [kernel builder] Fix slice computation.

runtime/cudaq/platform/default/rest/helpers/quantinuum/QuantinuumServerHelper.cpp
=> [rt] Change quantinuum's result processing

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Transforms/QuakeObserveAnsatz.cpp
=> Minor changes. Formatting and using an updated null-like type.

lib/Optimizer/Transforms/QuakeObserveAnsatz.cpp
=> Fix #303 - release build segfault

include/cudaq/Optimizer/Dialect/Quake/Canonical.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, runtime/cudaq/builder/QuakeValue.cpp, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/slice.cpp, test/Quake/canonical-1.qke, test/Quake/canonical-2.qke, test/Quake/combine.qke, test/Quake/roundtrip-ops.qke
Initial PR for #472. A follow-up PR will implement constant folding.
=> Rename subvec to subveq

python/tests/unittests/test_NoiseModel.py, unittests/integration/noise_tester.cpp
Fixes the random seed in some of our noise model tests to minimize range of results.
=> Set random seed for depolarization tests

lib/Optimizer/Dialect/CC/CCOps.cpp, test/AST-Quake/base_profile.cpp
=> Fix compiler crash when processing empty region

.github/workflows/config/spelling_allowlist.txt, .github/workflows/test_in_devenv.yml, docker/build/devdeps.Dockerfile, include/cudaq/Target/Emitter.h, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Target/IQM/TranslateToIQMJson.cpp, python/tests/CMakeLists.txt, python/tests/backends/test_IQM.py, runtime/common/RestClient.cpp, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, runtime/cudaq/platform/default/rest/helpers/CMakeLists.txt, runtime/cudaq/platform/default/rest/helpers/iqm/CMakeLists.txt, runtime/cudaq/platform/default/rest/helpers/iqm/IQMServerHelper.cpp, runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config, runtime/nvqir/NVQIR.cpp, test/Target/IQM/basic.qke, test/Target/IQM/extractOnConstant.qke, test/Target/IQM/for_loop.cpp, test/Target/IQM/z_gate.cpp, unittests/backends/iqm/CMakeLists.txt, unittests/backends/iqm/IQMStartServerAndTest.sh.in, unittests/backends/iqm/IQMTester.cpp, utils/mock_qpu/__init__.py, utils/mock_qpu/iqm/mock_iqm_cortex_cli.py, utils/mock_qpu/iqm/mock_iqm_server.py
IQM Server Helper implementation.
=> IQM Server Helper

runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config
The compilation error on nightly tests are because IONQ's pipeline was not doing multi-control decomposition.
=> Add multi-control decomposition to IONQ pipeline

lib/Target/OpenQASM/TranslateToOpenQASM.cpp, test/Target/OpenQASM/callOp_380.qke
=> Enable translation of func::CallOp for OpenQASM Target.

include/cudaq/Optimizer/Dialect/Quake/QuakeInterfaces.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td
This will make it a bit simpler to deal with mx, my, and mz in a uniform way in the code.
=> Add MeasurementInterface.

.github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/publishing.yml
Deploying to "nightly" on NGC to make the images publicly available.
=> Update NGC deployment

include/cudaq/Frontend/nvqpp/ASTBridge.h, test/AST-Quake/qpe.cpp
Fix comments in test and run them through clang-format.
=> Fix bug when using gcc-11 header files.

runtime/common/RuntimeMLIR.cpp
The LLVM IR optimization in `cudaq::optimizeLLVM()` is incompatible with IonQ's backend when dealing with trivial, empty programs. This removes that optimization for those trivial, empty programs. It leaves the optimization untouched for all other programs.
Closes #637
=> Only enable optimization in non-empty kernels

cmake/Modules/CUDAQConfig.cmake, cmake/Modules/CUDAQEmDefaultConfig.cmake, cmake/Modules/CUDAQPlatformDefaultConfig.cmake, docs/sphinx/using/advanced/cudaq_ir.rst
=> Follow-up to #658 - rename cudaq-em-qir to cudaq-em-default

lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp, test/AST-Quake/ranged_for.cpp, test/AST-error/statements.cpp
See #646. This implements the ranged for statement listed in that issue for std::vector<T> collections. Add a new test.
Make the operator kind test a fully parametric template function.
=> Implement ranged for loops over std::vector<T> collections.

docs/sphinx/install.rst
=> Fix docs formatting

include/cudaq/Optimizer/Builder/Intrinsics.h, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/Builder/CMakeLists.txt, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/CodeGen/LowerToQIRProfile.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/AST-Quake/ranged_for.cpp
While this adds general support for CUDA Quantum's range() function, it also provides an optimized lowering when range() is used in a C++ ranged for statement.
Add a regression test for nested ranged for statements.
=> Add support for cudaq::range(N).

.github/workflows/publishing.yml, docker/build/devdeps.ext.Dockerfile, docker/release/cudaq.Dockerfile, docker/release/cudaq.ext.Dockerfile, docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp
Deployment: https://github.com/NVIDIA/cuda-quantum/actions/runs/6417670686
=> Upgrade some packages with vulnerabilities

include/cudaq/Optimizer/Transforms/Passes.td, test/Quake/observeAnsatz.qke
Remove quake from quake-observe-ansatz. See #771.
=> Remove dialect name from pass option name (part 2)

include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/Transforms/Passes.td, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config, runtime/cudaq/platform/default/rest/helpers/iqm/iqm.config, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.config, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config, test/Transforms/BasisConversion/h-t-cz.qke, test/Transforms/BasisConversion/phased_rx-cz.qke, test/Transforms/DecompositionPatterns/CCXToCCZ.qke, test/Transforms/DecompositionPatterns/CCZToCX.qke, test/Transforms/DecompositionPatterns/CHToCX.qke, test/Transforms/DecompositionPatterns/CR1ToCX.qke, test/Transforms/DecompositionPatterns/CRxToCX.qke, test/Transforms/DecompositionPatterns/CRyToCX.qke, test/Transforms/DecompositionPatterns/CRzToCX.qke, test/Transforms/DecompositionPatterns/CXToCZ.qke, test/Transforms/DecompositionPatterns/CZToCX.qke, test/Transforms/DecompositionPatterns/ExpPauliToHRyRzCX.qke, test/Transforms/DecompositionPatterns/HToPhasedRx.qke, test/Transforms/DecompositionPatterns/R1ToPhasedRx.qke, test/Transforms/DecompositionPatterns/RxToPhasedRx.qke, test/Transforms/DecompositionPatterns/RyToPhasedRx.qke, test/Transforms/DecompositionPatterns/RzToPhasedRx.qke, test/Transforms/DecompositionPatterns/SToPhasedRx.qke, test/Transforms/DecompositionPatterns/TToPhasedRx.qke, test/Transforms/DecompositionPatterns/XToPhasedRx.qke, test/Transforms/DecompositionPatterns/YToPhasedRx.qke, test/Transforms/DecompositionPatterns/ZToPhasedRx.qke, test/Transforms/multicontrol_decomposition.qke
This PR fixes the 3 decomposition like passes.
=> Remove dialect name from pass option name (part 3)

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, test/Quake/merge_rotation.qke
Fix the test.
Depends on #769. Relates to #770.
=> Implement the combine rotation peephole optimization.

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/if.cpp
=> Fix logical `&&` operator in `__qpu__` kernels

lib/Optimizer/Transforms/LoopNormalize.cpp, test/AST-Quake/loop_normal.cpp
Loop normalization was mistakenly adding back the linear expression from the condition expression to compute the current value of the induction in the body. Remove that code and add a regression test.
=> Fix bug in loop normalization.

docs/sphinx/examples/cpp/basics/noise_amplitude_damping.cpp, docs/sphinx/examples/cpp/basics/noise_bit_flip.cpp, docs/sphinx/examples/cpp/basics/noise_depolarization.cpp, docs/sphinx/examples/cpp/basics/noise_modeling.cpp, docs/sphinx/examples/cpp/basics/noise_phase_flip.cpp, docs/sphinx/using/cpp.rst
- Hook C++ examples to the docs rst.
- Remove duplicate `--target` in the example instructions.
=> Add C++ noise modeling examples to our docs

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/if.cpp
=> Fix ternary operator in `__qpu__` kernels

python/tests/backends/test_oqc.py, runtime/cudaq/platform/default/rest/helpers/oqc/OQCServerHelp.cpp, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.config, unittests/backends/oqc/OQCTester.cpp, utils/mock_qpu/oqc/__init__.py
* Use single all_info endpoint rather than separate result and error endpoints
* Remove private helper functions
* fix stop condition, by checking for either errors or results
* Add env variable and extra command line processing capabilities to the target
=> Various improvements and fixes for the OQC rest integration

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, test/AST-Quake/reverse.cpp, test/AST-Quake/vector_front_back.cpp
This is a preliminary implementation. It will need more work in order to enable loop normalization and loop unrolling.
See #646
=> Implement std::reverse on std::vector

lib/Frontend/nvqpp/ConvertDecl.cpp
=> Add a catch-all clause for any std container types used in kernel

scripts/run_clang_format.sh
=> Fix clang-format script to exclude targettests.

docs/sphinx/using/hardware.rst, docs/sphinx/using/python.rst
Closes #868 
* Fixes small backend typo in hardware docs
* Hooks up IQM example to python hardware examples
=> Clean up hardware documentation

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/using/hardware.rst
OQC target general use documentation
=> Initial hardware documentation for OQC

docker/build/devdeps.Dockerfile
=> Add pyspelling to devdeps image

.gitlab/workflows.yml
- Remove tensornet from downstream (GitLab) pipeline.
- Prerequisite for https://github.com/NVIDIA/cuda-quantum/pull/863
=> Remove tensornet from downstream pipeline

.github/workflows/publishing.yml, runtime/nvqir/cutensornet/CMakeLists.txt
There is a bug `tensornet` backend config file, not reporting `GPU_REQUIREMENTS` field expected by our CI validation.
Checking the CI scripts, this field will affect the validation during deployment and publishing.
Also, update GPU backend validation to skip some tests for MPS.
N.B.: due to the additional tests, the validation CI runtime will increase.
=> Fixing CI issues in deployment/publishing validation for tensornet backends

docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp, docs/sphinx/install.rst, docs/sphinx/using/cpp.rst, docs/sphinx/using/simulators.rst
Docs update - Addresses https://github.com/NVIDIA/cuda-quantum/issues/886
=> Adding documentation about default target and the environment variable to override it

targettests/oqc/cudaq_observe.cpp, targettests/oqc/readme.txt
=> Add cudaq_observe.cpp to nightly OQC tests

include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/Builder/Intrinsics.h, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/DecompositionPatterns.cpp
Minor code maintenance to update factory functions and uses of same. These changes do not change behavior, but make uses more uniform.
=> [NFC] Code maintenance.

docs/sphinx/api/languages/python_api.rst, docs/sphinx/using/cudaq/generic_functions.rst, docs/sphinx/using/cudaq/kernel.rst, docs/sphinx/using/cudaq/platform.rst, docs/sphinx/using/cudaq/verbose_out.rst
Closes #845
Partially addresses #704 (does not add chemistry/hardware efficient ansatz docs)
=> Documentation updates for 0.5 release

python/README.md
* Fixing links to contribution readme and license file in Python documentation.
* Removed old full form of LLVM.
=> [Docs] Python documentation update

runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, unittests/qir/NVQIRTester.cpp
=> Reduce GPU memory usage when using reset(q) in user programs

docs/sphinx/examples/python/bernstein_vazirani.py, docs/sphinx/using/simulators.rst, python/README.md
(1) Update Python readme to reflect the new requirement of having a CUDA-aware installation of MPI 
(2) Update the bv example to set the seed (to support launching with MPI)
=> Update Python README to cover CUDA-aware MPI

test/CMakeLists.txt, tools/nvqpp/nvq++.in
- also include some changes to help with MacOS building
- eliminate trailing whitespace in nvq++.in
=> Fix library build dependence issues with tests.

.github/workflows/delete_tags.yml, .github/workflows/dev_environment.yml
We have accumulated quite a bit of tags. We don't/shouldn't delete tags automatically, and due to permission issues, it is not possible to delete them outside a GitHub workflow. Hence, I added a workflow to delete tags...
Tried it out here: https://github.com/NVIDIA/cuda-quantum/actions/runs/7053634885
=> Workflow to delete tags from GHCR

test/Quake/cse.qke
Adds tests for the canonicalization of quake.concat.
=> Closes #573: add tests for quake.concat.

test/AST-Quake/type_alias.cpp
=> Add regression test for typedef handling.

docker/build/devdeps.Dockerfile, test/NVQPP/shared_obj.cpp, tools/nvqpp/nvq++.in
Closes #314.
Adds PIC code flag to the required spots and allows `-static` and `-shared` flags to be passed to the linker.
=> Add ability to create shared library to the driver.

include/cudaq/Optimizer/Builder/Factory.h, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake/return_vector.qke
=> Support for return vectors of type std::vector<NT> where NT is a

runtime/cudaq/builder/kernel_builder.h
Reverting since some of the checks for this PR should have failed and didn't properly due to the issue fixed here: https://github.com/NVIDIA/cuda-quantum/pull/1019
=> Revert "[NFC] Disable warnings from the kernel_builder."

runtime/cudaq/builder/kernel_builder.h, test/AST-error/bad_sample_signature.cpp, test/AST-error/capture_list.cpp, test/AST-error/inaccessible_variable.cpp, test/AST-error/invalid_kernel.cpp, test/AST-error/kernel_data_members.cpp, test/AST-error/kernel_invalid_argument-1.cpp, test/AST-error/kernel_invalid_argument-2.cpp, test/AST-error/kernel_invalid_argument-3.cpp, test/AST-error/kernel_invalid_argument-4.cpp, test/AST-error/multiple_methods.cpp, test/AST-error/negation_error.cpp, test/AST-error/quantum_types.cpp, test/AST-error/statements.cpp, test/AST-error/wall.cpp
Fixes the tests that were not being run.
=> [NFC] Merge back in #1016

lib/Optimizer/CodeGen/LowerToQIRProfile.cpp
The Base Profile requires output recording calls to come at the end of the program, but the Adaptive Profile does not require that, and depending on the program, it may be logically inconsistent to do so. This changes the `LowertoQIRProfile.cpp` code to make output recording calls come right after the corresponding measurements for Adaptive Profile programs.
Note that this fixes the QIR generation issue in #1030, but the Quantinuum backend still generates results for measurements that should not have occurred.
Note: I have also tested these changes by submitting all of our integration tests to Quantinuum's `H1-1SC` and a few select tests to `H1-1E`. They all still pass.
=> Move QIR result recording calls right after measurement for Adaptive Profile

lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, test/AST-Quake/vector_vector.cpp, test/AST-error/vector.cpp
Adds a regression test for supported cases. Adds a negative test for cases that are not yet supported.
=> Add support for vectors of vectors to the bridge.

runtime/nvqir/CircuitSimulator.h, unittests/integration/measure_reset_tester.cpp
Fix library mode bit ordering issue discussed in #978
=> Fix library mode qubit ordering bug.

test/NVQPP/struct_arg.cpp, tools/nvqpp/nvq++.in
- remove the redundant 'file' arg
- automatically enable MLIR mode
=> [nvq++] Fixes to the 'emit-qir' command line argument

unittests/CMakeLists.txt, unittests/backends/QPPDMTester.cpp
* Fixes a bug occurring during release builds on the QPPDMTester
* Removes unneeded includes from dm tester
=> Patch density matrix bug in release mode

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/api/languages/cpp_api.rst, runtime/common/MeasureCounts.cpp, runtime/common/MeasureCounts.h, runtime/cudaq.h, runtime/cudaq/cudaq.cpp, runtime/cudaq/distributed/mpi_plugin.cpp, runtime/cudaq/distributed/mpi_plugin.h, runtime/cudaq/platform/QuantumExecutionQueue.h, runtime/cudaq/platform/common/QuantumExecutionQueue.cpp, runtime/cudaq/platform/quantum_platform.h, runtime/cudaq/utils/registry.h, tools/nvqpp/nvq++.in
- Const-correctness in MeasureCounts: in case we need to pass a `const MeasureCounts&` (e.g., Json conversion)
- Add string broadcast to MPI interface.
- Minor tidy up some somments/include.
- nvq++ in library mode should also include `OBJS_TO_MERGE` when doing the linking (compiled `backendConfig.cpp`)
=> Supporting changes for PR#1012

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/ctor-2.cpp, test/AST-Quake/cudaq_types.cpp, test/AST-Quake/qbit_arg.cpp, test/AST-Quake/struct.cpp, test/AST-error/vector.cpp
These changes allow the remaining tests to be activated.
Fix Werror issue. Fix LLVM codegen issue.
=> Process initializer lists for struct types in the bridge.

.github/workflows/test_in_devenv.yml
This reverts commit f6f06cd7624fc2adab85cf394ca6408a2c1e2f1f.
=> Revert "Update CI to use iqm-client v15.0 (not v15.1) (#1048)"

runtime/common/ServerHelper.h
=> [rt] Fix missing header

runtime/cudaq/platform/mqpu/MultiQPUPlatform.cpp
It was an oversight not setting the QPU Id there. `setId` was added to the base class to facilitate that.
Thanks @amccaskey for catching this.
=> Fix an oversight in MultiGPU code refactor

python/tests/compiler/fix_1130_bug_bad_arg_checking.py, runtime/cudaq/builder/kernel_builder.cpp
=> Fix issue with argument checking on kernel_builder apply_call

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, test/AST-Quake/qalloc_initialization.cpp, test/Transforms/mapping_non_unitaries.qke
=> Add support for the new qvector constructor with an initialization list

python/README.md
This is a docs-only workaround for #1144.
=> Update Python/README.md to better comprehend MPI plugin

docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp, docs/sphinx/examples/cpp/basics/noise_amplitude_damping.cpp, docs/sphinx/examples/cpp/basics/noise_bit_flip.cpp, docs/sphinx/examples/cpp/basics/noise_depolarization.cpp, docs/sphinx/examples/cpp/basics/noise_modeling.cpp, docs/sphinx/examples/cpp/basics/noise_phase_flip.cpp, docs/sphinx/examples/cpp/providers/ionq.cpp, docs/sphinx/examples/cpp/providers/quantinuum.cpp, docs/sphinx/using/cpp.rst
=> copy edits to the C++ examples on the website

runtime/common/RemoteKernelExecutor.h, runtime/cudaq/spin/matrix.cpp, runtime/cudaq/spin_op.h
=> Add missing includes.

runtime/cudaq/platform/default/rest_server/helpers/llvm_jit/JIT.h
=> Add missing header.

.github/workflows/config/gitlab_commits.txt, docs/sphinx/install.rst
The commit update should fix the current publishing issue.
=> MPI related docs and commit update

runtime/nvqir/cutensornet/simulator_mps_register.cpp, runtime/nvqir/cutensornet/simulator_tensornet_register.cpp
=> Fix tensornet bug with async python functions

docs/sphinx/api/languages/python_api.rst, python/cudaq/__init__.py, python/tests/parallel/test_mpi_api.py
* Expose 'OptimizationResult' in Python API
* Re-enable 'testMPI()'
Issue https://github.com/NVIDIA/cuda-quantum/issues/1157
=> [experimental/python] Minor fixes - addressing gaps

.github/workflows/ci.yml, .github/workflows/clean_up.yml, .github/workflows/create_cache_command.yml, .github/workflows/deployments.yml, .github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml
Following up to #1156 to update more GitHub actions.
=> More GitHub actions updates to get rid of warnings

runtime/cudaq/qis/managers/BasicExecutionManager.h, unittests/integration/adjoint_tester.cpp
=> [rt] Fix issue with handling nested `cudaq::adjoint`

python/cudaq/__init__.py, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/utils.py, python/cudaq/kernels/uccsd.py, python/tests/builder/test_NoiseModel.py, python/tests/builder/test_kernel_builder.py, python/tests/kernel/test_ir_operations.py, python/tests/kernel/test_kernel_features.py, python/tests/kernel/test_library_kernels.py, python/tests/kernel/test_observe_kernel.py, python/tests/kernel/test_sample_kernel.py, python/tests/kernel/test_state_kernel.py, python/tests/kernel/test_vqe_kernel.py, python/tests/mlir/ast_veq_tuple_target.py, python/tests/mlir/lit.cfg.py, python/tests/mlir/target/conditional_sample.py, python/tests/mlir/target/graph_coloring.py, python/tests/mlir/target/qspan_slices.py, python/tests/parallel/test_mqpu.py, python/tests/remote/test_remote_platform.py
* Drop `qlist`
* Re-enable working test(s)
* Applied code formatting
https://github.com/NVIDIA/cuda-quantum/issues/1157
=> [experimental/python] Clean-up

CMakeLists.txt, test/Remote-Sim/args_parsing.cpp, test/Remote-Sim/free_func.cpp, test/Remote-Sim/get_state.cpp, test/Remote-Sim/kernel_builder.cpp, test/Remote-Sim/observe.cpp, test/Remote-Sim/observe_async.cpp, test/Remote-Sim/sample.cpp, test/Remote-Sim/sample_async.cpp, test/Remote-Sim/unsupport_args.cpp, test/lit.site.cfg.py.in, tools/CMakeLists.txt
have the resources to perform such tests.
=> Add the ability to disable remote-sim tests, since not all build/host machines

.github/workflows/ci.yml, .github/workflows/python_wheels.yml, pyproject.toml, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/utils.py, python/cudaq/kernels/uccsd.py, python/cudaq/runtime/utils.py, python/tests/builder/test_kernel_builder.py, python/tests/kernel/test_ir_operations.py, python/tests/kernel/test_kernel_features.py, python/tests/kernel/test_state_kernel.py, python/tests/kernel/test_vqe_kernel.py
Addresses failing tests
Follow-up to https://github.com/NVIDIA/cuda-quantum/pull/1252
Issue https://github.com/NVIDIA/cuda-quantum/issues/1245
=> [experimental/python] Fixes to support Python v3.8 - part#2

runtime/cudaq/platform/orca/CMakeLists.txt, runtime/cudaq/platform/orca/OrcaQPU.cpp
=> Decode orca-url

lib/Frontend/nvqpp/ASTBridge.cpp, test/AST-Quake/lambda.cpp, test/AST-Quake/single_qubit_ctor.cpp, test/AST-Quake/template_kernel.cpp, tools/fixup-linkage/fixup-linkage.cpp
Adds the target triple and data_layout from the frontend.
Prep work for later.
=> Add target information to the module.

.github/workflows/test_in_devenv.yml, python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_control_operations.py, python/tests/kernel/test_kernel_features.py
Addressing one gap in issue https://github.com/NVIDIA/cuda-quantum/issues/1251
=> [experimental/python] Support for legacy control operations in MLIR mode

python/cudaq/runtime/utils.py, python/runtime/cudaq/algorithms/py_observe_async.cpp, python/tests/kernel/test_observe_kernel.py
necessary for fixes to `multi_gpu_workflows.ipynb`
=> Better error checking for erroneous broadcast arguments

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernels/uccsd.py, runtime/nvqir/NVQIR.cpp
Also implement `theta *= -1.0` aug-assign node.
=> Fix SymbolTable error with print statements

NOTICE, lib/Optimizer/CodeGen/LowerToQIR.cpp, python/CMakeLists.txt, python/cudaq/_cudaq.cpp, python/runtime/cudaq/algorithms/py_draw.cpp, python/runtime/cudaq/algorithms/py_draw.h, python/tests/unittests/test_kernel_builder.py, runtime/cudaq/CMakeLists.txt, runtime/cudaq/algorithms/draw.cpp, runtime/cudaq/algorithms/draw.h, runtime/nvqir/CircuitSimulator.h, unittests/CMakeLists.txt, unittests/integration/draw_tester.cpp
Enable circuit drawing apart from library mode. Supersedes #1201 , picked up that work to help out @boschmitt on paternity leave.
=> Finish up circuit drawing, expose to python

runtime/cudaq/platform/mqpu/nvqc.config
Need to add link lib explicitly due to `mqpu` lib restructure.
=> Fix `nvqc.config`

docs/sphinx/examples/python_mlir/intro.py, python/cudaq/qis/__init__.py, python/cudaq/qis/qis.py
* Added stub definitions for quantum operations.
=> Pylance stopgap

.github/workflows/config/gitlab_commits.txt
Update MGPU commit SHA to pick up changes in error messages.
=> Update mgpu commit hash

.github/workflows/test_in_devenv.yml, lib/Optimizer/CAPI/CMakeLists.txt
Ensure `cudaq/Optimizer/Dialect/Quake/QuakeDialect.h.inc` is generated before `CAPI` is built.
=> Fix for intermittent CI build failure.

docs/sphinx/examples/cpp/algorithms/bernstein_vazirani.cpp
named in the CUDA Quantum Specification.
=> Fix the example to use std::vector<bool>, which is a type that is

docs/sphinx/examples/cpp/algorithms/bernstein_vazirani.cpp
Addresses review comment left earlier.
=> Fix bug left over from residual code.

.github/workflows/test_in_devenv.yml
Cherry-picking https://github.com/NVIDIA/cuda-quantum/pull/1355
=> Update CI to use iqm-client v16.1 (not v17.0)

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
Adjustments based on product feedback
=> [nvqc] Adjust client log messages

.github/workflows/integration_tests.yml
These execution tests (i.e., checking the results, not IR-level checks) are now added to NVQC verification for both Docker containers and Python wheels.
A sample run: https://github.com/NVIDIA/cuda-quantum/actions/runs/8182667458
=> [NVQC] Add Python MLIR tests to the nightly integration test workflow

lib/Optimizer/Dialect/CC/CCOps.cpp
Folder had assumed float point typed constants.
=> [Core] Fix a bug in folding of constants.

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
Adjustments based on product feedback.
=> Revise NVQC error message

docs/sphinx/examples/python/cuquantum_backends.py
Sets the default qubit count to 5 for the cutensornet example to speed up CI
=> [docs] Update cutensornet example in CI

runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu
=> Fix memory leak in CuStateVecCircuitSimulator.cu

.github/workflows/clean_up.yml, .github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, scripts/build_cudaq.sh
... and adding a clean up job.
Signing fix confirmed here: https://github.com/NVIDIA/cuda-quantum/actions/runs/8436096454
=> Fixing the signing issue

include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/DecompositionPatterns.cpp
These functions weren't being used much any longer. Go ahead and eliminate them.
=> Discard unneeded helper functions.

.github/workflows/clean_up.yml, .github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, pyproject.toml, scripts/build_cudaq.sh
Cherry-pick #1441 and #1442 from main for build purposes
=> Cherry pick #1441 and #1442 from main

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/qalloc_initialization.cpp
=> [features/qalloc] Add qudit initializer to bridge.

python/tests/parallel/test_mqpu.py
* Update the `nTerms` to match the `spin_op` random generator logic
- For 4 qubits, `nTerms = 70`
=> [fix] [test] Updates to 'nvidia-mqpu' test - 'testLargeProblem'

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/qalloc_initialization.cpp
The initializer length must be 2**q where q is the number of qubits.
=> Compute the correct number of qubits.

CMakeLists.txt, docs/sphinx/snippets/cpp/using/first_kernel.cpp, docs/sphinx/snippets/cpp/using/first_observe.cpp, docs/sphinx/snippets/cpp/using/first_sample.cpp, docs/sphinx/snippets/cpp/using/time.cpp, docs/sphinx/snippets/python/using/first_kernel.py, docs/sphinx/snippets/python/using/first_observe.py, docs/sphinx/snippets/python/using/first_sample.py, docs/sphinx/snippets/python/using/time.py
=> [NFC] Update copyrights.

docs/sphinx/api/languages/cpp_api.rst
=> [docs] Add cudaq::range function.

docs/sphinx/examples/cpp/providers/nvqc_qml.cpp
The example `docs/sphinx/examples/cpp/providers/nvqc_qml.cpp` needs some comments to clarify what it illustrates.
=> Add comments to the newly added docs example

python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_kernel_features.py
=> Fix issue with indexing raw args pointer for return value

runtime/common/JIT.h
Update code comment in `JIT.h` to reflect the updated implementation.
Addressing https://github.com/NVIDIA/cuda-quantum/pull/1435#pullrequestreview-2005917817
=> Update code comment in `JIT.h`

CMakeLists.txt, scripts/build_llvm.sh, scripts/generate_cc.sh
We previously implemented diff branch code coverage Per-PR in PR #576, but due to the installation limitations of code-cov, we temporarily abandoned this plan.
A script is provided here to facilitate generating code coverage locally and on automated systems. Later I will enable this to the internal automation system so that code coverage can be generated regularly
=> Provide a script to generate code coverage

docker/build/assets.Dockerfile
=> [experimental/StateHandling] Support new scikit-build-core release (#1551)

CMakeLists.txt, docs/sphinx/examples/cpp/providers/nvqc_qml.cpp, docs/sphinx/examples/python/intro.py, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_kernel_features.py, runtime/common/JIT.h, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/qudit.h, scripts/build_llvm.sh, scripts/generate_cc.sh, test/AST-Quake/string-0.cpp, test/AST-Quake/string-1.cpp, tools/cudaq-translate/cudaq-translate.cpp, tools/fixup-linkage/fixup-linkage.cpp
=> [experimental/stateHandling] merge main to branch

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
=> Allow measurement of variadic list of qubits

include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/LowerToQIRProfile.cpp, lib/Optimizer/CodeGen/VerifyNVQIRCalls.cpp
Requires #1565 to be merged first.
=> Refactor verify NVQIR calls pass into a separate source file

docs/sphinx/api/default_ops.rst, docs/sphinx/api/languages/python_api.rst, include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/tests/backends/test_Quantinuum_LocalEmulation_kernel.py, python/tests/builder/test_kernel_builder.py, python/tests/kernel/test_kernel_features.py, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/qis/qubit_qis.h, runtime/nvqir/Gates.h, runtime/nvqir/NVQIR.cpp, unittests/qir/NVQIRTester.cpp, unittests/qis/QubitQISTester.cpp
Partially addresses issue https://github.com/NVIDIA/cuda-quantum/issues/1507
=> Expose the U3 operation to frontends

docs/sphinx/using/backends/simulators.rst
Fix broken documentation link that block PRs (see failing tests in https://github.com/NVIDIA/cuda-quantum/pull/1590)
=> Fix broken link in documentation

lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake-QIR/argument.qke, test/Quake-QIR/return_values.qke
Already reviewed here: #1596 
Merging back for further refactoring.
=> [cherry-pick] Merge changes made to stateHandling back to main.

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_complex.py, python/tests/kernel/test_kernel_float.py
Add python support for calling `numpy.exp` inside kernel functions.
=> [python] Add np.exp support

lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake/kernel_exec-1.qke, test/Quake/return_vector.qke
This is a follow up PR to #1604 
Refactor common code so it is easier to maintain.
=> [GKE] refactor to share common code

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_complex.py, python/tests/kernel/test_kernel_float.py
This is a cherry-pick of the following change from the `experimental/stateHandling` branch:
https://github.com/NVIDIA/cuda-quantum/commit/8ef7f12e010aed06cfc986f44e7e24fba1533d6d
=> Cherry pick `np.exp` support to main (#1590)

.github/workflows/config/gitlab_commits.txt
This PR updates commit hash containing code under mgpu's MR!13. We don't merge that MR yet to keep mgpu's `main` aligned with CUDA-Q's `main`.
We pump this commit hash to unblock the Publishing pipeline of the experimental branch to produce Docker images.
Example downstream pipeline [run](https://gitlab-master.nvidia.com/nvhpc/cuda-quantum/-/jobs/91278993): using a test branch to run the downstream pipeline checking out that commit `990ac52472ccc35503bd97395d4718788f1e121c`.
=> Update `cuquantum-mgpu` commit hash

.github/workflows/config/gitlab_commits.txt, python/tests/kernel/test_observe_kernel.py, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu
=> Fix observe for 0 terms and add test

runtime/cudaq/platform/default/rest/helpers/iqm/Aphrodite.txt, runtime/cudaq/platform/default/rest/helpers/iqm/CMakeLists.txt
Connectivity mapping for IQM 54qubits QPU.
=> IQM Aphrodite QPU support

runtime/common/Future.cpp, runtime/common/ServerHelper.h, runtime/cudaq/platform/default/rest/helpers/iqm/IQMServerHelper.cpp
Follow-up to #1632 - fix spelling
=> Follow-up to #1632 - fix spelling

docker/release/cudaq.wheel.Dockerfile
The original cuQuantum 24.03 wheel was removed and replaced with 24.03.0.post1.
=> Update to cuquantum-cu11==24.03.0.post1

docs/sphinx/specification/cudaq/examples.rst, python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Addresses issue captured in #1622
=> [Fix] [Python] Enable 'reset' in Python kernel mode

lib/Optimizer/CodeGen/ConvertToQIR.cpp, test/Quake-QIR/qalloc_initfloat.qke
Must call the correct qubit_allocate_array_with_state function. See #1670
=> Call the correct QIS function.

python/cudaq/mlir/dialects/CCOps.td, python/runtime/mlir/py_register_dialects.cpp
~Fixes failures in some python tests.~
=> [stateHandling] Fix bug in guard

lib/Optimizer/CodeGen/ConvertToQIR.cpp
https://github.com/NVIDIA/cuda-quantum/pull/1659#discussion_r1601969511
=> Code review.

runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp
=> Fix banner so it isn't 81 columns.

lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/CodeGen/VerifyNVQIRCalls.cpp, python/tests/remote/test_remote_platform.py, runtime/common/BaseRestRemoteClient.h, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp
Resolves #1663 
Note: this requires updates on the NVQC servers in order to fully resolve the issue, and that is not planned until 0.8 is released.
=> Allow math dialect to lower and run on NVQC

docs/sphinx/using/quick_start.rst
=> Fix typo of link in quick_start.rst

runtime/cudaq/algorithms/get_state.h, runtime/cudaq/qis/state.cpp
=> [stateHandling] Remove vestigial code that is not going to be used.

docs/sphinx/examples/cpp/providers/orca.cpp, docs/sphinx/examples/python/providers/orca.py, python/CMakeLists.txt, python/CUDAQuantumExtension.cpp, python/cudaq/__init__.py, runtime/cudaq/platform/orca/OrcaQPU.cpp, runtime/cudaq/platform/orca/orca_qpu.h, scripts/validate_container.sh
* Expose the ORCA-specific APIs to Python front-end
-  Documentation to be added later (Omar) 
-  Integration tests will be covered separately (Pradnya)
=> ORCA Python support

include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/ConvertCCToLLVM.cpp, lib/Optimizer/CodeGen/ConvertToCC.cpp, lib/Optimizer/CodeGen/ConvertToQIR.cpp, test/Quake/cc_execution_manager.qke
=> Add pass to convert cc dialect to LLVM-IR dialect.

lib/Optimizer/Transforms/LowerToCFG.cpp, test/Quake/to_cfg.qke
Fix #1749. The CFG for do-while was incorrect.
=> Fix #1749 - bad cfg conversion

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Factory.h, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, lib/Optimizer/Builder/Factory.cpp
Prep for merge to main. Audited the compiler core changes and found some code cleanups.
=> [stateHandling] Code cleanup.

.github/workflows/config/gitlab_commits.txt
Pull in the updates from MR# 16 and 17 downstream to fix the publishing pipeline (the change in https://github.com/NVIDIA/cuda-quantum/pull/1599 was probably undone by a merge from `main`) and to test the code changes in `mgpu` backend early via the Publishing pipeline of the experimental branch.
=> Update commit hash of the downstream `mgpu` backend

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, test/AST-Quake/qalloc_initialization.cpp, test/AST-Quake/qalloc_state.cpp, test/AST-Quake/veq_size_init_state.cpp
Teach veq_size to fold when it's input is a quake.init_state.
Fixes #1719
=> [Core] Fix #1719

lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, targettests/execution/sim_gate_timing-cpp17.cpp, targettests/execution/sim_gate_timing.cpp
- Adds code to the bridge to handle differences in the standard header implementations
- Modifies tests that used unsupported features
Fixes #1712
=> Fixes #1712: failures when using libc++

test/Quake-QIR/qalloc_initialization.qke
Add a test to exercise the conversion of a kernel that uses state initialization to QIR.
=> Add a qalloc initialization test.

lib/Optimizer/Builder/Intrinsics.cpp, test/Quake/cc_execution_manager.qke
=> [codegen] Fix bug between compute_ptr and getelementptr.

lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/CodeGen/QuakeToCC.cpp, test/Quake/cc_execution_manager.qke
=> [codegen] Fix a couple more bugs in quake2cc

lib/Optimizer/CodeGen/ConvertToCC.cpp, lib/Optimizer/CodeGen/QuakeToCC.cpp, test/Quake/quake_to_cc.qke
=> Fix some more bugs in lower quake pass.

docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu
=> Fix stack overflow when running with a large number of shots

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td
This file was getting pretty scattered with related operations thrown in all over the place. This change just sorts the deck of cards so related operations are grouped together.
=> [NFC] Reorganize the quake.td file

test/AST-Quake/initialization_list.cpp
Tests that the distinction between lowering an initialization list to be used for a state initialization vs. an initialization list that we expect to constant fold into the quantum circuit.
=> Add initialization_list test.

lib/Optimizer/Transforms/LowerToCFG.cpp, test/Quake/to_cfg.qke
The pass needed to be updated to handle cc.scope which allows arbitrary control flow regions nested within it now.
Add a test.
=> [core] Fix bug in lower-to-cfg

runtime/nvqir/cutensornet/mps_simulation_state.cpp, runtime/nvqir/cutensornet/tensornet_state.cpp, runtime/nvqir/cutensornet/tn_simulation_state.cpp
Adds fine-grained trace logs for `cutensornet` API calls to assist future performance analysis/debugging.
=> Add more performance traces to `tensornet` backends

python/runtime/cudaq/algorithms/py_sample_async.cpp, python/tests/builder/test_observe.py, python/tests/builder/test_sample.py
Fix for https://github.com/NVIDIA/cuda-quantum/issues/1218
=> [Bug-fix] [Python] Address scoping issue for `sample_async`

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, test/Quake/roundtrip-ops.qke
Add the op with a verifier and canonicalizer. Add to roundtrip test. Will add codegen for this next.
Depends of #1862
=> [core] Add offsetof operation to CC dialect.

tools/cudaq-qpud/README.md
Add some developer docs for `remote-mqpu` and `nvqc`.
=> [NFC] Add tools/cudaq-qpud/README.md

lib/Optimizer/Transforms/QuakeSynthesizer.cpp, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, unittests/Optimizer/QuakeSynthTester.cpp
=> [QuakeSynth] Reify std::vector<pauli_word> arguments as constants.

.github/workflows/integration_tests.yml, .github/workflows/nvqc_regression_tests.yml
Some new tests added in https://github.com/NVIDIA/cuda-quantum/pull/1920 were intended for library mode serialization testing; yet were picked up by NVQC integration CI causing failures.
Hence, I added a GitHub issue to track this and removed the tests with references to the issue.
=> Exclude some tests in integration pipelines pending future fixes

python/cudaq/kernel/register_op.py, python/tests/custom/test_custom_operations.py
* Fix the Python `SyntaxWarning: assertion is always true, perhaps remove parentheses?`
* Update comment in tests to point to GitHub issue
=> [Python] Follow-up to PR#1968

lib/Optimizer/CodeGen/VerifyNVQIRCalls.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, targettests/Remote-Sim/pauli_word.cpp
=> Implement synthesis for Pauli words

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/api/default_ops.rst, docs/sphinx/snippets/cpp/using/two_qubit_custom_op.cpp, docs/sphinx/snippets/python/using/examples/two_qubit_custom_op.py
=> [docs] Document the API for custom operations

runtime/common/BaseRemoteRESTQPU.h, runtime/cudaq/builder/kernel_builder.cpp
=> Update the pipeline constructions so they are more linear with the

targettests/execution/mapping_test-1-cpp17.cpp, targettests/execution/mapping_test-1.cpp, targettests/lit.cfg.py
Currently running tests modifies the source tree. This confuses git into thinking new untracked changes have been created.
These changes nip that in the bud.
=> Do not copy files in the source tree when running tests.

include/cudaq/Optimizer/Transforms/Passes.td
=> [NFC] Minor copy edits for consistent spellings, etc.

lib/Optimizer/Transforms/LiftArrayAlloc.cpp
See https://github.com/NVIDIA/cuda-quantum/pull/2035#discussion_r1709916502
=> Use LLVM ADTs.

python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/utils/OpaqueArguments.h, runtime/common/BaseRemoteRESTQPU.h
These changes convert the python runtime over to use the new argument synthesis pass.
=> [python runtime] Use argument synthesis pass

lib/Optimizer/Transforms/MemToReg.cpp
New code pattern exposed that memtoreg was trying to promote a value in memory even though its address was taken. This fix is needed for the new argument synthesis work.
=> [arg synth] Test that address of variable isn't taken.

lib/Optimizer/Transforms/LowerToCFG.cpp, test/Quake/to_cfg.qke
cc.if now has linear block arguments, which have to be threaded. Extend test coverage to cc.if and cc.loop.
=> Fixes bug in lower to cfg.

docs/sphinx/examples/python/tutorials/Divisive_clustering.ipynb, docs/sphinx/examples/python/tutorials/divisive_clustering_src/divisive_clustering.py, docs/sphinx/examples/python/tutorials/divisive_clustering_src/main_divisive_clustering.py
This will hopefully fix this publishing failure: https://github.com/NVIDIA/cuda-quantum/actions/runs/10493638995/job/29071381278
=> Make divisive clustering notebook repeatable

python/cudaq/qis/__init__.py
=> Fix typo in qis.__init__.py

python/cudaq/kernel/register_op.py, python/tests/custom/test_custom_operations.py
=> [Python] [custom op] Improve error handling

scripts/validate_container.sh
(Worked in collaboration with @sacpis)
Will enable resolution of existing publishing failure (when combined with #2167) and also resolves #2153.
=> [test] Fix package install issue during Publishing tests

docker/build/assets.Dockerfile, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, targettests/Kernel/signature-2.cpp
which can be passed as multiple (2) arguments.
=> [core] Fixes a bug in handling of small structs

lib/Optimizer/Transforms/RegToMem.cpp, test/Quake/memtoreg-7.qke
These changes continue the improvement of the regtomem pass, allowing it to handle more cases. Add checks for IR in pruned control form, which is incompatible. Add a new test.
=> [core] Implement some regtomem TODO items.

docs/sphinx/examples/cpp/providers/photonics.cpp, runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp
Towards: 'photonics' target support
* Added `get_state` API in C++ frontend
* Python bindings to be added after PR #2055
=> [photonics] [C++] Support 'get_state' API

lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp
Canonicalization patterns should return failure if they don't modify the IR.
=> Fix issue #2196

test/Translate/translate_openqasm2_loop.cpp, test/Translate/translate_openqasm2_simple.cpp, test/Translate/translate_openqasm2_vector.cpp
=> Use the standard C++ file banner.

include/cudaq/Optimizer/Dialect/CC/CCTypes.td, lib/Frontend/nvqpp/ConvertDecl.cpp, runtime/cudaq/cudaq.cpp, runtime/cudaq/qis/qkernel.h, runtime/cudaq/qis/qubit_qis.h, runtime/cudaq/utils/registry.h, targettests/SeparateCompilation/basic.cpp, targettests/SeparateCompilation/class.cpp, targettests/SeparateCompilation/deduction_guide.cpp, targettests/SeparateCompilation/emulate.cpp, targettests/SeparateCompilation/lambda.cpp, targettests/SeparateCompilation/multiple_callables.cpp, targettests/execution/cudaq_observe.cpp, test/AST-Quake/indirect_callable.cpp
=> Renaming qkernel_ref to qkernel per the spec.

.github/workflows/integration_tests.yml, docs/sphinx/examples/cpp/providers/orca.cpp, docs/sphinx/examples/cpp/providers/orca_mqpu.cpp, docs/sphinx/examples/python/providers/orca_mqpu.py, runtime/cudaq/platform/mqpu/MultiQPUPlatform.cpp, runtime/cudaq/platform/orca/OrcaRemoteRESTQPU.cpp, runtime/cudaq/platform/orca/OrcaRemoteRESTQPU.h, runtime/cudaq/platform/orca/orca.yml, runtime/cudaq/platform/quantum_platform.cpp
=> Add multi-QPU support for the 'orca' target

.github/workflows/config/gitlab_commits.txt, runtime/common/MeasureCounts.cpp, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cpp, runtime/nvqir/cutensornet/simulator_cutensornet.cpp, runtime/nvqir/qpp/QppCircuitSimulator.cpp, runtime/nvqir/stim/StimCircuitSimulator.cpp, unittests/integration/builder_tester.cpp
=> Fix mid-circuit measurement if reset follows measurement

.github/workflows/config/gitlab_commits.txt
Changes:
- Fixed integer overflow when converting `CUDAQ_MAX_GPU_MEMORY_GB` to bytes.
- Fixed issues with large `CUDAQ_MAX_CPU_MEMORY_GB` setting: always cap it based on actual memory availability.
- Fixed an issue with setting validation: some settings that allow zero was wrongly rejected.
See cuquantum-mgpu MR!30
=> Update mgpu commit sha

.github/workflows/integration_tests.yml, .github/workflows/nvqc_regression_tests.yml
This is a temporary workaround for #2299.
=> Disable building_kernels.py test for nightly NVQC tests

docker/build/assets.Dockerfile, runtime/cudaq/CMakeLists.txt, runtime/cudaq/utils/tensor.cpp, runtime/cudaq/utils/tensor.h, unittests/CMakeLists.txt, unittests/utils/Tensor.cpp
This PR supercedes and greatly simplifies the work in PR #2304 . The implementation is streamlined for the upcoming release.
=> [runtime] Add a new matrix class.

.github/CODEOWNERS, .github/workflows/deployments.yml, .github/workflows/documentation.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml
These permissions are necessary for the workflow to work on private forks.
Also, updating code ownership for github workflows.
=> Adding missing permissions and other small fixes

.github/workflows/nvqc_regression_tests.yml
Fix for NVQC integration test
https://github.com/NVIDIA/cuda-quantum/actions/runs/11789940366/job/32839604783#step:4:60
Fix by @1tnguyen. Thank you @1tnguyen.
=> Fix for NVQC integration test

include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Dialect/Quake/QuakeTypes.cpp, test/Quake/invalid.qke, test/Quake/roundtrip-ops.qke
=> Add some missing type verification.

.github/workflows/clean_up.yml, .github/workflows/docker_images.yml, docker/build/devdeps.ext.Dockerfile, docker/release/cudaq.Dockerfile, docs/sphinx/conf.py, runtime/nvqir/custatevec/CMakeLists.txt, runtime/nvqir/cutensornet/CMakeLists.txt
Fixes https://github.com/NVIDIA/cuda-quantum/issues/2409
=> Pipeline fixes

docs/sphinx/using/backends/platform.rst
Fixed https://github.com/NVIDIA/cuda-quantum/issues/2462
=> Fix a typo in the docs: mgpu -> mqpu

python/tests/operator/test_evolve_simulators.py
Hopefully this fixes the failure in https://github.com/NVIDIA/cuda-quantum/actions/runs/12661410519/job/35285524933?pr=2495.
=> [test] Fix evolve test repeatability issue

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/character_comparison.cpp
=> [C++] Add support for character literals to the C++ bridge.

docker/build/cudaq.dev.Dockerfile
Testing for segmentation fault
=> limiting the compilation to 4 parallel jobs

.github/workflows/config/gitlab_commits.txt
Changes:
- cuda-quantum/cuquantum-mgpu!36: fix a bug in trajectory simulation
- cuda-quantum/cuquantum-mgpu!37: fix a bug in `applyExpPauli`: invalid value errors when the pauli word is acting on a subset of qubits.
=> Update `cuquantum-mgpu` commit

.github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/generate_cc.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml
This change will eventually need to be reverted once the NV GH runners get updated next week, but this should allow the Deployment to start working again.
=> [ci] Update runners to use -testing suffix for now

runtime/cudaq.h, runtime/cudaq/algorithms/run.h
=> Add a cudaq::run template.

runtime/cudaq/algorithms/run.h
=> [features/run] Fix for build failure(s)

runtime/common/ExecutionContext.h, runtime/nvqir/NVQIR.cpp
These need to output to something other than std::cout. Using std::cout temporarily...
=> Add output function stubs to NVQIR.cpp.

python/tests/backends/test_braket.py, runtime/common/BraketServerHelper.h, runtime/cudaq/platform/default/rest/helpers/braket/BraketServerHelper.cpp, runtime/cudaq/platform/quera/QuEraServerHelper.cpp
* Manually tested following files:
- test_braket.py
- test_quera.py
- braket.py with IQM/Garnet and IonQ/Forte-1
(didn't wait for results in case of hardware devices)
=> [braket] Remove the hardcoded device list and qubit count

runtime/cudaq/CMakeLists.txt, runtime/cudaq/algorithms/run.cpp
=> Sketch the implementation of `runTheKernel`.

lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/Transforms/QuakeAddMetadata.cpp
=> A couple of bug fixes.

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
=> [python] Implement ast.[In, NotIn] comparator, fix 2611

targettests/execution/uccsd.cpp
=> Re-enable the uccsd test.

docs/sphinx/using/backends/cloud/braket.rst
Signed-off-by: Tim <yitchen@amazon.com>
Update Braket example and doc links to point to the specific page of CUDA-Q.
=> [braket] update Braket example and doc links

runtime/common/ExecutionContext.h, runtime/common/RecordLogDecoder.h, runtime/cudaq/algorithms/run.cpp
=> [features/run] Sketching some more code.

.github/workflows/deployments.yml, .github/workflows/publishing.yml, docker/build/assets.Dockerfile, docker/build/devdeps.ext.Dockerfile, docker/build/devdeps.manylinux.Dockerfile, docker/release/cudaq.ext.Dockerfile, docker/release/cudaq.wheel.Dockerfile, docker/test/installer/runtime_dependencies.sh, pyproject.toml, python/cudaq/__init__.py, scripts/configure_build.sh
This is a new dependency needed for the trajectory based noisy simulation.
=> Adding dynamic curand dependency

docs/sphinx/using/backends/hardware/neutralatom.rst
=> Remove broken links

include/cudaq/Optimizer/Builder/Runtime.h, lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/CodeGen/ReturnToOutputLog.cpp, runtime/common/ExecutionContext.h, runtime/common/RecordLogDecoder.cpp, runtime/common/RecordLogDecoder.h, runtime/cudaq/algorithms/run.cpp, runtime/cudaq/algorithms/run.h, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, targettests/execution/cudaq_run.cpp, test/AST-Quake/cudaq_run.cpp, tools/cudaq-quake/cudaq-quake.cpp, tools/nvqpp/nvq++.in, unittests/output_record/RecordParserTester.cpp
Add a test.
Add the pass to convert return types and get end-to-end flow working.
=> [features/run] Work on getting things working end to end.

runtime/common/NoiseModel.h, runtime/cudaq/algorithms/base_time_stepper.h
Add a couple of missing headers
=> [Fix] Add missing headers.

.github/workflows/config/gitlab_commits.txt
Downstream changes: [NFC] Include "cudaq_utils.h" header explicitly. See MR!56.
=> Fix downstream mgpu build pipeline

targettests/execution/to_integer.cpp
This test doesn't work. It's unclear how it got past the CI. Opening issue #2785.
=> Disable the to_integer target test.

runtime/cudaq/algorithms/run.cpp, runtime/cudaq/algorithms/run.h, targettests/Remote-Sim/cudaq_run.cpp, targettests/execution/cudaq_run.cpp, targettests/execution/cudaq_run_emulation.cpp, targettests/execution/cudaq_run_noisy.cpp
- Adjust the API so that we don't need to construct a `std::function` explicitly.
- Add `async` API.
- Adjust existing tests and add `async` tests.
=> Make `cudaq::run` API template easier to use

runtime/cudaq/qis/execution_manager.h
=> Add `const` to prevent compilation errors.

.github/workflows/config/gitlab_commits.txt
Revert the 4th bullet point in https://github.com/NVIDIA/cuda-quantum/pull/2774
This feature/optimization needs more consideration to be appropriate for different execution scenarios, especially in Python.
e.g., target switching, usage of third-party MPI library (mpi4py).
=> Update `mgpu` sha: revert initial state reuse optimization

python/cudaq/__init__.py, python/cudaq/kernel/kernel_decorator.py, python/cudaq/runtime/run.py, python/extension/CMakeLists.txt, python/extension/CUDAQuantumExtension.cpp, python/runtime/common/py_ExecutionContext.cpp, python/runtime/cudaq/algorithms/py_run_async.cpp, python/runtime/cudaq/algorithms/py_run_async.h, python/runtime/cudaq/target/py_runtime_target.cpp, python/tests/backends/test_Quantinuum_LocalEmulation_kernel.py, python/tests/kernel/test_run_kernel.py, python/tests/remote/test_remote_platform.py, python/utils/LinkedLibraryHolder.cpp, python/utils/LinkedLibraryHolder.h, runtime/nvqir/NVQIR.cpp
Python implementation of `cudaq.run` mirroring the C++ API implementation.
Support all flavors: with/without noise, local sim/remote sim/hardware emulation, async.
Add tests for those scenarios.
=> Python support for `cudaq::run`

lib/Optimizer/Dialect/CC/CCOps.cpp, test/Quake/cast_fold.qke, test/Quake/invalid.qke
=> [core] Add verify check for invalid cc.cast operations.

include/cudaq/Optimizer/Builder/Marshal.h, include/cudaq/Optimizer/Builder/Runtime.h, lib/Optimizer/Builder/CMakeLists.txt, lib/Optimizer/Builder/Marshal.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/LowerToCFGPatterns.inc
This work is preparation for other future work.
This moves a bunch of code out of the GKE pass proper into the builder library where it can be used by other passes. There are various minor changes to rename things in this refactor, but the essential functionality is not changed.
=> [core] Prep work to refactor the GKE code.

lib/Optimizer/CodeGen/ReturnToOutputLog.cpp, test/AST-Quake/cudaq_run.cpp
=> Fix bug with wrong output call being selected.

lib/Optimizer/Transforms/QuakeSynthesizer.cpp
of Quake synthesis and argument synthesis more aligned. Quake synthesis is somewhat deprecated, but may still be used in some contexts.
=> These diffs are intended to make the code generation

python/runtime/common/py_ExecutionContext.cpp, runtime/common/CMakeLists.txt, runtime/common/RecordLogParser.cpp, runtime/common/RecordLogParser.h, runtime/cudaq/algorithms/run.cpp, unittests/output_record/RecordParserTester.cpp
To avoid confusion with QEC nomenclature
=> [features/run] Renaming class

scripts/validate_pycudaq.sh
Follow-up to PR https://github.com/NVIDIA/cuda-quantum/pull/2817
=> [CI] [testing] Update the validation script to use the new location of 'integrator' tests

runtime/cudaq/operators/helpers.h
=> [rt][fix] Add missing header

lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/DecompositionPatterns.cpp, lib/Optimizer/Transforms/QuakeSimplify.cpp, python/tests/kernel/test_kernel_features.py, runtime/cudaq/qis/managers/BasicExecutionManager.h, test/Quake/quake_simplify.qke, unittests/qis/QubitQISTester.cpp
Fix bugs with the u3<adj> operator.
=> Fix #2863.

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Dialect/CC/CCTypes.h, include/cudaq/Optimizer/Dialect/CC/CCTypes.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.h, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Builder/Marshal.cpp, lib/Optimizer/CodeGen/ConvertToQIRProfile.cpp, lib/Optimizer/CodeGen/QuakeToLLVM.cpp, lib/Optimizer/CodeGen/VerifyQIRProfile.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/EraseNopCalls.cpp, lib/Optimizer/Transforms/ObserveAnsatz.cpp, lib/Optimizer/Transforms/RegToMem.cpp, lib/Optimizer/Transforms/UpdateRegisterNames.cpp, python/runtime/mlir/py_register_dialects.cpp, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/kernel_builder.cpp, utils/CircuitCheck/UnitaryBuilder.cpp
=> Update some of the old-school cast syntax.

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_decorator.py, python/tests/kernel/test_kernel_features.py
Support creating and field access for tuples:
```python
@cudaq.kernel
def kernel() -> int:
t = (-42, True, 13.5)
return t[0]
ret = kernel()
assert ret == -42
```
=> [python] Support creation and field access for tuples

lib/Optimizer/Transforms/MemToReg.cpp
=> Maintenance: remove some dead code.

Developing.md
Addresses: https://github.com/NVIDIA/cuda-quantum/issues/2318
=> [docs] Add instructions for rebuild, testing, formatting etc.

python/tests/mlir/control.py
These check lines fail every once in a while forcing developers to painfully have to re-run the CI. This updates the check lines, hopefully, in a way to stop these false failures.
=> Attempt to fix random, intermittent CI failures.

runtime/nvqir/cudensitymat/CuDensityMatState.h
=> [rt] Include unordered_map in CuDensityMatState.h

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_decorator.py, python/cudaq/kernel/utils.py, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_run_kernel.py, python/utils/OpaqueArguments.h, python/utils/PyTypes.h
Handle integers of various sizes when passing arguments in python.
=> [python] Handle integers of various sizes when passing arguments

python/cudaq/kernel/utils.py, python/runtime/cudaq/algorithms/py_run.cpp, python/tests/kernel/test_direct_call_return_kernel.py, python/tests/kernel/test_run_kernel.py
Address CR comments from merging features/run into main
(https://github.com/NVIDIA/cuda-quantum/pull/2927)
=> Address CR comments from merging features/run into main

lib/Frontend/nvqpp/ConvertExpr.cpp
Some of the math functions on the list only appear in MLIR after LLVM 16. However, we can add support for the rest to the C++ bridge. This patch adds support for sin, cos, tan, exp, log, ceil, and floor.
See issue #2942
=> [C++ bridge] Add support for some of the functions listed in issue 2942.

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_run_kernel.py
Fix for issue https://github.com/NVIDIA/cuda-quantum/issues/2966
=> [Python] Allow assignment on `dataclass` members

runtime/cudaq/algorithms/run.h, targettests/execution/cudaq_run.cpp, test/AST-error/cudaq_run.cpp
They are not fully supported as yet.
=> [cudaq::run] Disable std::vector return types for now.

include/cudaq/Optimizer/Transforms/Passes.td
=> [NFC] Alphabetize the passes.

runtime/nvqir/stim/CMakeLists.txt, runtime/nvqir/stim/verify_linkage.sh
=> Remove external linkage of Stim symbols in libnvqir-stim.so

python/tests/backends/test_Infleqtion.py, python/tests/backends/test_braket.py, runtime/cudaq/platform/default/rest/helpers/braket/braket.yml, runtime/cudaq/platform/default/rest/helpers/infleqtion/infleqtion.yml
=> [pipeline config] Add exp-pauli decompositions to OpenQASM2 backends.

python/tests/mlir/bug_3090.py, runtime/cudaq/qis/qubit_qis.h, runtime/nvqir/NVQIR.cpp
=> [apply_noise] Give warning if noise model is not provided.

docs/sphinx/using/integration/libraries.rst, docs/sphinx/using/quick_start.rst
While reading the docs, I have found a couple of typos that I'm fixing with this PR.
=> Fix typos in docs

runtime/common/ArgumentConversion.cpp, runtime/common/BaseRemoteRESTQPU.h
=> Fix bug with substitution module being overly pruned.

runtime/cudaq/cudaq.cpp
Organize a block of logic to make it a bit clearer.
=> [NFC] Minor cleanup.

.github/workflows/config/gitlab_commits.txt
Experimental performance optimization (see `cuquantum-mgpu`'s MR!61).
FYI @cuMikeBrown
=> Use mgpu input stage gate fusion optimization

python/runtime/cudaq/algorithms/py_sample_async.cpp, python/tests/builder/test_NoiseModel.py
Addressing https://github.com/NVIDIA/cuda-quantum/issues/843
=> [Python] Expose noise model to the asynchronous sample API

runtime/cudaq/driver/device.h
=> Add device.h header file.

runtime/common/RuntimeMLIRCommonImpl.h, targettests/execution/cudaq_run_emulation.cpp, tools/nvqpp/nvq++.in
We need a way to be able to activate `-fenable-cudaq-run` from the command line.
=> Honor -fenable-cudaq-run if the user explicitly provides it

lib/Optimizer/Transforms/DecompositionPatterns.cpp, python/tests/kernel/test_get_unitary.py, test/Transforms/BasisConversion/all-qir-gates.qke
* This pattern is needed by `quantinuum-gate-set-mapping`
* Python test to check decomposition
=> Adding a decomposition pattern for controlled-Y gate (CY)

lib/Optimizer/Transforms/MemToReg.cpp, test/Quake/memtoreg-6.qke
=> [core] Proper fix to memtoreg to allow variable coalescing to be turned on.

.github/workflows/config/gitlab_commits.txt, docs/sphinx/using/backends/sims/svsims.rst
Update mgpu sha:
(1) Fix a bug when running multi-GPU with a number of qubits < distributed threshold repeatedly.
(2) Add a custom gate fusion size for B300 (compute capability 10.3)
Update gate fusion doc: move the default settings into a table for readability.
=> Update mgpu sha and gate fusion doc

lib/Optimizer/Builder/Marshal.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/LowerToCFG.cpp, targettests/SeparateCompilation/gke.cpp
=> Fix bug with separate compilation of quasi-entry point kernels.

lib/Optimizer/Transforms/SROA.cpp, test/Quake/sroa.qke
Add CHECK lines to the commits.
Fixes #3370.
=> [core] Fix a type error in SROA pass.

lib/Optimizer/Transforms/ResourceCountPreprocess.cpp, runtime/common/RuntimeMLIR.cpp, runtime/common/RuntimeMLIRCommonImpl.h, utils/CircuitCheck/UnitaryBuilder.cpp
=> [NFC] cleanup some idioms when using isa<T>

runtime/common/BaseRemoteSimulatorQPU.h
=> [NFC] Removes dead PassManager declaration.

lib/Optimizer/Transforms/SROA.cpp, test/Quake/sroa.qke
=> [core] Add hoisting of loads to SROA's repertoire.
