lib/Frontend/nvqpp/ConvertStmt.cpp, test/AST-Quake/control_flow.cpp, test/AST-Quake/if_return.cpp, test/AST-Quake/while-2.cpp
Previous change introduced regressions on main. We don't want the regressions in the development branch.
I have read the Contributor License Agreement and I hereby accept the Terms.
=> Revert change to disable jump branching.

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, runtime/cudaq/qis/qubit_qis.h, test/AST-Quake/control.cpp
```c++
cudaq::control(Kernel{}, {ctrl1, ctrl2}, args...);
```
Get vector<reference_wrapper<qubit>> through the bridge.
Add simple test.
=> Add overload to handle the case when the user writes:

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/pull_request_template.md
Add a couple of issue templates and a PR template. Note that for bug reports, I propose that we first assign a `triage` label to indicate the need to confirm the reproducibility of the issue. Once this has been confirmed, one would change the label to `bug` so that someone can pickup for fixing. Feature request will be labeled as `enhancement`.
=> GitHub PR and issue templates

python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/unittests/test_sample.py, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, unittests/integration/builder_tester.cpp
We had left off these functions as an oversight. Fix that by adding them here. Tested in both C++ and Python.
Address #2
=> Add reset to kernel_builder in C++ and python.

.github/workflows/config/mlc_config.json, .github/workflows/link_and_spell_check.yml
This PR
- fixes a typo that caused the config file to be ignored,
- adds a particularly flaky link to the list of links to ignore,
- makes it so that the check is cancelled when new changes are pushed
=> Minor fixes for markdown link check

include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/AddDeallocs.cpp, test/AST-Quake/dealloc.cpp, test/Quake-QIR/basic.qke
This replaces the old deallocation pass with one that works with the global jump unwinding pass (unwind-lowering) to handle deallocation of quantum objects. This pass deals with deallocations in structured SEME regions such as func.func, cc.scope, and cc.create_lambda. See #14
=> Replace the old deallocation pass.

python/runtime/cudaq/spin/py_spin_op.cpp, python/tests/unittests/test_SpinOperator.py
=> Expose for_each_term and for_each_pauli to python

python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/unittests/test_bug64_quakevalue_lifetime.py, python/tests/unittests/test_observe.py, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/QuakeValue.h, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h
Fix issue with `QuakeValue` lifetime on instance returned from `QuakeValue::operator[](...)`. Fix issue with `kernel_builder::to_quake()` and multiple calls to print the quake code. 
#64
=> Fix `QuakeValue` Lifetime Bug and `kernel_builder::to_quake` Handling

tools/nvqpp/nvq++.in
This changes the behavior of the driver to only add the `-rpath` flags when linking the final binary. The main reason for this change is that the macOS linker does not allow adding `-rpath` option when merging object files. But also, when building in Linux, it seems unnecessary to add a `-rpath` flags when merging objects files (I think they get ignored anyway), and then again when doing the final binary liking.
=> [nvq++] Add RPATH flags only to the final binary

.devcontainer/devcontainer.json, .github/workflows/build_packages.yml, .github/workflows/ci.yml, .github/workflows/deployments.yml, .github/workflows/dev_environment.yml, docker/build/cudaqdev.Dockerfile, docker/build/devdeps.Dockerfile, docker/build/devdeps.ext.Dockerfile, docker/build/extdevdeps.Dockerfile, docker/release/cudaq.Dockerfile, scripts/build_llvm.sh, scripts/install_toolchain.sh
This PR takes care of the second prerequisite for https://github.com/NVIDIA/cuda-quantum/issues/41, as well as the remaining work items for https://github.com/NVIDIA/cuda-quantum/issues/57.
Specifically, it contains the following changes:
- Updates the CUDA Quantum Docker image to use the libstdc++-12.
- Adds llvm to the CI build and removes clang15 and gcc11.
- Adds a dockerfile containing all necessary build dependencies for gpu components, 
specifically CUDA (runtime only by default, but can be configured), OpenMPI, cuQuantum, and cuTensor
- Adds the option to build and deploy that image upon request from main and release branches 
(uses the same workflow as the CI and deployment for the more minimal devdeps image)
- Makes the dev_environment workflow generally usable for images that …
=> Adding a dev environment that contains all necessary CUDA and OpenMPI tools

.github/workflows/ci.yml, .github/workflows/clean_caches.yml, .github/workflows/deployments.yml, .github/workflows/dev_environment.yml
This should ensure that there is always an existing build cache for main and release branches. Caches created as part of CI will continue to be pushed to the gha cache.
This PR also creates a separate cache for the doxygen build, since otherwise doxygen is rebuilt in each matrix job when there are changes to the rest of the image.
=> Pushing the build caches for main and release branches to ghcr instead to the gha cache

python/utils/LinkedLibraryHolder.cpp, runtime/nvqir/CMakeLists.txt, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, runtime/nvqir/QIRTypes.h
This is how we do it everywhere else in the framework. The fact that we didn't in the NVQIR library is an oversight.
=> NVQIR files should use top-level relative include path

docs/sphinx/specification/cudaq/operations.rst, docs/sphinx/specification/cudaq/synthesis.rst
For some unknown reason they cause the sphinx builder script to crash and burn.
=> These are the documentation changes for PR #81.

utils/CircuitCheck/CMakeLists.txt
tests. It feels off to have build errors when trying to run the tests.
=> Build CircuitCheck as part of the build rather than as part of running

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, test/Quake/quake-ops.qke
This adds 3 new ops for #98. This is a preliminary PR and just adds the ops and a simple test.
=> Add new ops to quake.

include/cudaq/Optimizer/Dialect/Common/Ops.td
Fix to return the correct parameter as double
=> Fix getting op's parameters as double

utils/CircuitCheck/CMakeLists.txt, utils/CircuitCheck/CircuitCheck.cpp, utils/CircuitCheck/UnitaryBuilder.cpp, utils/CircuitCheck/UnitaryBuilder.h
CircuitCheck might failed if we don't canonicalize the IR before trying to build the unitary. This step is mainly to guarantee that operators parameters that are known at compilation time are defined by ArithDialect's  constant operation. For example:
```mlir
// CircuitCheck _cannot_ handle:
%cst = arith.constant 3.1415926535897931 : f64
%neg_cst = arith.negf %cst : f64
quake.rx |%neg_cst : f64| (%q0)
// CircuitCheck can handle:
%cst = arith.constant -3.1415926535897931 : f64
quake.rx |%cst : f64| (%q0)
```
This PR also:
- Improves error reporting
- Fixes the computation of global phase
=> [CircuitCheck] Run canonicalizer before checking

include/cudaq/Optimizer/Dialect/Quake/QuakeInterfaces.td
Add a method to retrieve the information whether controls are negated from the operator interface.
=> [quake] OperatorInterface method to get negated controls

docs/README.md, include/cudaq/Optimizer/Dialect/Quake/Canonical.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/QuakeObserveAnsatz.cpp, python/tests/compiler/conditional.py, python/tests/compiler/control.py, python/tests/compiler/measure.py, python/tests/compiler/multi_qubit.py, test/AST-Quake/control_flow.cpp, test/Quake-QIR/negated_control.cpp, test/Quake/adjoint-1.qke, test/Quake/bell.qke, test/Quake/canonical-1.qke, test/Quake/ccnot.qke, test/Quake/compute_action.qke, test/Quake/deuteron.qke, test/Quake/ghz.qke, test/Quake/lambda_variable-1.qke, test/Quake/observeAnsatz.qke, test/Quake/qpe.qke
Typically the index into the veq is a constant. These changes allow the op to hold the constant itself instead of relying on a ConstantOp. This will avoid issues with bad code sharing, allow the use of CSE, etc.
=> Fold constant into extract_ref op

lib/Optimizer/Dialect/Quake/QuakeOps.cpp, runtime/cudaq/algorithms/observe.h, runtime/cudaq/qis/managers/qir/QIRForwards.h, runtime/cudaq/qis/managers/qir/QubitQIRExecutionManager.cpp, runtime/cudaq/qis/qubit_qis.h, runtime/nvqir/NVQIR.cpp, unittests/integration/ccnot_tester.cpp
Fix #126. This only applies to library mode since future gate decomposition work will likely be needed for lower ctrl-swap for physical backends.
=> Fix Issue #126, whereby swap function did not allow ctrl modifier

runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/managers/qir/QIRForwards.h, runtime/cudaq/qis/managers/qir/QubitQIRExecutionManager.cpp, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, unittests/CMakeLists.txt, unittests/qudit/simple_qudit/SimpleQuditExecutionManager.cpp
For simulation (library-mode) ensure that `qreg q(N)` allocates all qubits at once. Ensure deallocations (when sampling or observing an operator) happen at once without explicit qubit reset.
=> Increase performance of quantum allocation and deallocation in simulation

include/cudaq/Optimizer/Transforms/CMakeLists.txt
This change enable the generation of docs for the transformation passes when building the `cudaq-doc` target.
=> [Optimizer] Generate docs transform passes

docs/CMakeLists.txt, runtime/common/QuditIdTracker.h, runtime/cudaq/platform/default/DefaultQuantumPlatform.cpp, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/managers/qir/QubitQIRExecutionManager.cpp, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/QIRTypes.h
The current methodology used by the ExecutionManager and the CircuitSimulator for creating unique qudit integer identifiers is not future proof. It currently keeps track of a discrete set of available qudit ids and caps the maximum number of qudits in a platform-specific manner. As we start to consider Clifford simulator plugins, this will become a problem, as we don't want to allocate and keep track of an enormous number of available qudit indices. 
This PR leaves the API exactly the same, but cleans up how qudit indices are handled internally.
=> Improve unique qudit index allocation and deallocation.

runtime/nvqir/qpp/QppCircuitSimulator.cpp, unittests/CMakeLists.txt
It looks like we missed a call to `std::vector`'s `erase` after using `std::unique`.
This will cause the underlying qpp lib to throw (dimension mismatches).
Run `test_domains` with `CUDAQ_OBSERVE_FROM_SAMPLING` environment variable set to false.
Hence, also added a variant of `test_domains`  unit test to check for this case.
=> Fixed a subtle bug in `QppCircuitSimulator::observe`

utils/CircuitCheck/UnitaryBuilder.cpp, utils/CircuitCheck/UnitaryBuilder.h
This PR allows CircuitCheck to verify decompositions that require ancillary qubits. It does this by treating local allocations as ancillas. For example:
```mlir
// It treat args as non-ancilla
func.func @cccz(%arg0: !quake.ref, %arg1: !quake.ref, %arg2: !quake.ref, %arg3: !quake.ref) {
%0 = quake.alloca !quake.ref // It will treat it as an ancilla
//...
}
```
The resulting unitary for the above circuit will only have 3 qubits (the arguments). CircuitCheck will also check if the ancilla(s) qubit(s) are properly cleaned up, i.e., intermediate results were uncomputed.
=> [CircuitCheck] Handle local qubits

python/tests/unittests/test_vqe.py, runtime/common/MeasureCounts.cpp, runtime/common/MeasureCounts.h, runtime/cudaq/domains/chemistry/molecule.h, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, runtime/nvqir/qpp/QppCircuitSimulator.cpp, unittests/Optimizer/QuakeSynthTester.cpp, unittests/domains/ChemistryTester.cpp
There is a discrepancy b/w `QppCircuitSimulator::sample()` and `CuStateVecCircuitSimulator::sample()` when computing `expectationValue` for the `shots > 0` case. `QppCircuitSimulator` always sets `expectationValue` to the true value, not from the shots distribution like `CuStateVecCircuitSimulator`.
This MR is to make `QppCircuitSimulator::sample()` consistent with  `CuStateVecCircuitSimulator::sample()`. 
Changes:
- Refactor the even parity checker into a static helper of `sample_result` (I think it is a logical place) to reduce code duplication.
- Move `QppCircuitSimulator::calculateExpectationValue` (compute the true expectation value) to within the `if` block (no need to do it when we don't need to).
- Compute and set the  `expectationValue` in `QppCircuitSimulator::sample()` from …
=> Fixed `QppCircuitSimulator` shots `ExecutionResult.expectationValue` 

python/tests/unittests/test_sample.py
Failure was due to random angles being too close to `0.0`, therefore not adequately rotating the state.
=> Fix sporadic python test error #191

runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/managers/qir/QubitQIRExecutionManager.cpp, runtime/cudaq/qis/qubit_qis.h, unittests/qis/QubitQISTester.cpp
This is probably a regression since https://github.com/NVIDIA/cuda-quantum/pull/167 
Specifically, `flushRequestedAllocations()` is not called when handling measurement at the concrete `ExecutionManager` implementation (i.e., `QIRExecutionManager`) with the assumption that it has been called during `executeInstruction()`.
This will lead to a Segfault in this case (no gates)
```
{
cudaq::qvector q(2);
mz(q);
}
```
For `reset` gate, there is a subtle issue w.r.t. gate ordering (leading to segfault eventually):
`ExecutionManager::resetQudit` is skipped by the middle `BasicExecutionManager` (where instruction batching occurs) and only implemented by the concrete subclass `QIRExecutionManager` -> `reset` op could be dispatched out of order due to no `synchronize()` call (-> segfault due to no …
=> Fixing segfault crashes when using measure/reset ops.

include/cudaq/Optimizer/Dialect/CC/CCOps.h, include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Dialect/CC/CCTypes.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Frontend/nvqpp/ConvertType.cpp, lib/Optimizer/Builder/CUDAQBuilder.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, python/tests/compiler/adjoint.py, python/tests/compiler/call.py, python/tests/compiler/control.py, python/tests/compiler/measure.py, python/tests/compiler/swap.py, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/AST-Quake/auto_kernel-1.cpp, test/AST-Quake/auto_kernel-2.cpp, test/AST-Quake/lambda_variable.cpp, test/AST-Quake/loop_unroll.cpp, test/AST-Quake/measure_bell.cpp, test/AST-Quake/mz.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/vector_bool.cpp
Fix tests. Add new CC ops to codegen for end-to-end compilation.
=> [bridge, runtime] Replace use of LLVM-IR dialect in the bridge and python interface with CC dialect operations.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, test/AST-Quake/loop_unroll.cpp, test/Quake/compute_ptr.qke
The compute_ptr op can have (and prefers) constant operands. Make sure constants get folded into the op whenever possible.
=> [cc] Add a folder to compute_ptr op.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/Builder/CUDAQBuilder.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/AST-Quake/auto_kernel-2.cpp, test/AST-Quake/mz.cpp, test/Quake/kernel_exec.qke, test/Quake/lambda_kernel_exec.qke
Continue to eliminate the use of the LLVM-IR dialect from the compiler. These patches replace the uses of LLVM-IR in the kernel-execution pass with uses of our CC dialect.
=> [cg] Move GenKernelExecution to CC dialect.

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Factory.h, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, lib/Optimizer/Transforms/QuakeAddMetadata.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, test/AST-Quake/adjoint-2.cpp, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/bool_literal.cpp, test/AST-Quake/compute_action-2.cpp, test/AST-Quake/control_flow.cpp, test/AST-Quake/empty_step.cpp, test/AST-Quake/if.cpp, test/AST-Quake/measure_bell.cpp, test/AST-Quake/mz.cpp, test/AST-Quake/nested_scope.cpp, test/AST-Quake/operators.cpp, test/AST-Quake/postfix_ops.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/simple_qarray.cpp, test/AST-Quake/single_qubit_ctor.cpp, test/AST-Quake/while-1.cpp, test/Quake/lambda_variable-2.qke, utils/CircuitCheck/CMakeLists.txt, utils/CircuitCheck/CircuitCheck.cpp
MLIR's Memref dialect offers full support for dynamic, multidimensional arrays. Since these are not part of C and not supported on the QPU, they are not needed. Rather than trying to constrain MLIR itself, we use the CC dialect to have direct control over the transformations applied to QPU code.
=> Remove the use of the MLIR Memref dialect.

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp
I'm currently working on adding more quantum operations to Quake. This PR is just reorganizing the definitions in the tabelgen file (old scheme was a bit confusing, so now gates appear in alphabetical order) and removes a method from that was only defined in some ops and only used by QTX .
=> [nfc][quake] Cleanup and reorganize quantum ops

python/utils/LinkedLibraryHolder.cpp, python/utils/LinkedLibraryHolder.h
Currently we create all available CircuitSimulators and quantum_platforms at Python startup. This is not very efficient since we'll likely only use one of each in a given Python execution. 
Update to load these pointers lazily via storage of a creation functor for each.
=> Load available simulators and platforms lazily in Python

runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/QuakeValue.h, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, unittests/integration/builder_tester.cpp
- Use `const QuakeValue &` for `reset` rather than `QuakeValue &` to handle the `reset(q_reg[idx])` use case since `QuakeValue::operator[]` returns a `QuakeValue` rval.
- `CUDAQ_BUILDER_ADD_ONE_QUBIT_PARAM` to handle floating-point params in adjoint and control code paths (in addition to the base one) by converting the floating point number to a `QuakeValue` if necessary.
=> Reset and and parametric gates in `kernel_builder`

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/LowerToBaseProfileQIR.cpp, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, test/NVQPP/bug_qubit.cpp, test/Quake/combine.qke
This is a direct fix to handle both array and single qubit allocations in the base profile pass.
Add a pass to combine quantum allocations.
=> Fix #251: Base profile should handle single qubit allocations.

CMakeLists.txt, python/_cudaq.cpp, python/runtime/cudaq/algorithms/py_observe.cpp, python/tests/CMakeLists.txt, python/tests/parallel/CMakeLists.txt, python/tests/parallel/run_mpi_py.sh.in, python/tests/parallel/test_mpi_mqpu.py, python/tests/parallel/test_mqpu.py, runtime/cudaq.h, runtime/cudaq/CMakeLists.txt, runtime/cudaq/algorithms/observe.h, runtime/cudaq/cudaq.cpp, runtime/cudaq/platform/mqpu/MultiQPUPlatform.cpp, runtime/cudaq/platform/quantum_platform.h, unittests/CMakeLists.txt, unittests/mqpu/mpi_mqpu_tester.cpp, unittests/mqpu/mqpu_tester.cpp, unittests/mqpu/run_mpi.sh.in
Add optional MPI support to CUDA Quantum. 
Implement `observe()` functions that distribute expectation value computations across available GPUs on a multi-node, multi-gpu system. 
User surface: 
```python
cudaq.mpi.initialize()
...
ansatz, parameters = cudaq.make_kernel(list)
... 
hamiltonian = ...
energy = cudaq.observe(ansatz, hamiltonian, args, execution=cudaq.par.mpi)
energy = cudaq.observe(ansatz, hamiltonian, args, execution=cudaq.par.thread)
energy = cudaq.observe(ansatz, hamiltonian, args)
cudaq.mpi.finalize()
```
```cpp
// Must initialize if using MPI
cudaq::mpi::initialize();
...
auto ansatz = [](std::vector<double> parameters) __qpu__ {
...
};
auto H = ... ;
// MPI Distribution
auto result = cudaq::observe<cudaq::par::mpi>(ansatz, H, args...);
// Single-node, multi-GPU …
```
=> Implement MPI support in CUDA Quantum

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, test/AST-Quake/loop_unroll-2.cpp
Bug fix to loop unrolling to handle multiple cc.loop arguments.
Fix test case for unrolling of for loop with upper bound stored in a
variable that can be register promoted, hoisted as an invariant, and
detected as a constant for a counted loop.
Depends on #287
=> Fix #286: Add canonicalization to hoist invariants cc.loop arguments.

runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp
Slightly more robust solution to parse target config scripts. We must re-address this when we refactor the driver.
=> Fix #276: Use regex to parse config file

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/LoopUnroll.cpp, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config
This adds an option to the loop unrolling pass that will signal a pass failure if it cannot unroll all loops.
Closes #277.
=> [opt] Flag to raise an error if cannot unroll a loop

lib/Optimizer/Transforms/MultiControlDecomposition.cpp, test/Transforms/multicontrol_decomposition.qke
This PR fixes #291. The decomposition function was wrongly returning `success()` when it was not transforming the IR.
=> [pass] Fix #291: don't erase non-controlled ops

lib/Optimizer/Transforms/GenDeviceCodeLoader.cpp, test/AST-Quake/adjoint-1.cpp, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/auto_kernel-1.cpp, test/AST-Quake/callable-1.cpp, test/AST-Quake/callable-2.cpp, test/AST-Quake/control.cpp, test/AST-Quake/ctor.cpp, test/AST-Quake/ctrl_vector.cpp, test/AST-Quake/empty_step.cpp, test/AST-Quake/lambda_instance.cpp, test/AST-Quake/lambda_variable.cpp, test/AST-Quake/measure_bell.cpp, test/AST-Quake/mz.cpp, test/AST-Quake/nested_scope.cpp, test/AST-Quake/passQregNToQSpan.cpp, test/AST-Quake/postfix_ops.cpp, test/AST-Quake/qbit_arg.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/simple.cpp, test/AST-Quake/single_qubit_ctor.cpp, test/AST-Quake/slice.cpp, test/AST-Quake/template_lambda.cpp, test/AST-Quake/typename.cpp, test/AST-Quake/vector.cpp, test/AST-Quake/vector_bool.cpp, test/AST-Quake/while-1.cpp, test/NVQPP/testDeviceCodeLoaded.cpp, tools/cudaq-quake/cudaq-quake.cpp
Enable line info in cudaq-quake. Allows the original C++ source lines to be passed to later stages.  Do not use pretty format, causes roundtrip issues.
=> Preserve the line information in the source code for JIT compilation.

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/LoopAnalysis.h, lib/Optimizer/Transforms/LoopNormalize.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config, test/AST-Quake/adjoint-2.cpp, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/loop_normal.cpp
Implement enhancement #288.
This pass converts monotonic loops with constant step into invariant loops or counted loops depending on whether the total number of iterations is constant. This pass has some limitations which can be addressed in future work. For now it will convert some interesting loops such as countdown loops, loops with steps != 1, etc.
Normalizing loops is an important transformation in that it will allow the loop unrolling pass to find more counted loops to unroll.
=> [pass] Add a loop normalization pass.

runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config, tools/cudaq-translate/cudaq-translate.cpp, unittests/Optimizer/QuakeSynthTester.cpp
This pass is added before the loop unrolling pass to give unrolling an opportunity to unroll more loops.
=> Add the loop normalization pass to the general set of pipeline passes.

test/NVQPP/graph_coloring-1.cpp, test/NVQPP/graph_coloring.cpp, test/NVQPP/sudoku_2x2-1.cpp, test/NVQPP/sudoku_2x2.cpp, test/NVQPP/test-0.cpp, test/NVQPP/test-1.cpp, test/NVQPP/test-2.cpp, test/NVQPP/test-3.cpp, test/NVQPP/test-4.cpp, test/NVQPP/test-5.cpp, test/NVQPP/test-6.cpp
This depends on #321 
For now, some tests are named `test-<number>` for my lack of imagination. I left comments on reasons why some of them are not passing as well as for things that we are supposed to support, but don't when compiling to a target.
Failed Tests (8):
CUDAQ :: NVQPP/sudoku_2x2-1.cpp (#343)
CUDAQ :: NVQPP/test-0.cpp (#336)
CUDAQ :: NVQPP/test-1.cpp (#337)
CUDAQ :: NVQPP/test-2.cpp (#344)
CUDAQ :: NVQPP/test-3.cpp (#341)
CUDAQ :: NVQPP/test-4.cpp (#345)
CUDAQ :: NVQPP/test-5.cpp (#339)
CUDAQ :: NVQPP/test-6.cpp (Not a bug. We could improve error message, tho.)
=> [test] Add some target compilation tests

include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Optimizer/Transforms/AggressiveEarlyInlining.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, runtime/cudaq/builder/kernel_builder.cpp, tools/cudaq-opt/cudaq-opt.cpp, tools/cudaq-translate/cudaq-translate.cpp, tools/nvqpp/nvq++.in
Add it to the pass pipeline. Move the indirect to direct call conversion to a distinct and greedy pass. Add a check inlining kernel pass to verify that calls to kernels are, in fact, inlined.
(Includes PR #326 as well.)
=> Fix #324: Update the old aggressive early inlining pass.

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Factory.h, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/NVQPP/if_jit.cpp, test/NVQPP/test-1.cpp, test/NVQPP/test-5.cpp
As we now allow plain old functions to be quantum kernels, we can no longer assume that an entry point kernel will have a this pointer. These changes will generate signatures for kernel entry points that do not assume that a this pointer must always be added.
This fixes (part of) #337 as well as other issues. #339
=> Fixes the handling of the this pointer.

include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, test/NVQPP/test-0.cpp
Update GenKernelExecution to output a new entry point function with any callable struct argument types emitted as pointers to the type, instead of just the type. Update QuakeSynthesizer to handle these struct types by incrementing the offset (ignoring them, since they have already been inlined). Turn the failing test on.
=> Callable Kernel Arguments Passed QuakeSynthesizer.

lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, test/NVQPP/sudoku_2x2-1.cpp
Especially with inlining, a loop's body may contain a non-trivial CFG. Allow that. Make unrolling greedy so that loops that contain loops will have the entire loop nest tree unrolled, if possible. Mark existing test as passing.
=> Fix #343: Allow unrolling to work on more loops.

include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/LowerToBaseProfileQIR.cpp, test/Quake-QIR/base_profile_verify.qke, tools/nvqpp/nvq++.in
This patch introduces a minimal base profile verification. It will catch cases where the JIT produces QIR base profile code that calls non-QIR functions.
See https://github.com/NVIDIA/cuda-quantum/issues#issuecomment-1621658944
=> Minimal verification of QIR base profile.

docs/CMakeLists.txt, docs/sphinx/examples/cpp/basics/mid_circuit_measurement.cpp, runtime/common/ExecutionContext.h, runtime/cudaq/CMakeLists.txt, runtime/cudaq/algorithms/sample.h, runtime/cudaq/cudaq.cpp, runtime/cudaq/platform/quantum_platform.h, runtime/cudaq/qis/execution_manager.cpp, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/qubit_qis.h, runtime/nvqir/CircuitSimulator.h, scripts/validate_container.sh, tools/nvqpp/nvq++.in, unittests/integration/builder_tester.cpp
Detect boolean casts of mid-circuit measurement results, update sampling strategy accordingly. Retain `bool` `mz` return type for AST Bridge and MLIR compilation mode.
=> Enable mid-circuit measurement detection in library mode.

runtime/cudaq/builder/kernel_builder.cpp, unittests/integration/builder_tester.cpp
Fix #332 by recursively finding all called functions and adding them to the current `ModuleOp` if not already present. Also do so for `kernel_builder::control/adjoint` while we're here.
=> Fix kernel_builder nested function call bug, #332

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/adjoint-4.cpp
Fix #338 
These patches bring cudaq::control and cudaq::adjoint to parity. Add test.
=> Fix #338: Work on implementation of cudaq::adjoint.

lib/Optimizer/CodeGen/LowerToQIR.cpp, test/Quake-QIR/allocaNoOperand.qke, test/Quake-QIR/base-profile-2.qke, test/Quake-QIR/basic.qke, test/Quake-QIR/measure.qke, test/Quake-QIR/testBaseProfile.qke
This implements the same fix as PR #377, but moves the creation of the names so as to avoid any race conditions in updating the Module.
See #377 for more information.
=> Alternative to PR #377

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Transforms/LowerUnwind.cpp, test/AST-Quake/control_flow.cpp, test/Quake/control_flow.qke
assumed simple high-level control flow graphs. That need not be true in the general case, particularly with inlining, and will not be true when more optimization work is done. See issue #14.
These changes add support for single-entry multiple-exit control op regions. It uses dominance information to identify any subsets that need to be accounted for in deallocation when exiting scopes. In most cases, the subsets x path-types are uniqued to exploit block sharing.
These changes also fix some bugs relating to lambda expressions.
Fix tests. Exit blocks are no longer merged.
Add a new test for unwind-lowering pass that leans into dominance relations between basic blocks.
=> Update unwind-lowering pass to be more general. The original pass

include/cudaq/Optimizer/Transforms/Passes.h, lib/Optimizer/Transforms/LoopUnroll.cpp, runtime/common/RuntimeMLIR.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config, tools/cudaq-opt/cudaq-opt.cpp
The sequence of steps to fully unroll loops (when possible) has become more elaborate. This introduces a named pass pipeline to consolidate and standardize this sequence of transformations.
=> Add a loop unrolling pipeline.

python/tests/compiler/adjoint.py, python/tests/compiler/call.py, python/tests/compiler/conditional.py, python/tests/compiler/control.py, python/tests/compiler/float.py, python/tests/compiler/list.py, python/tests/compiler/measure.py, python/tests/compiler/mixed_args.py, python/tests/compiler/multi_qubit.py, python/tests/compiler/multiple_floats.py, python/tests/compiler/no_input.py, python/tests/compiler/one_qubit.py, python/tests/compiler/qalloc.py, python/tests/compiler/qreg_apply.py, python/tests/compiler/swap.py, runtime/cudaq/builder/kernel_builder.cpp, unittests/integration/builder_tester.cpp
This should resolve https://github.com/NVIDIA/cuda-quantum/issues/378.
Mark the kernel's main function as an cudaq-entrypoint.
This is useful for the OpenQASM translator, which requires one function to be marked as an entrypoint.
=> Add "cudaq-entrypoint" attribute on to_quake

lib/Optimizer/Transforms/QuakeSynthesizer.cpp
The primary issue here is that not all uses of the compute_ptr op were being updated, so removing it wasn't working. A second issue was deleting the IR while looking at it. This left pointers in bad states and we segfaulted by dereferencing into garbage.
=> Fix bug 8 for release.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, test/Quake/roundtrip-ops.qke
This patch allows synthesis to create inline IR for a std::vector<double> of constants. After the loop unrolling pipeline has run (which is after synthesis), the abstract constant vector of doubles can be rewritten as simple scalars, which can be lowered to QIR and LLVM. The constant vector abstraction lets us escape the phase ordering issues of synthesis and loop unrolling.
=> Improve synthesis.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToBaseProfileQIR.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/QuakeObserveAnsatz.cpp, runtime/common/RuntimeMLIR.cpp
Add verify of base profile to explicit pipeline. This should be done as a pass pipeline so it doesn't get lost again.
Teach lowering to base profile about qubit array slices.
=> Fixes for slicing of std::vector.

lib/Optimizer/Transforms/QuakeAddMetadata.cpp, python/tests/compiler/conditional.py, runtime/cudaq/builder/kernel_builder.cpp
Take Quake code with `qubitMeasurementFeedback` when `if(mx(q))` or `if(my(q))` are encountered. Current implementation only considers `mz`.
=> Add mx/my checks to QuakeAddMetadata

tools/cudaq-quake/cudaq-quake.cpp, tools/nvqpp/nvq++.in
On clusters we'll often encounter multiple GCC installations. Add a way for cudaq-quake to take extra input arguments via an environment variable (specifically `--gcc-toolchain=/path/to/gcc/12`). 
Fix bug in nvq++ whereby symlinks are not followed in checking path equality.
=> Fixes for running on ppc64le architectures and HPC clusters 

.github/workflows/deployments.yml, .github/workflows/dev_environment.yml, .github/workflows/publishing.yml
This PR
- makes sure that build caches get populated based on the main cache when release branches are created
- makes sure a set of packages is deployed to GHCR when release branches are created
- allows to specify the cache base when manually triggering deployment
- adds the platform id to the cache id to ensure caches are not overwritten when building for a different platform
- makes sure the publishing is only triggered (manually or) by workflows that are run by the cuda-quantum bot
- ensures that all release assets are picked up for the final packaging
=> Various minor workflow fixes

include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/RefToVeqAlloc.cpp, runtime/common/RuntimeMLIR.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/NVQPP/bug_qubit.cpp, tools/cudaq-translate/cudaq-translate.cpp, unittests/Optimizer/QuakeSynthTester.cpp
Add a pass to convert quake allocations of qubit references to
allocations of vectors of size 1. This presents the conversion to QIR in
code gen with a uniform set of allocations.
=> Add promote single qubit pass

lib/Optimizer/CodeGen/LowerToQIR.cpp
Fix issue with multiple mz creating a register name targeting the same global string. 
```python
import cudaq
cudaq.set_target('quantinuum')
kernel = cudaq.make_kernel()
qubits = kernel.qalloc(2)
kernel.h(qubits[0])
kernel.cx(qubits[0], qubits[1])
kernel.mz(qubits[0])
kernel.mz(qubits[1])
print(kernel)
counts = cudaq.sample(kernel)
```
=> Fix #428, duplicate register names clashing in base profile

python/CMakeLists.txt
Remove need to run `make install` to use python bindings from the build directory.
=> Make python module available for testing in build directory

runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp
We weren't previously checking for a "failed" status from the IonQ jobs. This meant the terminal would hang indefinitely without informing the user of the error. 
Changes
* Throws a runtime error if the job has failed
=> Throw runtime error if job fails on IonQ's server

lib/Target/OpenQASM/TranslateToOpenQASM.cpp, runtime/cudaq/builder/kernel_builder.h
Also implement 
```cpp
std::ostream &operator<<(std::ostream &stream,
const kernel_builder_base &builder);
```
so users can write kernel_builders to ostream 
```cpp
std::cout << kernel << "\n";
```
=> Fix #379, cu1 -> u1 (bad copy-paste)

tools/nvqpp/nvq++.in
See issue 258. This is NOT a fix. It silences the error message.
=> Comment out the error message in the driver.

lib/Optimizer/CodeGen/LowerToBaseProfileQIR.cpp, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, runtime/common/CMakeLists.txt, runtime/common/RuntimeMLIR.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/NVQPP/test-int8_t_free_func.cpp, test/Quake-QIR/basic.qke, tools/cudaq-translate/cudaq-translate.cpp, unittests/Optimizer/QuakeSynthTester.cpp
QIR translation is buggy when there are multiple qubit allocations. Change the pipelines to use the qubit combine pass to move all allocations into a single vector allocation.
Also adds another checker to the base profile verifier to make sure that qubits are not misused in the base profile.
=> Fix QIR translation bug.

runtime/common/Future.cpp, test/NVQPP/test-6.cpp
also fix the `test-6.cpp` x operations on the right qubits to produce 1111, even though its currently marked XFAIL (and should be)
=> Better exception messages for cudaq::future

docs/sphinx/examples/cpp/algorithms/phase_estimation.cpp, include/cudaq/Optimizer/Transforms/Passes.h, lib/Optimizer/Transforms/LoopNormalize.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, test/AST-Quake/loop_normal.cpp
Simplify the fixed-point stuff, round 2.
Remove unsigned long constant from loops on int type. Not needed.
phase_estimation nirvana.
=> Fix bug with iterator in loop normalization.

runtime/cudaq/algorithms/optimizers/nlopt/nlopt.cpp
Catching exceptions from NLOpt and re-throw them with a more verbose message.
I think the most common one is the `roundoff_limited` error. It will occur when running in 'shots' mode, e.g., 
```
cudaq::observe(1000, deuteron_n3_ansatz{}, ...
```
in `docs/sphinx/examples/cpp/other/gradients.cpp`.
Might be related to https://github.com/NVIDIA/cuda-quantum/issues/399 (not fixing it, but could make the error message more helpful).
=> Catch NLOpt errors and rethrow with a verbose message

python/runtime/cudaq/kernels/py_chemistry.cpp, python/tests/domains/test_chemistry.py, runtime/cudaq/domains/chemistry/hwe.h, unittests/domains/ChemistryTester.cpp
The hardware efficient ansatz was extended to allow kernel builder calling.
Additionally the hwe.h was refactored a bit to reduce code duplication via free function for defaults and forwarding.
Tests in python were added.
=>  Added kernel_builder functions for the hardware efficient ansatz #361

include/cudaq/Optimizer/Transforms/Passes.h, lib/Optimizer/Transforms/LoopUnroll.cpp
This adds options that can be tweaked from the command line, etc. for the loop unrolling pass pipeline. Previously these settings were hardcoded into the compiler.
=> Add options to the loop unrolling pass pipeline.

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, test/Quake/modeless_effects.qke
Do not eliminate measurements and resets if their results are unused. These operations should be considered pinned in the IR.
=> Fix #475: bug with measurement operations in value semantics

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, test/Quake/nullwire.qke
The null_wire op differs from the classical value undef (or 0) in that it is not an SSA-value and not pure.
=> Fixes bug with null_wire.

.github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml, python/cudaq/_cudaq.cpp, python/tests/backends/test_IonQ.py, python/tests/backends/test_Quantinuum.py, python/tests/backends/test_Quantinuum_LocalEmulation.py, python/utils/TestingUtils.cpp, runtime/cudaq.h, runtime/cudaq/cudaq.cpp, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, runtime/nvqir/qpp/QppCircuitSimulator.cpp, unittests/integration/builder_tester.cpp
Fix bugs in those python backends tests. #303 
#26
=> Add cudaq::set_random_seed()

python/CMakeLists.txt, python/cudaq/_cudaq.cpp, python/runtime/cudaq/algorithms/py_sample.cpp, python/runtime/cudaq/domains/plugins/PySCFDriver.cpp, python/runtime/cudaq/target/py_runtime_target.cpp, python/runtime/cudaq/target/py_runtime_target.h, python/runtime/cudaq/target/py_testing_utils.cpp, python/runtime/cudaq/target/py_testing_utils.h, python/utils/CMakeLists.txt, python/utils/LinkedLibraryHolder.cpp, python/utils/LinkedLibraryHolder.h, runtime/cudaq/cudaq.cpp
This MR:
- Pulled `LinkedLibraryHolder` into a separate lib (`cudaq-py-utils`) to be used by both the `_pycudaq` and `cudaq-pyscf` libs.
- Made  `disallowTargetModification` a static member variable of `LinkedLibraryHolder`.
- Pulled the binding code in `utils/`  into `runtime/cudaq/target` sub-dir alongside other bindings.
Resolved https://github.com/NVIDIA/cuda-quantum/issues/416
=> Pulling `LinkedLibraryHolder` into a util lib

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp, docs/sphinx/install.rst, docs/sphinx/releases.rst, docs/sphinx/using/simulators.rst
Fixes the nvidia-mgpu target name and an example, adds a 0.4.0 section in versions, and adds a section on Python wheels to the install instructions.
=> Updating docs

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/examples/cpp/basics/cuquantum_backends.cpp, docs/sphinx/install.rst, docs/sphinx/releases.rst, docs/sphinx/using/simulators.rst
Cherry-picking #519 into main.
Fixes the nvidia-mgpu target name and an example, adds a 0.4.0 section in versions, and adds a section on Python wheels to the install instructions.
=> Updating docs (#519)

runtime/cudaq/platform/default/rest/helpers/quantinuum/QuantinuumServerHelper.cpp
This PR improves sanity checks for the Quantinuum's configuration file and fixes #524. It will throw exceptions if the file is ill-formed (not one `<key> : <value>` pair per line) and if one of the required keys is missing (API and refresh).
=> [rt] Fix #524: improve quantinuum's config file checks

python/tests/unittests/test_NoiseModel.py, python/tests/unittests/test_state.py, runtime/nvqir/CircuitSimulator.h, unittests/integration/noise_tester.cpp
=> Fix bug in bit flip noise channel

docs/sphinx/examples/cpp/providers/ionq.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config
Trying the IonQ simulator target, I saw that we didn't have an option to use the free hardware noise model simulation hence adding it in this PR.
- Add a CLI option (`--ionq-noise-model`) for users to set the noise model (ideal/aria-1/harmony).
- Send on to the job request JSON according to https://ionq.com/docs/get-started-with-hardware-noise-model-simulation
- Update the example to include instructions on how to use noise model simulation.
=> Add option to set the noise model when using the IonQ-hosted simulator

.github/workflows/integration_tests.yml
Adds ability to run the integrations tests in IONQ's backends. (Only works when the action is dispatched manually)
=> [gh] Run integration tests on IONQ's backends

include/cudaq/Support/Version.h, tools/cudaq-opt/cudaq-opt.cpp, tools/cudaq-quake/cudaq-quake.cpp, tools/cudaq-translate/cudaq-translate.cpp
Closes #532.
I added this massage to a `Support/Version.h` file because I think we need to implement a way for the tools to identify the compiler version, e.g., `cudaq-opt --version`. Since both the version and this massage should be shared for all tools, makes sense to have those things in one file. The PR leave the versioning report as a TODO, focusing only on closing the current issue. (I will open a new issue for the version flag)
=> [Support] Closes #532: change backtrace error message

.github/workflows/ci.yml, .github/workflows/deployments.yml, python/utils/LinkedLibraryHolder.cpp
**Root cause**: calling `dlclose`, during `LinkedLibraryHolder` destructor (shutdown), with `NULL` due to a previous failure of `dlopen`.
In this particular case, `libnvqir-custatevec-fp32.so`, though present in the wheel, cannot be loaded due to no `libcublas.so.11` in the ARM environment.
This is not ARM-specific but related generally to error-handling in `LinkedLibraryHolder`. e.g., those NVIDIA libs may also be corrupted due to users' actions (uninstall them...)
**Fixes:**
- Don't add the simulator backend if cannot load the corresponding .so lib.
- Add an additional `NULL` safeguard when using `dlclose`.
Tested locally by installing the wheel on a vanilla Ubuntu22.04 ARM VM and running CUDAQ python tests.
https://github.com/NVIDIA/cuda-quantum/issues/554
=> Fixed shutdown SEGFAULT in ARM build

unittests/integration/builder_tester.cpp
IIRC, `M_PI_4` is a POSIX standard while `M_PI_4f32` is a GNU extension not supported across the board.
=> Use `M_PI_4` instead of `M_PI_4f32`

python/runtime/cudaq/spin/py_matrix.cpp, python/runtime/cudaq/spin/py_spin_op.cpp, python/tests/unittests/test_SpinOperator.py, runtime/common/EigenSparse.h, runtime/cudaq/spin/spin_op.cpp, runtime/cudaq/spin_op.h, unittests/spin_op/SpinOpTester.cpp
Usage: 
```cpp
auto H = 5.907 - 2.1433 * x(0) * x(1) - 2.1433 * y(0) * y(1) + .21829 * z(0) -
6.125 * z(1);
auto [values, rows, cols] = H.to_sparse_matrix();
```
```python
hamiltonian = 5.907 - 2.1433 * spin.x(0) * spin.x(1) - 2.1433 * spin.y(
0) * spin.y(1) + .21829 * spin.z(0) - 6.125 * spin.z(1)
numQubits = hamiltonian.get_qubit_count()
values, rows, cols = hamiltonian.to_sparse_matrix()
scipyM = scipy.sparse.csr_array((values, (rows, cols)), shape=(2**numQubits,2**numQubits))
energy, _ = scipy.sparse.linalg.eigsh(scipyM, k=1, which='SA')
```
=> Implement spin_op::to_sparse_matrix().

docs/sphinx/api/languages/python_api.rst, python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/unittests/test_kernel_builder.py, runtime/cudaq/builder/CMakeLists.txt, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/QuakeValue.h, runtime/cudaq/builder/kernels.cpp, runtime/cudaq/builder/kernels.h, unittests/CMakeLists.txt, unittests/integration/kernels_tester.cpp
Enable kernel creation from a state vector. 
```python 
state = np.asarray([.70710678, 0., 0., 0.70710678])
kernel = cudaq.from_state(state)
counts = cudaq.sample(kernel)
```
```cpp
std::vector<std::complex<double>> state{.70710678, 0., 0., 0.70710678};
auto kernel = cudaq::from_state(state);
auto counts = cudaq::sample(*kernel);
```
=> Implement CUDA Quantum Kernel from State Vector.

.github/workflows/integration_tests.yml
Some nightly tests are not currently supported by the IonQ backend. Disable those currently failing tests for now.
=> Limit nightly integration tests to currently supported tests

runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp, utils/mock_qpu/ionq/__init__.py
This will enable more nightly integration tests to be enabled and pass.
=> Convert IonQ outputs to bit strings and correct order

lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Target/OpenQASM/TranslateToOpenQASM.cpp
@schweitzpgi please double check me on these. This is an attempted fix of #573. 
Also @boschmitt I'm attempting to enable adjoint operation lowering to OpenQASM here. 
This PR supports a demo the following demo I'd like to give:
```cpp
#include "cudaq.h"
// Demo Steps: 
// Show code: cudaq-quake demo/multicontrol_decomp.cpp | cudaq-opt --canonicalize 
// Synthesize ctrl kernels;   --apply-op-specialization 
// inline the functions:      --inline 
// Decompose multi-ctrl ops:  --quake-multicontrol-decomposition 
// Target a native gate set:  --quantinuum-gate-set-mapping --canonicalize 
// Canonicalize:              --canonicalize --factor-quantum-alloc
// See the code, the structure of the circuit
// Run the code, show how NVQ++ automates these things
//
// nvq++ --emulate --target …
```
=> Add some canonicalizations for ConcatOp and ExtractRefOp

runtime/cudaq/builder/kernels.cpp, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, unittests/integration/kernels_tester.cpp
Since we now have `cudaq::from_state`, which assumes MSB bit-ordering for its input, this PR makes `CuStateVecCircuitSimulator::getStateData` to return the state data in that bit ordering.
This will make it consistent with qpp as well as the `cudaq::from_state` convention.
Tested by:   running `test_runtime_custatevec-fp32`: `KernelsTester.checkFromState` test passed.
=> [custatevec] `getStateData` to return data consistent with qpp and `cudaq::from_state`

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, test/Quake/roundtrip-ops.qke
This adds a quake.sink and quake.from_ctrl. Rename quake.convert_ctrl to quake.to_ctrl. Changes to deploy these new ops will be in a forthcoming PR.
=> Add new ops to quake dialect.

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/examples/cpp/providers/quantinuum.cpp, docs/sphinx/specification/cudaq/platform.rst, include/cudaq/Optimizer/Transforms/Passes.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, python/tests/unittests/test_sample.py, runtime/common/Future.cpp, runtime/common/MeasureCounts.cpp, runtime/common/MeasureCounts.h, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp, runtime/cudaq/platform/default/rest/helpers/quantinuum/QuantinuumServerHelper.cpp, runtime/cudaq/platform/qpu.h, runtime/cudaq/platform/quantum_platform.cpp, runtime/cudaq/platform/quantum_platform.h, runtime/nvqir/CircuitSimulator.h, test/AST-Quake/loop_unroll-1.cpp, test/NVQPP/integration/sudoku_2x2-bit_names.cpp, test/NVQPP/integration/sudoku_2x2-reg_name.cpp, unittests/integration/builder_tester.cpp
This will resolve #579.
* Pass user-generated variable names into registerName attribute and count bits with a counter
* Form synthetic global register if one doesn't exist
* Change result handling in launchKernel output handling
* Log results messages in server helpers for debug
* Remove comments while parsing .config file
The main improvements are that it allows custom output names as demonstrated in sudoku_2x2-*.cpp. It also includes a synthetic global register if you want to get it the old way, but the synthetic global register is formed based off the alphabetical register names.
For example, 2 new tests were added to demonstrate the fix. when you compile and run the new test programs test/NVQPP/integration/sudoku_2x2-*.cpp, you will see the following results (as part of …
=> Allow more descriptive output names

lib/Frontend/nvqpp/ConvertExpr.cpp
An initializer-list may be 0 or more elements in length. The elements are pushed as values on the value stack of the bridge. Because a list of length 0 has no elements, the type is *explicitly* visited for an initializer-list. That visit must push exactly 1 type at traversal and pop that type at visitation.
This change adds the assertions to check the above invariants. It also tweaks the visit method to make sure the type is always consumed.
Add more comments to indicate what is going on.
TODO: the concrete Quake type for an initializer-list ought to be `!cc.array<T x c>` where `c` is a compile-time constant. At present the type travsersal is pushing just the element type: `T`.
=> More bridge work.

.github/workflows/ci.yml, .github/workflows/dev_environment.yml, .github/workflows/test_in_devenv.yml
This PR adds a step to the dev_environment.yml workflow that checks if the latest image on the GHCR registry match the layers needed for the build. If they do, it omits pushing them into the GH cache to reduce cache usage and instead uses the image from the registry in subsequent steps. This should address the issue that the cache upload occasionally failed due to hitting the 10GB/5min limit that GitHub sets, resulting in pipeline failures. Build times remain the same. We are still using the GH cache for the CUDA Quantum builds that are shared between different jobs of the python wheel validation and the docker image validation during CI. However, the dev dependencies make up most of the cache usage, such that relying on the cache should be fine for those.
=> Only create tar cache for dev dependencies when they are modified

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, lib/Optimizer/Transforms/LowerUnwind.cpp, test/AST-Quake/ctrl_vector.cpp
Copies and customizes the traversal code from RecursiveASTVisitor to make the traversal uniform. Since much of the code in the nested macros of the visitor cannot be overridden, we have to resort to copying. [Issue raised on discourse. https://tinyurl.com/m9wbr9jm]
The traversal changes make it possible to have predictable behavior with respect to the type and value stacks which allows assertions to be added to enforce that visiting a type does, in fact, add 1 type to the top of the stack.
Also add more support for the newer cudaq classes to the bridge.
=> Changes to harden the processing of VarDecls.

docs/sphinx/examples/cpp/algorithms/qaoa_maxcut.cpp, docs/sphinx/examples/cpp/algorithms/vqe_h2.cpp, docs/sphinx/examples/cpp/other/builder/qaoa_maxcut_builder.cpp, docs/sphinx/examples/cpp/other/builder/vqe_h2_builder.cpp, docs/sphinx/examples/python/advanced_vqe.py, docs/sphinx/examples/python/qaoa_maxcut.py, docs/sphinx/examples/python/simple_vqe.py, runtime/cudaq/spin/spin_op.cpp, runtime/cudaq/spin_op.h, runtime/cudaq/utils/cudaq_utils.cpp, runtime/cudaq/utils/cudaq_utils.h, runtime/nvqir/qpp/CMakeLists.txt, runtime/nvqir/qpp/QppCircuitSimulator.cpp, unittests/domains/ChemistryTester.cpp, unittests/integration/ghz_nisq_tester.cpp, unittests/integration/kernels_tester.cpp, unittests/mqpu/mqpu_tester.cpp
As described in Issue #608, many of our tests were not repeatable. This PR takes a significant first step towards addressing these issues, but some tests (like `GHZSampleTester.checkBroadcast`) are still not repeatable yet. The VQE and QAOA tests were some of the bigger offenders, and those are repeatable now.
Updates include:
[runtime] Wrap '#pragma omp' in appropriate #ifdefs 
* This PR does not disable OpenMP, but if one _were_ to disable it for testing, our build was failing. This fixes that.
[runtime] Modify omp reductions to get answer repeatability
* The variable order of operations in omp reductions will never be repeatable.
* This changes the expensive operations to occur in parallel, but the final sum is sequential.
* The final sum is not a significant runtime contributor, so …
=> Make runtime (and some tests) more repeatable

include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Pipelines.h, lib/Optimizer/CodeGen/TranslateToIQMJson.cpp, runtime/common/RuntimeMLIR.cpp, tools/cudaq-translate/cudaq-translate.cpp
These changes allow all the code gen backends to use a pass pipeline to fix up the code before the actual file is written. In the case of the bug, there was still Quake IR sitting in the Module that needed to be transformed before it could be emitted correctly.
=> Fix #627: Code gen for IQM Json failure.

unittests/backends/oqc/CMakeLists.txt, unittests/backends/oqc/OQCTester.cpp
This special test environment only applies when compiling with `-DCUDAQ_TEST_MOCK_SERVERS=TRUE`, which is not the default done by `build_cudaq.sh`.
This changes the answer checking to be done similar to how IonQ's answer checking is done.
=> Fix OQC mock server tests (special test environment)

.github/workflows/integration_tests.yml
This PR adds new OQC integration tests into the nightly integration test. See https://github.com/bmhowe23/cuda-quantum/actions/runs/6146329821 for an example run under my account.
I also took this opportunity to update the comments to specify the reasons that some specific tests are disabled (for both OQC and IQM).
Note: we need to hold off on merging the PR until we get the NVIDIA CI account established, but the reviews can begin now.
=> Add OQC nightly integration tests

include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, test/AST-Quake/control.cpp, test/AST-Quake/ctrl_vector.cpp, test/AST-Quake/lambda_instance.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/template_lambda.cpp, test/Quake-QIR/callable.qke, test/Quake/roundtrip-ops.qke
allow application to callables, such as lambda expressions.
Teach the bridge to lower lambda expressions to indirect apply calls when the lambda is not explicitly flagged with a `__qpu__` attribute but is an available lambda expression. (There is no reason not to allow this since the lambda expression is lowered by the bridge and readily available.)
Augment the cc.instantiate_callable operation to allow for wrapping plain old functions. Plain old functions are callable, but they do not have captures, do not need to create a closure, and do not need a thunk to unpack a closure. In short, they are a less complicated form. Supporting them now allows two flavors of CallableType. The original form, as constructed by lambda lifting, generates a pair of pointers consisting of a thunk function …
=> Modify Quake::ApplyOp to allow an indirect form of call in order to

test/NVQPP/testVersion.cpp, tools/cudaq-quake/cudaq-quake.cpp, tools/nvqpp/nvq++.in
#647 added the ability to report the cuda-quantum version, but it only works in conjunction with other command line arguments. This makes it work with a simple `nvq++ --version` command, as shown here:
```bash
[root@docker-desktop build (ch-version-rpt-improvements)]# nvq++ --version
nvq++ Version proto-0.5.0-developer
```
Whereas that simple command behaves like this in the main branch:
```bash
[root@docker-desktop build (main)]# nvq++ --version
ld.lld: error: undefined symbol: main
>>> referenced by /lib/x86_64-linux-gnu/Scrt1.o:(_start)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
failed: "/opt/llvm/bin/clang++ --ld-path=/opt/llvm/bin/ld.lld -Wl,-rpath,/usr/local/cudaq/lib -Wl,-rpath,/usr/local/cudaq/lib/plugins …
```
=> Make `nvq++ --version` work

.gitlab/workflows.yml
(1) Docker
Build Tensornet and MGMN SV cross-platform; package them into sims_amd64.zip and sims_aarch64.zip artifacts/assets to be uploaded to GitHub for the Docker image Packaging workflow.
Sample muti-platform docker build log: https://github.com/NVIDIA/cuda-quantum/actions/runs/6145961949/job/16675054084
```
#10 [linux/amd64 4/5] RUN for folder in `find "/opt/nvidia/cudaq/assets"/*$(uname -m)/* -maxdepth 0 -type d`;     do bash "/opt/nvidia/cudaq/bin/migrate_assets.sh" "$folder" && rm -rf "$folder"; done     && rm "/opt/nvidia/cudaq/bin/migrate_assets.sh"
#10 0.161 Migrating assets in /opt/nvidia/cudaq/assets/x86_64/mgmn_svsim.
#10 0.161 Using build configuration /opt/nvidia/cudaq/build_config.xml.
.....
```
```
#13 [linux/arm64 4/5] RUN for folder in `find …
```
=> Downstream cross-platform backend builds for HPC docker image and Python wheels

.github/workflows/docker_images.yml, include/cudaq/Support/CMakeLists.txt
priority over generating a value for the version.
When the tools are built by the CI, the bot sets a version number. This vresion number is defined in an environment variable and that variable is used in various places in the build.
On the other hand, not all builds are done by bots and the version may not be defined in that way. Therefore have a fallback path that will generate a version number based on the nearest tag from git to the commit (+ changes) being built.
=> Let the CUDA_QUANTUM_VERSION set as an environment variable have

.github/workflows/publishing.yml, CMakeLists.txt
We fixed the `-gencode` option to `sm_80` (Ampere/A100) while the `CuStateVecCircuitSimulator.cu` does have some CUDA kernels (e.g.,  `__global__ void initializeDeviceStateVector`). Hence, the generated binary is not compatible with the V100 GPU.
In this case, the `initializeDeviceStateVector` was not executed since the runtime couldn't find a compatible binary to run; hence the state vector was left uninitialized (all 0.0's).
Fixed by modifying the `-gencode` to support more architectures: same level of compatibility as the cuquantum library.
Should fix the issues reported in https://github.com/NVIDIA/cuda-quantum/issues/623; https://github.com/NVIDIA/cuda-quantum/issues/622; https://github.com/NVIDIA/cuda-quantum/issues/583
=> Support Volta+ arch in custatevec backend

Building.md
=> Update documentation to clarify LLVM version requirements

.devcontainer/devcontainer.json, docs/sphinx/api/languages/python_api.rst, docs/sphinx/install.rst, docs/sphinx/releases.rst, docs/sphinx/using/simulators.rst, pyproject.toml, python/README.md
=> Document CUDA library dependencies for python wheel

.github/workflows/deployments.yml, .github/workflows/docker_images.yml, .github/workflows/publishing.yml
So far we only ran publishing automatically when the deployment was also automatically launched by the cuda quantum bot. This was motivated by the fact that we run partial deployments (not launched by the bot) after merging PRs to update caches, which should not result in anything being published. I updated the publishing to be triggered also by partial deployments; it just won't do much in that case.
=> always run publishing after deployment

docs/sphinx/using/advanced/cudaq_ir.rst, include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/CodeGen/Pipelines.h, include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/LowerToQIRProfile.cpp, python/runtime/cudaq/target/py_testing_utils.cpp, python/runtime/cudaq/target/py_testing_utils.h, runtime/common/RuntimeMLIR.cpp, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.config, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.config, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.config, runtime/nvqir/NVQIR.cpp, test/Quake-QIR/basic.qke, test/Quake/lambda_variable-2.qke, tools/cudaq-opt/cudaq-opt.cpp, tools/cudaq-translate/cudaq-translate.cpp, utils/mock_qpu/ionq/__init__.py, utils/mock_qpu/oqc/__init__.py, utils/mock_qpu/quantinuum/__init__.py
The Adaptive Profile shares a large number of features with the Base Profile. These changes will enable us to add support for the Adaptive Profile with minimal code changes (in a forthcoming PR). Many of the Adaptive Profile changes have already been done, but I figured it would be best to break this up into multiple PR's to help the review process and testing process.
1. **Rename a bunch of code from "Base Profile" to "QIR Profile".** Justification: The Adaptive Profile is a superset of the Base Profile, so lowering to the Adaptive Profile is very similar to the Base Profile except we will just disable a few checks and add a few new functions. In many places where we used to say "base profile", I changed it to either say "QIR profile" or "specific profile". Most of these changes are in …
=> Refactor Base Profile code in preparation for Adaptive Profile

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/vector_front_back.cpp
=> Support vector front/back in bridge

docker/release/cudaq.Dockerfile, docs/sphinx/using/simulators.rst, python/README.md
Trying out the latest installation, the error that is given when CUDA dependencies are missing can be a bit cryptic. I hence mention it explicitly in the note about dependencies for the simulator backends.
Also, properly documenting the mgpu backend.
=> Clarifying how to invoke GPU-simulators from Python

.github/workflows/clean_up.yml, .github/workflows/docker_images.yml, .github/workflows/publishing.yml, docker/release/cudaq.Dockerfile, docker/release/cudaq.ext.Dockerfile, python/README.md
We use draft releases to exchange data between GitHub and GitLab. In principle, these draft releases are automatically cleaned up by the workflow. However, draft releases can get left behind when there is a bug or when updating the workflow. I hence added the input option to delete all draft releases in the clean-up workflow for convenience.
Works as it should: 
- https://github.com/NVIDIA/cuda-quantum/actions/runs/6393624866/job/17353240380
- https://github.com/NVIDIA/cuda-quantum/actions/runs/6405654128
=> Workflow to delete draft releases and clean up GHCR docker images and signatures

lib/Optimizer/Transforms/LowerUnwind.cpp, test/Quake/control_flow.qke
The algorithm was being too conservative with, e.g., break statements inside conditionals inside loops. These were causing a cascade that converted the nearest enclosing loop to be converted to a primitive CFG. That result is undesirable since we want to keep the high-level loop structure for later optimization passes. It is also unnecessary since cc.break and cc.continue statements can be used inside cc.loop so long as the body of the loop is a CFG.
=> Fix bug with unwind lowering.

lib/Optimizer/Transforms/LowerUnwind.cpp, test/AST-Quake/control_flow.cpp, test/Quake/control_flow.qke
Similar to the unwind lowering of cc.if ops, these changes allow a cc.scope to be lowered to a CFG without necessarily lowering the surrounding cc.loop to a CFG as well.
Update the tests to reflect the new reality.
=> Make unwind lowering of scopes less conservative.

.github/workflows/docker_images.yml, docker/release/cudaq.Dockerfile, python/cudaq/__init__.py
Fixes https://github.com/NVIDIA/cuda-quantum/issues/750 by not emitting the incorrect "cuquantum not found" message when not installed with pip.
Fixes the docs build issue. 
Fixes the issue that cudaq is not found when running a python program as sudo in our docker container.
=> Various small-ish fixes for docker images and build

lib/Optimizer/Transforms/MemToReg.cpp, lib/Optimizer/Transforms/RegToMem.cpp
Measurements now thread the wires as well as the bool result value in the value semantics. Each wire needs to be forwarded correctly.
=> Fix bug when rewriting measurement type ops.

lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/MemToReg.cpp, test/AST-Quake/to_qir.cpp, test/Quake/memtoreg-4.qke, tools/nvqpp/nvq++.in
The unwind lowering pass was being done somewhat late in the pipeline. The commit 2af197dbd7 moves it to be very early in the list of passes. The rationale is that the unwind_* operations model non-local transfers of control and make it easy for the bridge to lower to CC. However, their actual semantics is very hard to reason about in isolation as they depend on the surrounding context. Rewriting the IR to erase these Ops early will produce a simpler IR for the rest of the optimizer.
Commit adc4ef7929 does a remodel of the memtoreg pass. It reworks some data structures, refactors and renames code, and add more comments/documentation to, hopefully, make the code easier to understand. Along the way, it corrects a bug with CFGs embedded in high-level Ops.
The final commit, 813810e739, adds a …
=> Move unwind lowering to early in the pipeline and remodel memtoreg pass

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/LoopAnalysis.cpp, lib/Optimizer/Transforms/LoopAnalysis.h, lib/Optimizer/Transforms/LoopNormalize.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, test/NVQPP/phase_estimation.cpp, test/Quake/unroll_loop_with_break.qke
Add an option to the unrolling pass and unrolling pass pipeline to allow loops with `break` statements to be fully unrolled, so long as the loop is otherwise, structurally speaking, like a regular counted loop. Since the total number of executions is a variable, the option allows one to selectively enable/disable the unrolling of these variable iteration, constant upper bound loops.
=> Extend the cc-loop-unroll pass.

runtime/cudaq/platform/default/rest/helpers/oqc/OQCServerHelp.cpp
json null previously matched against c++ NULL 0. This allowed the future to terminate and fetch results before processing had finished.
=> Identify incomplete processing in OQC server helper

Developing.md, include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/AddDeallocs.cpp, test/AST-Quake/dealloc.cpp, test/Quake-QIR/alloca_no_operand.qke, test/Quake-QIR/base_profile-4.qke, test/Quake-QIR/basic.qke, test/Quake-QIR/exp-pauli-qir-1.qke, test/Quake-QIR/exp-pauli-qir-2.qke, test/Quake-QIR/exp-pauli-qir-3.qke, test/Quake-QIR/ghz.qke, test/Quake-QIR/measure.qke, test/Quake/test_add_dealloc.qke
It's all quake now. The dialect name isn't needed any longer.
=> Remove dialect name from pass option name.

test/Quake/compute_action.qke, tools/nvqpp/nvq++.in
- Remove the "quake" prefix from the driver script.
- Update comment that referred to retired option.
=> Minor cleanup.

lib/Optimizer/Transforms/BasisConversion.cpp
This allows legalization to pass in the basis conversion pass. The resulting code may not be executable on the final target, but the assumption is that the QIR profile validation pass will handle those cases.
=> Legalization error in basis conversion.

include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/ObserveAnsatz.cpp, runtime/cudaq/platform/default/rest/RemoteRESTQPU.cpp
- Rename QuakeObserveAnsatz to ObserveAnsatz
- Clean up the file to use MLIR coding style
- Convert GenerateKernelExecution and ObserveAnsatz to use the newer tablegen pass generators.
=> Pass name cleanup.

docs/sphinx/examples/python/tutorials/executing_circuits.ipynb, python/runtime/cudaq/builder/py_QuakeValue.cpp, python/tests/unittests/test_quake_value.py, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/QuakeValue.h, runtime/cudaq/builder/kernel_builder.cpp, unittests/integration/builder_tester.cpp
- Support division (resolved https://github.com/NVIDIA/cuda-quantum/issues/754)
- Fix bug in Quake `for_loop`: we missed a cast to index type when the start index is a `QuakeValue`.
- Also, fix first tutorial, showing the use of `expectation()` to retrieve the expectation result (dumping the result will show empty counts distribution since we don't do shots-based sampling).
=> Add more supports for `QuakeValue` in Python

lib/Optimizer/Transforms/MemToReg.cpp, test/Quake/memtoreg-5.qke
This refactoring splits up the "big loop" to reach the fixed-point into different sub-steps. These change will improve the performance of the algorithm overall. It also simplifies some of the bookkeeping being done to track IR updates on-the-fly.
The new sub-steps are:
1. Traverse every block in the region to produce live-in and live-out sets. This step threads stored values to load uses within each block.
2. If the parent has region arguments, convert promoted loads to region arguments if the memory reference is defined somewhere in parent. The promoted loads become input arguments.
3. Traverse all blocks and iterate to a fixed-point, threading values from terminators to arguments.
4. Rewrite the parent op to add values to region arguments (in any) and store the results appropriately. …
=> Refactor memtoreg.

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/LoopPeeling.cpp, test/Quake/loop_peeling.qke
This pass only implements a very resricted form of loop peeling. Specifically, a do-while loop is peeled and converted into a copy of the body of the do and a succeeding while loop.
The purpose of this transformation is to allow do-while loops to be converted to while loops. Once unrolling of general while loops is enabled, the compiler will be able to fully unroll a wider range of styles of loop statements.
=> Implement a loop peeling pass.

python/runtime/cudaq/algorithms/py_observe.cpp, python/runtime/cudaq/algorithms/py_sample.cpp, python/tests/parallel/test_mqpu.py, python/tests/unittests/test_state.py, runtime/cudaq/algorithms/state.h, runtime/cudaq/builder/kernel_builder.h, unittests/CMakeLists.txt, unittests/mqpu/mqpu_tester.cpp
Converting Python args to native data before passing it to the async sample functor. We've implemented it for `observe_async`, hence adopting it for `pySampleAsync`.
Addressed https://github.com/NVIDIA/cuda-quantum/issues/640.
=> Added missing GIL-safe implementation for `pySampleAsync`

python/runtime/cudaq/algorithms/py_observe.cpp, python/tests/unittests/test_observe.py
We infer the type of broadcasting in `args` vs. array of `args` and `spin_op` vs. array of `spin_op` when handling Python `observe`.
However, we didn't handle a combination of them. 
This PR:
- Allow Python `observe` to return a nested vector. Peel off the `spin_op` sum result to construct the nested result.
- Add a unit test case.
Resolved https://github.com/NVIDIA/cuda-quantum/issues/776
=> Support 2-d broadcast for observe

include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertType.cpp, test/AST-error/kernel_invalid_argument-1.cpp, test/AST-error/kernel_invalid_argument-2.cpp, test/AST-error/kernel_invalid_argument-3.cpp, test/AST-error/kernel_invalid_argument-4.cpp
Add a couple of tests that issue clang diagnostics about unsupported kernel argument types. This re-enables functionality that had been disabled.
=> Re-enable diagnostics for invalid kernel argument types.

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/cast.cpp
This adds `clang::CastKind::CK_FloatingToBoolean` to `QuakeBridgeVisitor::VisitImplicitCastExpr` in order to fix a compiler crash that could occur with code like this:
```cpp
double measure = mz(qubit);
if (measure)
someOtherCode();
```
I believe this implementation is consistent with https://en.cppreference.com/w/cpp/language/implicit_conversion#Boolean_conversions.
=> Fix compiler crash when casting from floating to boolean

python/tests/compiler/conditional.py, python/tests/parallel/test_mqpu.py, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/QuakeValue.h, unittests/integration/builder_tester.cpp
* Fixes an issue where qubits that are extracted in a `then` function were not getting a unique `extract_ref` if used outside of the conditional
* Adds new python and C++ tests to test for this bug
=> Fix kernel builder c_if qubit extraction bug

runtime/cudaq/platform/default/rest/helpers/ionq/IonQServerHelper.cpp, test/NVQPP/bug_qubit.cpp, test/NVQPP/callable_kernel_arg.cpp, test/NVQPP/cudaq_observe.cpp, test/NVQPP/if_jit.cpp, test/NVQPP/int8_t.cpp, test/NVQPP/int8_t_free_func.cpp, test/NVQPP/load_value.cpp, test/NVQPP/qir_if_base.cpp, test/NVQPP/qir_string_labels.cpp, test/NVQPP/qspan_slices.cpp, test/NVQPP/sudoku_2x2-1.cpp, test/NVQPP/sudoku_2x2-bit_names.cpp, test/NVQPP/sudoku_2x2-reg_name.cpp, test/NVQPP/sudoku_2x2.cpp, test/NVQPP/swap_gate.cpp, test/NVQPP/variable_size_qreg.cpp
[Last night's nightly integration test](https://github.com/NVIDIA/cuda-quantum/actions/runs/6740787337) had some issues. Some of them were caused by connection issues unrelated to our build (which have since been resolved), but some of them were true failures resulting from some of the mapping changes. This PR does the following to address those issues:
* Update some of our tests to properly name measurement results.
*  Mapping requires measurement names in order to keep the results interpretable by the end user. (It throws errors if it encounters unnamed measurements, and that's what caused some of the integration tests to fail.)
* Update RUN lines in tests to include more targets (to help prevent this from happening again)
* Related to this, also make IONQ_API_KEY env var not required …
=> [test] Fix failing integration tests

docs/sphinx/examples/python/tutorials/multi_gpu_workflows.ipynb, python/cudaq/__init__.py, python/cudaq/_query_gpu.py, python/runtime/cudaq/target/py_runtime_target.cpp, python/tests/unittests/test_qpp_target.py, python/utils/LinkedLibraryHolder.cpp, python/utils/LinkedLibraryHolder.h, runtime/cudaq/platform/default/nvidia-fp64.config, runtime/cudaq/platform/default/nvidia.config, runtime/cudaq/platform/mqpu/nvidia-mqpu-fp64.config, runtime/cudaq/platform/mqpu/nvidia-mqpu.config, runtime/nvqir/qpp/CMakeLists.txt, runtime/nvqir/qpp/density-matrix-cpu.config, runtime/nvqir/qpp/qpp-cpu.config, test/NVQPP/qpp_cpu_target.cpp, tools/nvqpp/backendConfig.cpp, tools/nvqpp/nvq++.in
* Default to GPU state-vector simulator when GPU is detected and to the CPU simulator otherwise.
* Refactored the check for GPUs into a common function.
Checklist:
=> Modifying default target to be GPU, if present

lib/Optimizer/Transforms/GenKernelExecution.cpp, test/NVQPP/auto_kernel.cpp
The root cause is ABI differences b/w ARM and x86 as explained [here](https://github.com/NVIDIA/cuda-quantum/issues/553#issuecomment-1800311727).
Hence, this PR adds the `sret` attribute to the first (hidden) argument if the entry point function is returning one and re-enables the `auto_kernel.cpp` test on ARM. 
Resolved: https://github.com/NVIDIA/cuda-quantum/issues/553
=> Add `sret` attribute for entry point function if needed

include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, runtime/nvqir/NVQIR.cpp, test/AST-Quake/control_flow.cpp, test/AST-Quake/if.cpp, test/AST-Quake/to_qir.cpp, test/Quake-QIR/veq_or_qubit_control_args.qke, unittests/backends/quantinuum/QuantinuumTester.cpp, unittests/integration/builder_tester.cpp
This PR fixes a bug in the C++ ASTBridge whereby `QuantumOp(qubit...), sizeof...(qubit) > 1` was treated as a controlled operation when it should be treated as a `QuantumOp` applied to all qubits in the variadic argument list. #875 
This PR also fixes the issues raised in #805 and #867, whereby control operations with multiple control operands of differing type (`veq` and `ref`) were not lowered to LLVM correctly.
=> Make C++ ASTBridge specification adherent for operation broadcasting 

docs/sphinx/examples/cpp/algorithms/bernstein_vazirani.cpp
This reduces the number of qubits used in the recently added `bernstein_vazirani.cpp` test from 32 to 28 in order to allow the CI to pass.
=> Fix publishing failures by reducing size of test

include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/RefToVeqAlloc.cpp
Moves the transformation pass, ref to veq, from the CodeGen directory to the Transforms directory. This puts it the same place as related passes like factor quantum alloc and combine quantum alloc.
=> [NFC] Move a transformation pass.

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/LinearCtrlRelations.cpp, lib/Optimizer/Transforms/LoopUnroll.cpp, lib/Optimizer/Transforms/PruneCtrlRelations.cpp, test/Quake/linear_control.qke
This pass converts the "value semantics" form of the quake dialect from the "pruned control relations" form to the "linear control relations" form. The pruned form is the less constrained IR representation while the latter is overly constrained. The following examples illustrate the distinction.
This is a sequence of ctrl-x ops in pruned form:
%10 = quake.to_ctrl %0 : (!quake.wire) -> !quake.control
%11 = quake.x [%10] %1 : (!quake.control, !quake.wire) -> !quake.wire
%12 = quake.x [%10] %2 : (!quake.control, !quake.wire) -> !quake.wire
%13 = quake.x [%10] %3 : (!quake.control, !quake.wire) -> !quake.wire
%14 = quake.x [%10] %4 : (!quake.control, !quake.wire) -> !quake.wire
%15 = quake.x [%10] %5 : (!quake.control, !quake.wire) -> !quake.wire
%16 = quake.x [%10] %6 : (!quake.control, …
=> Add new pass, linear-ctrl-form.

include/cudaq/Optimizer/CodeGen/Pipelines.h, include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/ApplyControlNegations.cpp, lib/Optimizer/Transforms/CMakeLists.txt
Our current strategy for handling negative controls is to inject X operations around the un-controlled version of the operation. This is currently handled in the lowering to LLVM and introduces a fair amount of logic that needs to be kept track of. This PR pulls that logic out into a separate pass and adds that pass to the QIR lowering pipeline.
=> Remove negative control handling from LowerToQIR to a standalone pass

docs/sphinx/install.rst, docs/sphinx/using/simulators.rst
* Code block updated to use tabs for C++ and Python for sake of consistency with the rest of documentation.
* Fixed the link from 'Next Steps' section to 'Default Simulator'.
Follow-up to [PR#899](https://github.com/NVIDIA/cuda-quantum/pull/899)
=> [Docs] Enhancement to the 'Defualt Simulator' section

.github/workflows/deployments.yml, .github/workflows/test_in_devenv.yml, docs/sphinx/using/cudaq/generic_functions.rst, docs/sphinx/using/cudaq/kernel.rst, docs/sphinx/using/cudaq/platform.rst
Specifically
- Fixing links in docs such that the link always point to the same version of the docs that someone is currently browsing
- Fixing a minor typo in the workflow when launching deployment manually
- Installing the iqm client for testing such that iqm server helper tests are not skipped.
=> Various minor fixes

lib/Optimizer/Transforms/LinearCtrlRelations.cpp, test/Quake/linear_control.qke
This fixes a bug in the newly added linear-ctrl-form pass. The index of the operand to be replaced was being miscomputed which was producing incorrect results. Corrects the test.
=> Fix bug in the linear-ctrl-form pass.

lib/Optimizer/CodeGen/LowerToQIR.cpp, runtime/nvqir/NVQIR.cpp, test/Quake-QIR/basic.qke, test/Quake-QIR/veq_or_qubit_control_args.qke
Extend and generalize the invoke* code.
Closes #806
=> Lower the ctrl-swap operations to QIR.

python/runtime/cudaq/builder/py_kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, unittests/integration/builder_tester.cpp
With (PR #[876](https://github.com/NVIDIA/cuda-quantum/commit/d83bdd24bedd3abcc46d44a65cacc31ea803d6c8)), we are now enforcing the use of `cudaq::ctrl` when a programmer intends to run a control gate. This behavior must be matched in the kernel builder to remain specification compliant.
As is, this deprecates the old functions with a stern warning, and replaces them with new templated versions. Depending on when this PR is merged, the deprecated functions should be removed for the following release cycle.
Note: this has no impact on the Python API, only the C++ kernel builder.
Old behavior that will now show a deprecation notice:
```
auto [kernel, value] = cudaq::make_kernel<float>();
std::vector<cudaq::QuakeValue> ctrls{kernel.qalloc(), kernel.qalloc()};
auto target = kernel.qalloc();
// …
```
=> Deprecate builder ctrl gates that are not specification compliant

runtime/cudaq/algorithms/observe.h, runtime/cudaq/algorithms/sample.h
These changes simplify some of the lambda expressions in the cudaq headers. It eliminates some of the more complicated capture expressions and uses simple reference capture. It also removes the `mutable` modifier which does not appear to be necessary in these cases.
=> Simplify lambda expressions.

python/tests/backends/test_IonQ.py, python/tests/backends/test_Quantinuum.py, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu
* Some Python backend tests fail by reporting `custatevec` errors when running on a machine with GPUs
- Set the target in test fixture that starts mock server 
-  Wrap the call to `cudaGetDevice` in CUDA error handler for early catching
Addresses https://github.com/NVIDIA/cuda-quantum/issues/977
=> Fix for Issue#977

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/MemToReg.cpp, test/NVQPP/cudaq_observe.cpp, test/Quake/basic.qke, test/Quake/roundtrip-ops.qke, test/Quake/wire_sink.qke, test/Transforms/mapping_unitaries.qke
These changes make !quake.wire a linear type and impose the "must be used exactly once" constraint in the IR.
Leaves work on cc.if as a TODO.
=> [quake] Introduce linear type constraints, part 1.

runtime/common/MeasureCounts.cpp, unittests/CMakeLists.txt, unittests/integration/measure_reset_tester.cpp
=> Fix bug in sampling a kernel with mz-reset-mz pattern (overwriting sample_result register)

.github/workflows/docker_images.yml
This change was included in https://github.com/NVIDIA/cuda-quantum/pull/832 to support GHA runners using rootless docker, but we don't plan anymore to use rootless docker so we can remove it.
=> Remove workaround for docker rootless

docs/sphinx/api/default_ops.rst
Clicking this link in question resolves to a page (so the CI's link checker though it was valid), but it was to a non-existent anchor, so the browser takes you to the top of the page rather than the desired anchor. This fixes that.
=> Trivial anchor link fix in docs

include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.h, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake-QIR/return_values.qke, test/Quake/lambda_variable-1.qke
Round out the implementation of kernels that return values in the IR and carry that through to LLVM code generation (QIR). This extends the support for scalar numeric return values to include aggregate types. It also fixes some bugs, particularly with dynamically sized aggregate return values.
The principle changes are to GenKernelExecution, which now uses the sret convention to return aggregate values. This actually simplifies the generation of the thunk code since the sret buffer is preallocated and can be passed by pointer rather than having the thunk copy return values itself.
Add a regression test for !cc.stdvec, !cc.struct, !cc.array, and multiple return values.
=> Kernels with return values.

CMakeLists.txt, runtime/cudaq/qis/qreg.h, runtime/cudaq/qis/qspan.h, test/AST-error/bad_sample_signature.cpp, test/AST-error/capture_list.cpp, test/AST-error/inaccessible_variable.cpp, test/AST-error/invalid_code.cpp, test/AST-error/invalid_kernel.cpp, test/AST-error/kernel_data_members.cpp, test/AST-error/kernel_invalid_argument-1.cpp, test/AST-error/kernel_invalid_argument-2.cpp, test/AST-error/kernel_invalid_argument-3.cpp, test/AST-error/kernel_invalid_argument-4.cpp, test/AST-error/multiple_methods.cpp, test/AST-error/negation_error.cpp, test/AST-error/quantum_types.cpp, test/AST-error/statements.cpp, test/AST-error/wall.cpp
Closes #75. Taking action on the old RFC.
=> Add deprecated attributes to qreg and qspan.

runtime/cudaq/builder/kernel_builder.h
The kernel builder still uses qreg, a deprecated type, which is generating a lot of warnings. This change silences the warnings. When qreg is finally removed, this change should be reverted.
See #75.
=> [NFC] Disable warnings from the kernel_builder.

test/NVQPP/custom_pass.cpp, tools/nvqpp/nvq++.in
Ability to pass custom pass plugins (as `.so` files) from `nvq++` to `cudaq-opt` and adding its passes to the pipeline.
Resolved https://github.com/NVIDIA/cuda-quantum/issues/969
=> Ability to pass custom passes from `nvq++`

lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake/vector.qke
This allows the IR to express vectors of vectors of ... recursively. Add a test for quake and for lowering to QIR. Bonus: Fix a bug in GKE.
=> Add vector<vector<...>> support to CC.

docs/sphinx/api/languages/python_api.rst, docs/sphinx/conf.py, lib/Optimizer/CodeGen/LowerToQIR.cpp, python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/compiler/ctrl_gates.py, python/tests/unittests/test_kernel_builder.py, python/tests/unittests/test_qpp_target.py, python/tests/utils/target_env_var_check.py, python/tests/utils/target_env_var_reset.py, runtime/cudaq/builder/kernel_builder.h, unittests/integration/builder_tester.cpp
Does the glue work for #918 to perform controlled SWAP's from the python and C++ builder.
* Adds new `cudaq::ctrl` overloads to the SWAP operation in the C++ builder
* New overloads support the following as controls: vector of individual qubits, qubit register, variadic arguments containing a mix of qubits/vecs
* Writes new C++ builder tests for these SWAP functions
* Binds the controlled SWAP gates to python as `cswap`
* New compiler and unit tests for the python controlled SWAP's
* Adds the python cswap gate to API documentation
Note: Ignore the random formatting changes to unrelated tests
=> Support controlled-SWAP's in kernel builder

docs/sphinx/snippets/cpp/using/cudaq/platform/get_state_async.cpp, docs/sphinx/snippets/cpp/using/cudaq/platform/sample_async.cpp
This test was accidentally broken by #1029 (relating to the deprecation of `qreg`). This change fixes the test by changing `qreg` to `qvector`.
=> Fix local GPU `nvqpp_SampleAsync` test by changing `qreg` to `qvector`

unittests/utils/UtilsTester.cpp
Fix error in nightly CI where warning was emitted from direct inclusion of a `fmtlib` header.
=> Fix direct include of fmt (suppress warnings)

.github/workflows/test_in_devenv.yml
There are issues with the freshly released iqm-client v15.1 (at least with respect to the cuda-quantum aspect of it). Until they are resolved, lock the CI to v15.0.
=> Update CI to use iqm-client v15.0 (not v15.1)

include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/NVQPP/kernel_exec.cpp, test/Quake/kernel_exec-1.qke, test/Quake/kernel_exec-2.qke, test/Quake/return_vector.qke, tools/nvqpp/nvq++.in
This is the initial implementation to support `vector<vector<...<T>>` arguments to kernels. It adds code to GenKernelExecution to perform the argument packing/unpacking into the message buffer.
Returning recursive vector data types is *NOT* supported.
- Implement the recursive unpacking of `vector<vector<...>>` in thunk.
- Implement packing `vector<vector<...>>` arguments.
- Refactor and share code with argsCreator.
- Add test.
- Fix regression tests.
As a bonus, this patch attempts to repair the `-g` option to `nvq++`.
=> Add end-to-end support for recursive vector arguments.

test/NVQPP/qpp_cpu_target.cpp, test/Target/IQM/z_gate.cpp, tools/nvqpp/nvq++.in
The nvq++ documentation says that it accepts command line arguments such as '--target=<value>', but does not correctly process them resulting in an error (as they pass through to clang).
This change attempts to fix this behavior.
=> [nvq++] Accept command line arguments specified as '--arg=value'

.github/workflows/config/spellcheck_config.yml, .github/workflows/config/spelling_allowlist.txt, include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, test/AST-Quake/struct.cpp
There is more to do here. Most notably the bridge doesn't support the ctors and other AST artifacts needed to build struct values, pass them around, etc.
Supports a POD struct if it is created by some external at this point.
=> Break ground on passing/return POD struct values.

lib/Frontend/nvqpp/ConvertStmt.cpp, test/AST-Quake/compute_action-3.cpp, test/AST-error/inaccessible_variable.cpp, test/AST-error/statements.cpp, test/AST-error/vector.cpp
This is a workaround added to the `for` loop handling. A more general solution in the bridge should be implemented.
=> Fix issue 1064: bug in bridge when lambda argument contains a loop.

python/runtime/cudaq/builder/py_kernel_builder.cpp, python/tests/unittests/test_kernel_builder.py, runtime/cudaq/builder/kernel_builder.h, unittests/integration/builder_tester.cpp
Currently, the Pauli word argument for `kernel_builder::exp_pauli` must be a string. Allow one to pass a single-term `spin_op`. 
Useful for use cases like in #1056
=> Enable use of single-term spin_op with kernel_builder::exp_pauli

runtime/cudaq/cudaq.cpp
There are a couple of static variables in `cudaq.cpp` that might be accessed concurrently.
For example:
- Thread 1 calls `deviceCodeHolderAdd` (`.thunk` function) => `vector::emplace_back`
- Thread 2 calls `get_quake_by_name` => iterate over the same `vector` => BANG.
This PR adds a `mutex` to guard access to those vars.
=> Improve thread-safety of CUDAQ static variables

.github/workflows/clean_up.yml, .github/workflows/config/ghcr_config.json, .github/workflows/deployments.yml, .github/workflows/documentation.yml, .github/workflows/gh_registry.yml, .github/workflows/prepare_deployment.yml
These changes make sure that feature branches get their own build caches.
Given the increasingly larger number of tags we create, I've also added a job once a day that keeps only a certain number of tags for images on GHCR (exact number is defined in the ghcr_config.json file): https://github.com/NVIDIA/cuda-quantum/actions/runs/7585004562
=> Workflow configs for feature branches

.github/workflows/config/spelling_allowlist.txt, runtime/cudaq/domains/chemistry/uccsd.h, unittests/domains/ChemistryTester.cpp
UCCSD bug fixes, implementation adapted from @marwafar 
Fixes #952
=> UCCSD Bug Fixes #952

CMakeLists.txt, python/tests/remote/test_remote_platform.py, runtime/cudaq/cudaq.cpp, runtime/cudaq/distributed/mpi_plugin.cpp, runtime/cudaq/distributed/mpi_plugin.h, runtime/cudaq/platform/default/rest_server/CMakeLists.txt, runtime/cudaq/platform/mqpu/helpers/MQPUUtils.cpp, tools/CMakeLists.txt
Try installing the wheel myself showed a bug: the qpud, as a tool, was missing from the wheel. 
Also fixed for wheels:
- Add `bin/` path to search for the qpud executable since we have no `PATH` to rely on.
- Gracefully check `dlopen` for MPI plugin. In Python wheel environment, there could be other deps missing if no mpi4py was install, e.g. libpython.
- Make sure the Python tests for `cudaq-mqpu` always run.
- Python `remote-mqpu` is now tested in the "Create Python wheels / Validate wheel" job.
=> Missing qpud in wheels

python/runtime/cudaq/algorithms/py_observe.cpp, python/runtime/cudaq/algorithms/py_sample.cpp, python/tests/parallel/test_mqpu.py
Race condition due to non-uniqueness of hash value for storage of opaque arguments in async multi-qpu scenario.
=> Fix bug 1108 - race condition in sample_async

include/cudaq/Optimizer/CodeGen/Pipelines.h, include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/CodeGen/LowerToQIR.cpp, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/default/DefaultExecutionManager.cpp, runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp, runtime/cudaq/qis/qudit.h, runtime/cudaq/qis/qvector.h, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, runtime/nvqir/qpp/QppCircuitSimulator.cpp, runtime/nvqir/qpp/QppDMCircuitSimulator.cpp, unittests/integration/builder_tester.cpp, unittests/qudit/simple_qudit/SimpleQuditExecutionManager.cpp
This moves the work in PR #1090 into this new feature branch. Work by others will build off of this. 
Things that still need to be done:
=> Add library mode and kernel_builder state allocation with initialization

include/cudaq/Optimizer/CodeGen/CMakeLists.txt, include/cudaq/Optimizer/CodeGen/CodeGenDialect.td, include/cudaq/Optimizer/CodeGen/CodeGenOps.td, include/cudaq/Optimizer/CodeGen/CodeGenTypes.td, include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/CodeGen/Pipelines.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/CodeGenDialect.cpp, lib/Optimizer/CodeGen/CodeGenDialect.h, lib/Optimizer/CodeGen/CodeGenOps.cpp, lib/Optimizer/CodeGen/CodeGenOps.h, lib/Optimizer/CodeGen/CodeGenTypes.cpp, lib/Optimizer/CodeGen/CodeGenTypes.h, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/CC/CCTypes.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/AddDeallocs.cpp, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, lib/Optimizer/Transforms/FactorQuantumAlloc.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/AST-Quake/qalloc_initialization.cpp, test/Quake/add_dealloc-1.qke
- Splits subgraph matching from the conversion pass. The conversion rewriter doesn't really let one do both at the same time given the way it traversing the IR.
- Add a new codegen dialect. Only used in codegen. Part of the previous bullet. The dialect will be the logical point to add any future combination ops.
- Removes the extra canonicalizer pass
=> Fixes for the lower to QIR pass.

docs/sphinx/examples/python/tutorials/cost_minimization.ipynb, docs/sphinx/examples/python/tutorials/executing_circuits.ipynb, docs/sphinx/using/advanced/cmake_app.rst, docs/sphinx/using/advanced/cudaq_ir.rst, docs/sphinx/using/advanced/mlir_pass.rst, docs/sphinx/using/advanced/nvqir_simulator.rst
=> copy edits made to Advanced topics and Tutorials

python/utils/LinkedLibraryHolder.cpp
If the user has GPUs but doesn't have all the right dependencies installed, we should not throw fatal exceptions in that case. Rather, we should fallback on qpp-cpu and log an `info` message that we are not selecting the `nvidia` target because dependencies are missing.
Helps mitigate the impact of missing dependencies as encountered in #1096.
Testing this in CI is difficult so I did standalone testing as follows:
First perform the following to force missing dependencies:
```bash
$ mv /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11 /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11.ignore
```
Without this change, it behaves as follows:
```bash
$ python3 -c "import cudaq"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```
=> Don't throw fatal exception during 'import cudaq' if missing dependencies

Developing.md
Changed the documentation to reflect the variable name that is in the macro, "#NAME" to "#PRINTED_NAME". Closes #959.
=> Edit to variable name in docs

.github/workflows/docker_images.yml, docker/build/cudaq.dev.Dockerfile, docker/release/cudaq.Dockerfile, docker/release/cudaq.ext.Dockerfile
I believe PR #1010 accidentally got rid of the build_info.txt file in our Docker images. This PR brings it back (or at least the `source-sha` portion of that file, which is used in the nightly integration tests [[logs to error](https://github.com/NVIDIA/cuda-quantum/actions/runs/7720616344/job/21045804379)]).
=> Restore build_info.txt in Docker images

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/LowerUnwind.cpp
These changes adjust the placement of quake.dealloc ops to account for the presence of state initializers in local scopes.
=> Add dealloc adjustments to the lower-unwind pass.

runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp, runtime/cudaq/platform/mqpu/MultiQPUPlatform.cpp, runtime/nvqir/cutensornet/tensornet_utils.h
(1) Clean shutdown behavior
- Client side: enforce cleanup order: qpus first then any auto-launch server instances. This prevents some stray errors during shut down. For example, the server process is shut down before the client, which causes the client to report an error (lost connection to the server) momentarily before it being destructed.
- Server app: make sure that we always have a loaded simulator in the runtime to prevent segfault during shutdown when the runtime would try to find one.
(2) Harden the `tensornet` scratch memory allocation against race condition.
Related to https://github.com/NVIDIA/cuda-quantum/issues/1136
=> Fixes for the `remote-mqpu` platform

test/AST-Quake/lambda_variable.cpp, test/AST-error/kernel_invalid_argument-2.cpp, test/AST-error/negation_error.cpp, test/NVQPP/custom_pass.cpp, test/NVQPP/mapping_test-1.cpp
Closes #1102.
- lambda_variable.cpp will never compile as C++17.
- Testing errors: one cannot expect identical error messages between different C++ standard settings.
- Syntax in these tests uses C++20 features and will produce warnings.
- As the runtime is compiled with C++20, a plugin pass compiled with C++17 may not behave correctly.
=> Triage tests

runtime/cudaq/matrix.h, runtime/cudaq/spin/matrix.cpp
This change fixes the following issue when address sanitization is enabled:
```bash
[ RUN      ] SpinOpTester.checkGetMatrix
=================================================================
==37123==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x606000002c60
#0 0x7fd52e01c3bd in operator delete(void*) /llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:152:3
#1 0x55e4351ca64a in std::default_delete<std::complex<double>>::operator()(std::complex<double>*) const /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95:2
#2 0x55e4351ca58b in std::unique_ptr<std::complex<double>, std::default_delete<std::complex<double>>>::~unique_ptr() /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:396:4
#3 …
```
=> Fix mismatch between new[] and delete

runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp
Minor clean up to the `BasicExecutionManager`:
* Remove unused headers
* Prefer the use of `std::vector` instead of `std::queue` and `std::stack`. (This simplifies the code and avoid the use of unnecessarily involved data structures.)
=> [rt] Minor clean up of `BasicExecutionManager`

docs/sphinx/api/languages/cpp_api.rst, runtime/common/CMakeLists.txt, runtime/common/ExecutionContext.h, runtime/common/Resources.cpp, runtime/common/Resources.h, runtime/common/Trace.cpp, runtime/common/Trace.h, runtime/cudaq/algorithms/resource_estimation.h, runtime/cudaq/qis/managers/BasicExecutionManager.h
The execution of a kernel in the `tracer` context will produce a `Trace` object: a netlist representation of the executed computation as seen by the execution manager. This object can then be used for analysis, e.g., `cudaq::estimate_resoruces` can compute number of operations or a circuit be drawn (this functionality will be added by a later PR).
With this `Trace` class, we can improve the `cudaq::Resource` one. However, that abstraction is leaky and would require braking changes that are out-of-scope for the present PR.
Depends on #1176
=> [rt] Add `Trace` class

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Fix issue where all dependent kernels were not added to MLIR ModuleOp
```python
@cudaq.kernel()
def func0(q : cudaq.qubit):
x(q)
@cudaq.kernel()
def func1(q: cudaq.qubit):
func0(q)
@cudaq.kernel
def func2(q: cudaq.qubit):
func1(q)
@cudaq.kernel()
def callMe():
q = cudaq.qubit()
func2(q)
```
@marwafar
=> [experimental/python] Build kernel call graph and add all dependent kernels

python/cudaq/kernel/analysis.py, python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Make sure `cudaq.kernel()` is not found as a kernel dependency. Clear the MLIR value stack upon exit from the AST bridge visitor.
=> [experimental/python] Fix issue with finding kernel dependencies 

include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/LowerToQIRProfile.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp, runtime/cudaq/platform/mqpu/nvcf.config, tools/cudaq-qpud/RestServerMain.cpp
- `nvcf.config` to disable library mode + sanity check within the client to verify that.
- Add a subclass for server implementation to do server-side filtering for MLIR (lowered to QIR).
- Add a verification for `CallOp`: either QIR functions or NVQIR-known functions as defined in `QIRFunctionNames.h`
 
- Add a missing MLIR pass in the config.
=> Ability to run qpud in QIR-only mode with `CallOp` verification

python/runtime/cudaq/algorithms/py_observe.cpp, python/runtime/cudaq/algorithms/py_sample.cpp, python/runtime/cudaq/algorithms/py_state.cpp, runtime/cudaq/builder/kernel_builder.cpp
This PR introduces 2 optimizations:
1. This changes the JIT cache key calculation from `std::hash<std::string>{}(modulePrintOut)` to one using `llvm::hash_code`. In my timing tests, the latter is ~27-29x faster than the former. (The generation of the `modulePrintOut` was the slow part, not the `std::hash`.)
2. Additionally, this eliminates redundant calls to `kernel_builder::jitCode()` when it is subsequently followed up with calls to `kernel_builder::jitAndInvoke()`. With the JIT cache key calculation change (above), this change is less important, but the redundant calls should not be needed, and are hence removed anyway.
Under some VQE test code, the combination of these two optimizations reduces the overall simulation runtime by ~50%, but YMMV.
=> Kernel builder JIT cache optimizations

CMakeLists.txt, runtime/cudaq/platform/CMakeLists.txt, runtime/cudaq/platform/default/CMakeLists.txt, runtime/cudaq/platform/mqpu/CMakeLists.txt, tools/CMakeLists.txt
Under some circumstances, it may be expediant to disable the building of the REST and REST Server libraries in the runtime. This adds a cmake variable, CUDAQ_ENABLE_REST, for exactly that purpose.
=> Add a cmake variable to disable building the REST parts of the runtime.

.github/workflows/config/spelling_allowlist.txt, docs/sphinx/examples/python/providers/oqc.py, docs/sphinx/using/hardware.rst, runtime/cudaq/platform/default/rest/helpers/oqc/CMakeLists.txt, runtime/cudaq/platform/default/rest/helpers/oqc/OQCServerHelp.cpp, runtime/cudaq/platform/default/rest/helpers/oqc/lucy.txt, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.config, runtime/cudaq/platform/default/rest/helpers/oqc/toshiko.txt
The current rest helper defaults to the OQC 8 qubit Lucy device. We now want to support 2 devices on the platform including the 32Q Toshiko coaxmon based super conducting qpu.
=> Options for OQC Toshiko machine

pyproject.toml
`numpy` is required by modules like `python/cudaq/kernel/ast_bridge.py` and `python/cudaq/kernel/quake_value.py`
While installing wheel on Python v3.8 we get `ERROR: No matching distribution found for numpy~=1.26`
=> [experimental/python] Fix for deployment on Python v3.8

.github/workflows/test_in_devenv.yml, docs/sphinx/install.rst, python/cudaq/__init__.py, python/cudaq/dbg/__init__.py, python/cudaq/dbg/ast.py, python/cudaq/kernel/analysis.py, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_decorator.py, python/tests/kernel/test_kernel_features.py, python/tests/kernel/test_observe_kernel.py, python/tests/kernel/test_sample_kernel.py
Fixed a bug in incrementing ranges like the following
```python
for i in range(0, 4, 2):
...
```
Setup error diagnostics for AST compilation to MLIR. 
New error diagnostics for invalid code. Just a few examples to get an idea for what it looks like
```python 
@cudaq.kernel()
def ex0():
l = [] # can't create an empty list 
```
```bash
cudaq.kernel.ast_bridge.CompilerError: tmp.py:11: error: CUDA Quantum does not support allocating lists of zero size (no dynamic memory allocation)
(offending source -> l = [])
```
```python
@cudaq.kernel
def test(i : int, f:float):
cudaq.dbg.ast.print_i64(i)
q = cudaq.qvector(2)
ry(f, q[f]) # qubit extraction with a float instead of int
```
```bash
cudaq.kernel.ast_bridge.CompilerError: tmp.py:11: error: invalid index variable type used for qvector …
```
=> Python Error Diagnostics. Bug fix for incrementing range generation

.github/workflows/integration_tests.yml
Default values from the `workflow_dispatch` section of the workflow are not inherited by the scheduled runs. Fix tests to keep the defaults in sync, and add maintenance comments.
=> Fix default values for scheduled nighly integration tests

python/runtime/cudaq/platform/py_alt_launch_kernel.cpp
The experimental/python branch has an additional JIT point. Apply the same optimization from #1261 to that spot.
=> Optimize LLVM JIT for large circuits: apply #1261 to experimental/python

docker/release/cudaq.nvqc.Dockerfile, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp
- NVCF server subclass to initiate an exit (internal event loop) after serving each job request.
- Launch script (entry point) to loop the daemon service as it exits.
- Also, fixed some innocuous logs when doing IR validation.
=> NVCF REST server to operate in per-request process context

python/cudaq/__init__.py, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/kernel_decorator.py, python/runtime/cudaq/algorithms/py_observe_async.cpp, python/runtime/cudaq/algorithms/py_sample_async.cpp, python/runtime/cudaq/algorithms/py_state.cpp, python/runtime/cudaq/algorithms/py_vqe.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_ir_operations.py, python/tests/kernel/test_kernel_features.py
We really need to change when / where the actual AST-to-MLIR JIT happens. As of right now all library kernels are JIT compiled when they are imported - and this occurs even if they are not necessarily needed. For example, the UCCSD compilation time takes ~.9 seconds on my machine, and this occurs every time `import cudaq` is called. It would be better if the kernels JIT compiled when they were called. 
This PR updates the `PyKernelDecorator` class to do AST-to-MLIR JIT when the kernel is invoked.
=> Move AST-to-MLIR compilation to the call operator.

.github/workflows/integration_tests.yml
GitHub actions won't allow `env` usage outside of `steps` contexts. This resolves that.
I have tested it on my personal account ([here ](https://github.com/bmhowe23/cuda-quantum/actions/runs/8039342190)on a schedule and [here](https://github.com/bmhowe23/cuda-quantum/actions/runs/8039132150) on `workflow_dispatch`), but I do not have the NVQC secrets for this endpoint under my account, so I cannot fully test everything until it is merged.
=> Follow-up to #1288 - fix integration test env usage

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/kernel_decorator.py, python/cudaq/kernel/utils.py, python/tests/kernel/test_kernel_features.py
Also disallow capture variables 
```python 
n = 5 
@cudaq.kernel
def test():
q = cudaq.qvector(n)
test()
```
```bash
cudaq.kernel.ast_bridge.CompilerError: z.py:9: error: Invalid variable requested - `n` was defined in the kernel's parent scope. CUDA Quantum does not support capturing variables from parent scope (variables must be defined as input arguments or within the kernel function body).
(offending source -> n)
```
=> Implement improved error diagnostics for kernel_decorator and kernel_builder

docker/release/cudaq.nvqc.Dockerfile, scripts/nvqc_proxy.py
Make a reverse proxy for NVCF that is always up, so that `cudaq-qpud` cycles do not affect NVCF communications.
=> Add reverse proxy for NVQC

.github/workflows/integration_tests.yml
GitHub was converting the `3.10` to `3.1`, which was causing the Python tests to fail when running in the "scheduled" (i.e. nightly) workflow. Fix that here. Also clean up some spacing/formatting issues.
I cannot run the full test from my personal account, but I *did* test what I could [here](https://github.com/bmhowe23/cuda-quantum/actions/runs/8084617572/job/22090516856). The main thing I was looking for was correctly shown here (under the "Install wheel" section):
```
Run python_version=3.10
python_version=3.10
```
=> [test] Fix python version string for scheduled nightly tests

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_decorator.py, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_kernel_features.py
Capture `int`, `float`, `bool`, or `list[int|float|bool]` from parent scope. Track potential variable changes and update the MLIR code accordingly. 
```python
n = 5
@cudaq.kernel
def kernel():
q = cudaq.qvector(n)
x(q)
counts = cudaq.sample(kernel)
assert '1' * n in counts
n = 7
counts = cudaq.sample(kernel)
assert '1' * n in counts
```
=> Implement proper Pythonic capture of variables from parent scope

runtime/common/BaseRemoteSimulatorQPU.h
Publishing validation failed for `mid_circuit_measurement.cpp`: https://github.com/NVIDIA/cuda-quantum/actions/runs/8102260968/job/22146719182
We've probably missed a couple of changes when refactoring `RemoteSimulatorQPU`  -> `BaseRemoteSimulatorQPU`.
Perhaps, these changes went into main's `RemoteSimulatorQPU` after the refactoring and have not been copied over to  `BaseRemoteSimulatorQPU`.
Tested by: running this `mid_circuit_measurement.cpp` locally after the fix for both `remote-mqpu` and `nvqc`.
=> Fixed a fallout from the recent merge

python/tests/remote/test_remote_platform.py, runtime/common/BaseRemoteSimulatorQPU.h, runtime/common/BaseRestRemoteClient.h, runtime/common/RemoteKernelExecutor.h, runtime/cudaq/cudaq.cpp, runtime/cudaq/platform/mqpu/CMakeLists.txt, runtime/cudaq/platform/qpu.h, runtime/cudaq/platform/quantum_platform.cpp, runtime/cudaq/platform/quantum_platform.h
Currently, when sending REST requests to a remote QPUD, the seed value is set to `cudaq::get_random_seed()`, hence all kernel executions will be using the same seed value. This deviates from the local execution model, whereby the static random number generator in the simulator is seeded **once** when `set_random_seed` is called. 
This PR fixed that difference by letting the client to seed the server using a random number generator seeded by `cudaq` seed value.
Note: in general, we don't expect an absolute seed value to have the same effect between local execution and remote execution. Hence, we can randomly generate the server seed using a random sequence seeded by the `cudaq` seed.
=> Refresh remote seeds for executions within a client session

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernels/uccsd.py, python/tests/domains/test_chemistry.py
In the following code we have subscripting into existing lists, which returns a `cc.ptr` type. At runtime this translates into a garbage integer being added to the `doubles_a[counter]` list. This PR instead checks the list elements being added and if one is a `cc.ptr` then we call `cc.LoadOp` first. 
```python
doubles_a[counter] = [occupied_alpha_indices[p],occupied_alpha_indices[q],\
virtual_alpha_indices[r],virtual_alpha_indices[s]]
```
Also, fixing an oversight in the number of UCCSD parameters function.
=> Fix issue where list creation would not load pointers before adding them to the list

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Previously, captured variables were treated as constant MLIR values created in whatever scope they were first used. This means they cannot be used in other function scopes and they can't be set / changed (though they are still captured by value). This PR fixes this by elevating capture variables to stack variables at the start of the kernel entry block.
=> Elevate capture vars to stack slot at function entry block start

lib/Optimizer/Transforms/GenDeviceCodeLoader.cpp, runtime/common/BaseRestRemoteClient.h
- Fixed the issue with duplicate function def in the IR when a function is included multiple times. 
- Handled `FuncOp` without explicit kernel attribute by checking the function name.
Tested by: running all Python MLIR tests in `python/tests/mlir/target` with NVQC (to be included in the nightly integration CI along with other examples).
=> [NVQC] Fixes for Python MLIR tests

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Throw a compile-time error if someone tries to assign to a variable captured from parent scope.
=> Disallow assignment to captured variables

python/runtime/cudaq/algorithms/py_draw.cpp, python/tests/kernel/test_kernel_features.py
Description:
> We should throw a better error in cudaq.draw() if someone forgets to pass along the kernel arguments. Right now, it just returns a segfault without explanation.
=> Runtime error if kernel arguments missing / incorrect when invoking   'draw'

tools/nvqpp/nvq++.in
`llvm-config` is not in our deployed cuda-quantum image, so this change works around that by using `llc` to determine the default host target instead of `llvm-config`.
I manually copied the `nvq++` file into a fresh `cuda-quantum:latest` image to verify this change works.
=> Follow-up to #1340 because llvm-config is not in cuda-quantum image

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
- Retrieve timeout info from NVQC deployment (container environment variables).
- Log timeout limit alongside the NVQC info line.
- Warn users when timeout is approaching (less than 5 min remained).
=> [NVQC] Add logging info for timeout 

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
When container environments are not visible, function name is the only mechanism to encode deployment configurations.
Proposed naming convention: `cuda_quantum_v1_t3600_8x` (encode API version, timeout in secs, and the number of GPUs).
Implement a regex match procedure to parse these configs from the name. It will take precedence over container environment variables.
=> Ability to decode deployment configs from function names

lib/Optimizer/Transforms/QuakeSynthesizer.cpp, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h, unittests/Optimizer/QuakeSynthTester.cpp
to the synthesizer.
Add test for vector<int64_t>.
Fix some bugs.
Implement folding of size() calls on vector inputs in synthesis. Allow vectors that are longer than what is required.
**Release**
These changes enable code that was failing on nvqc.
=> Add support for vector<int64_t>, vector<int32_t>, and vector<float>

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
This change is a follow-up to #1353.
* It displays a new dot (`.`) every 5-6 seconds while the job is in execution.
* If your job has to wait in a queue, it shows updates any time your position in the queue changes.
-------------------
Here is sample of what it looks like for a ~40 second job (using default log levels). The `.`'s come out every 5-6 seconds if the job is not completed within the first 5-6 seconds.
```bash
$ python3 ../docs/sphinx/examples/python/providers/nvqc_sample.py
[2024-03-08 16:17:42.239] Submitting jobs to NVQC service with 1 GPU(s). Max execution time: 3600 seconds (excluding queue wait time).
......
================ NVQC Device Info ================
GPU Device Name: "NVIDIA H100 80GB HBM3"
CUDA Driver Version / Runtime Version: 12.2 / 11.8
Total global memory …
```
=> Adjust NVQC client logs to show queue position and dots by default

python/tests/builder/test_SpinOperator.py, python/tests/remote/test_remote_platform.py, runtime/cudaq/spin/spin_op.cpp
This fixes a bug in formulas used when deserializing a spin op from a vector. The new test in the PR fails without the code change and passes with the accompanying code change.
I confirmed that this error was only happening when there was exactly 1 term in the spin op.
=> Fix spin-op deserialization bug when there is exactly 1 term

python/tests/builder/test_SpinOperator.py, python/tests/remote/test_remote_platform.py
Fix deployment failure with Python 3.8 (test only, not operational code): https://github.com/NVIDIA/cuda-quantum/actions/runs/8210300739/job/22457834545
(Python 3.8 doesn't have `list`; it's not truly needed for the new test, so simply eliminate it.)
=> Follow-up to #1363 - Fix test for Python 3.8 compatibility

python/runtime/utils/PyRestRemoteClient.cpp, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteClient.cpp
This PR fixes an oversight in checking whether we need to upload the request as an asset: need to use the full JSON string size rather than only the main IR payload.
=> Use actual json string size to compare against NVCF message size limit

include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/GenDeviceCodeLoader.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, runtime/common/BaseRemoteRESTQPU.h, runtime/common/BaseRestRemoteClient.h, targettests/execution/device_code_loaded.cpp, targettests/execution/lambda_introspection.cpp, targettests/execution/template_introspection.cpp
Need to use LLVM's understanding of how the struct of arguments is laid out in memory in order to recover the values that the synthesizer will use to instantiate a circuit from a kernel.
Fix #1367
=> Fix issue #1367

python/README.md
Anaconda doesn't have linux-aarch64 packages for Python 3.8.0 and 3.9.0, so without this change, these instructions will fail on ARM. However, when switching to a single "=", conda will allow the user to specify a version up to the number of digits provided, and then use the latest version available after that. For example, if the user provides "3.8", then conda will choose "3.8.18", which is the largest patch version matching "3.8".
=> Remove exact version specifier in Python install instructions

runtime/cudaq/algorithms/sample.h
In library mode, we need to run a tracing pass before actual execution. 
With multi-qpu, we `set_exec_ctx` on specific QPU id but didn't reset the context on that particular qpu id (fall back to reset QPU 0 context all the time).
Resolves #1374
=> Fix a bug in `sample.h` affecting `sample_async` in library mode

python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/utils.py, python/tests/builder/test_kernel_builder.py
We now require argument annotations with the Python language kernels, and lists must have element type specified (e.g. `list[float]` instead of just `list`). 
Users likely will try to specify list element types with the kernel builder as well, but this currently emits an error 
```python
import cudaq 
kernel, thetas = cudaq.make_kernel(list[float])
print(kernel)
```
```bash
RuntimeError: error: Can not handle conversion of python type list[float] to MLIR type.
Offending code:
File "/workspaces/cuda-quantum/builds/gcc-12-debug/test.py", line 3, in <module>
kernel, thetas = cudaq.make_kernel(list[float])
```
This PR fixes this by enabling element type inference for kernel builder list arguments.
=> Fix bug - enable list[T] argument specification with kernel builder

scripts/nvqc_proxy.py
The NVCF infrastructure team has requested that health endpoint requests (i.e. requests to our `/` endpoint) be served in a separate thread from the inference endpoint (i.e. `/job`) so that inference requests won't block health endpoint checks. This PR satisfies that request.
Regression testing was performed by pushing a new image with these changes into our NVCF organization.
In addition to asking the NVCF team to review their logs about health endpoint requests for these new deployments, I have performed the following stress tests:
1. Deploy multiple instances of our 1-GPU configuration and saturate it with multiple parallel requests.
```bash
$ bin/nvq++ --target nvqc ../examples/cpp/providers/nvqc_sample.cpp
$ for j in `seq 1 10`; do echo "*** j = $j ***"; for i in `seq 1 10`; do …
```
=> Make nvqc_proxy.py multi-threaded

lib/Optimizer/Transforms/QuakeSynthesizer.cpp
The constant array op is using at ArrayAttr, which does not naturally support integral sizes less than i32. This patch upcasts the short values to i32 to get around the issue. Another approach would be to have the constant array op take a DenseArrayAttr, which does support the shorter integral types. Might need a custom parser/pretty printer if we go that route?
Fix #1384
=> Fix #1384 - synthesis of vectors with small integers.

lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp
The operator[] returns a reference, but the AST doesn't have a cast node. So the value appearing in the conditional is not loaded. This adds an explicit check and an error message if the load is returning an unexpected value.
Fix #1383.
=> Fix #1383: bridge not lowering to correct IR

lib/Optimizer/Transforms/QuakeSynthesizer.cpp
Change the catch-all for structs to NOT raise an error for callables and empty structs (which are more than likely callable classes).
Fix #1392
=> Fix #1392: "synthesis" of callables

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp
We can't use it yet since we're lagging LLVM, but this greases the skids to make folding of invalid constant array accesses to poison values.
=> [Core] Add poison op and fold optimization

python/tests/kernel/test_sample_kernel.py, python/tests/mlir/ast_elif.py, python/tests/mlir/ast_for_stdvec.py, scripts/build_cudaq.sh, scripts/build_llvm.sh
* (Re-)Enable 'pycudaq-mlir' tests which have been fixed by PR# https://github.com/NVIDIA/cuda-quantum/pull/1406(https://github.com/NVIDIA/cuda-quantum/pull/1406)
* Update comment in scripts to reflect allowed build type ('Debug', not 'DEBUG')
- Using 'DEBUG' results in error `Invalid build type` 
* Removed the comment about issue# https://github.com/NVIDIA/cuda-quantum/issues/1046
=> Re-enable skipped tests and update script usage comment.

python/tests/builder/test_SpinOperator.py, runtime/cudaq/spin/spin_op.cpp, unittests/spin_op/SpinOpTester.cpp
=> Make spin_op.distribute_terms batch more efficiently

python/tests/builder/test_observe.py, runtime/common/ObserveResult.h
We have the logic to expand the term strings (used as index keys) for result look-up but it was limited to single-qubit cases (e.g., only expanding Z0 but not Z1 to the target number of qubits).
This caused the issue reported in #1396 whereby the second `spin_op` in that list is Z1. It wasn't expanded properly, hence reported as a zero result.
This PR fixed the issue and added a test based on the bug report.
Resolved #1396
=> Fix issue with `spin_op` result retrieval

pyproject.toml
Our Python wheel builds seem to be broken (e.g. [this example](https://github.com/NVIDIA/cuda-quantum/actions/runs/8434834595/job/23101378620)), and it seems to be related to the recent release of [CMake 3.29](https://github.com/Kitware/CMake/releases/tag/v3.29.0).
This is a quick fix to get our wheels building again, but we should additionally try to figure out why the build process doesn't work with the new version and fix that separately.
=> Prevent usage of cmake 3.29.0 in Python wheel

python/cudaq/kernel/kernel_decorator.py, python/runtime/cudaq/algorithms/py_draw.cpp, python/runtime/cudaq/algorithms/py_observe_async.cpp, python/runtime/cudaq/algorithms/py_sample_async.cpp, python/runtime/cudaq/algorithms/py_state.cpp, python/runtime/cudaq/algorithms/py_vqe.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_kernel_features.py, python/utils/OpaqueArguments.h
Inject the kernel `FuncOp` when packing input runtime arguments into the opaque arg used by `altLaunchKernel`. This provides better handling of runtime argument types via the LLVM TypeSwitch utility.
Without this we should experience issues with regards to processing empty lists passed as runtime arguments. Currently we can only know that the argument is a `list` and infer the element type by checking the type of the list's first element, which does not exist if the list is empty. This PR brings the kernel argument signature to this processing step, and so we can check / process the args knowing the required argument type.
=> Improved type handling for OpaqueArguments::packArgs

python/tests/kernel/test_kernel_features.py, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/nvqir/CircuitSimulator.h
=> Fix issue where qubits are retained with draw / tracer

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
=> Fix issue #1419 where docstrings were not being ignored

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Fixes #1446 
Fixes #1447 
Fixes #1448 
Fixes #1449 
Fixes #1450 
Fixes #1451
=> PyASTBridge Fixes - Issues 1446-1451

docs/sphinx/examples/cpp/basics/bernstein_vazirani.cpp
There are failures in Publishing validation, e.g., https://github.com/NVIDIA/cuda-quantum/actions/runs/8443846828
```
loc(callsite("bernstein_vazirani.cpp":33:22 at "bernstein_vazirani.cpp":52:3)): error: 'quake.extract_ref' op invalid index [6] because >= size [6]
```
This only showed up in the `remote-mqpu` (probably hardware emulation too) since we performed argument synthesis and loop unrolling => the pass manager can detect indexing issues.
This PR fixes the example.
Tested by: running locally
```
nvq++ --enable-mlir --target remote-mqpu  /home/cuda-quantum/examples/cpp/basics/bernstein_vazirani.cpp && ./a.out 
nvq++ --target quantinuum --emulate /home/cuda-quantum/examples/cpp/basics/bernstein_vazirani.cpp && ./a.out
```
Both produced correct results (`Encoded bitstring` == …
=> Fix Publishing validation failures

lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/LoopNormalize.cpp, runtime/cudaq/builder/QuakeValue.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/array.cpp, test/AST-Quake/control_flow.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/ranged_for.cpp, test/AST-Quake/ranged_for_qreg.cpp, test/AST-Quake/reverse.cpp, test/Quake-QIR/return_values.qke
Fix #925
Remove the last few traces of the mlir::IndexType from the compiler and update the tests accordingly.
=> [Core] Remove the use of IndexType

lib/Frontend/nvqpp/ConvertExpr.cpp
Although the control shorthands were being recognized in the bridge, they were inadverently being promoted to non-control forms of the same quantum gate.
Fixes #1464.
=> Fix #1464: control setting was being dropped.

include/cudaq/Optimizer/CodeGen/Passes.h, lib/Optimizer/CodeGen/Passes.cpp, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/runtime/mlir/py_register_dialects.cpp, runtime/common/RuntimeMLIR.cpp
According to MLIR: "The process of loading a Dialect in the context is not thread-safe, which forces all involved Dialects to be loaded before the multi-threaded pass manager starts the execution."
This PR makes sure that we load all the dialects when MLIR is needed at runtime and, hence may be used in a multi-threading environment (async. execution).
In particular, add a method to register the internal CodeGenDialect, which is only used by our passes (not the frontend).
Make sure that we load all Dialects in C++ (CUDAQ `MLIRRuntime`) and Python (builder/decorator).
Tested by: running `python/tests/remote/test_remote_platform.py`
=> Make sure that we register and load all dialects when using `PassManager` at runtime

.github/workflows/ci.yml, docker/test/wheels/fedora.Dockerfile
The latest Deployment pipeline is failing due to python3.10-3.10.14-1.fc38 being released (bumped from python3.10-3.10.13-3.fc38.x86_64).
Example: https://github.com/NVIDIA/cuda-quantum/actions/runs/8571513425/job/23495607331
This change fixes the failure by making sure that the latest version of libexpat is installed for that wheel test. This is not a change to our release Docker images or our regular development Docker images.
The 3.10.14 release notes (https://www.python.org/downloads/release/python-31014/) say:
> [gh-115399](https://github.com/python/cpython/issues/115399) & [gh-115398](https://github.com/python/cpython/issues/115398): bundled libexpat was updated to 2.6.0 to address CVE-2023-52425, and control of the new reparse deferral functionality was exposed with new APIs …
=> Fix wheel test Docker build failure (Fedora)

include/cudaq/Optimizer/Builder/Runtime.h, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h
This is basically a NFC. Cleanup some of the kernel builder code. Modify some of the interfaces to use `const T &` arguments to avoid making copies, etc., in particular with `std::string`.
=> Kernel builder cleanup.

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, runtime/cudaq/builder/kernel_builder.cpp
Add power-of-two tests.
See #1086
=> [features/qalloc] Error checking on number of elements in MLIR Verifier

.github/workflows/config/gitlab_commits.txt
CircuitSimulator does not call `canHandleObserve()` right before `observe` calls, so the `nvidia-mgpu` simulator was returning incorrect values to `canHandleObserve()` at the times they were being called. This PR fixes that...or, more specifically, it updates the GitLab commit to include the fix from GitLab.
=> Follow-up to #1477 - fix multi-gpu observe() calls

python/cudaq/__init__.py, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/utils.py, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/runtime/cudaq/target/py_runtime_target.cpp, python/tests/builder/test_kernel_builder.py, python/utils/LinkedLibraryHolder.cpp, python/utils/LinkedLibraryHolder.h, python/utils/OpaqueArguments.h, runtime/cudaq/qis/qudit.h, test/AST-Quake/qalloc_initialization.cpp
Implement `qalloc(state_vector)` support for the Python Kernel builder. 
Support patterns like 
```python
kernel, initState = cudaq.make_kernel(list[complex])
qubits = kernel.qalloc(initState)
state = [.70710678, 0., 0., 0.70710678]
counts = cudaq.sample(kernel, state)
state = np.array([.70710678, 0., 0., 0.70710678], dtype=complex)
kernel = cudaq.make_kernel()
qubits = kernel.qalloc(state)
counts = cudaq.sample(kernel)
```
This requires a better handle at the Python level on the floating point precision of simulation state data. 
```python 
cudaq.set_target('nvidia-fp64')
state = np.array([.70710678, 0., 0., 0.70710678], dtype=complex)
kernel = cudaq.make_kernel()
qubits = kernel.qalloc(state)
state = np.array([.70710678, 0., 0., 0.70710678], dtype=np.complex64)
kernel = …
```
=> python kernel builder qalloc support

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Fixes #1496 - issue with unknown attribute call expression 
```python 
import cudaq
@cudaq.kernel
def test_state(N: int):
q = cudaq.qvector(N)
h(q[0])
kernel.h(q[0]) # user error
test_state.compile()
```
=> Fix issue with unknown base on attribute call (throw an error)

.github/workflows/publishing_stable.yml
For now, this workflow pushes an image that is already on the NGC nightly channel to the new stable channel.
Since this is a new workflow, I need to merge this as is to properly try it out...
=> Workflow to publish stable releases

docker/build/devdeps.Dockerfile
https://pypi.org/project/h5py/3.11.0/#files shows that the new 3.11 release doesn't include manylinux aarch64 wheels.
See https://github.com/h5py/h5py/issues/2408
=> [devdeps] Build workaround for lack of h5py 3.11 aarch64 wheel

docs/sphinx/releases.rst, docs/sphinx/using/install/local_installation.rst, docs/sphinx/using/quick_start.rst
New link for CUDA-Q images: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/quantum/containers/cuda-quantum
Confirmed by pulling `docker pull nvcr.io/nvidia/quantum/cuda-quantum:0.7.0` without docker credentials.
=> [Fix] Update the docker image link for stable releases

runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/BasicExecutionManager.h, runtime/cudaq/qis/qudit.h
The execution manager should not expose details of how qudit allocation is handle internally through its public API. User must only know that, when they ask for a qudit allocation, they get a qudit identifier back.
Users should not write code that rely on a qudit having a particular identifier---something that the current name might invite them to do.
=> [rt] Rename getAvailableIndex function.

docker/build/assets.Dockerfile
This is needed to support scikit-build-core advancing from 0.8.2 to 0.9.0, presumably due to this PR: https://github.com/scikit-build/scikit-build-core/pull/698
=> Support new scikit-build-core release

docs/sphinx/examples/python/intro.py
Fixed the comment in intro.py example, 
[Issue #1497](https://github.com/NVIDIA/cuda-quantum/issues/1497)
```# Next, we can allocate qubits to the kernel via `qalloc(qubit_count)`.```
```# An empty call to `qalloc` will return a single qubit.```
```qubit = cudaq.qubit()```
To
```# Allocates qubit to |0> state```
```qubit = cudaq.qubit()```
Fixes #1497
=> Fix the comment in intro.py example #1497

lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Frontend/nvqpp/ConvertType.cpp, test/AST-Quake/string-0.cpp, test/AST-Quake/string-1.cpp
This patch reverts some of the core support intended for Pauli words. Revert this PR when the Pauli word work is picked up again.
=> [0.7.1] Reverts some support for Pauli word operations from kernels.

tools/fixup-linkage/fixup-linkage.cpp
This tool was being very cautious about rewriting the linkages on the C++ code. This change makes things more aggressive. This implies that the tool may fail by changing linkages that don't need to be changed and were not formerly being changed. The motivation for this is to allow linkages when generating shared library code to be fixed up.
=> [fixup-linkage] Open the door wider.

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/Dialect/CC/CCTypes.td, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Dialect/CC/CCTypes.cpp, test/AST-Quake/qalloc_state.cpp
Add a cc.state type to the CC dialect.
Replace !cc.struct<"cudaq.state"> with !cc.state.
Requires #1534 to be merged first.
=> [experimental/StateHandling] add new state type

tools/cudaq-translate/cudaq-translate.cpp
This patch fixes a segmentation fault in `cudaq-translate` when `--emit-llvm` is false. The issue occurs because the initialization lambda has non-trivial storage, and `llvm::function_ref` only holds a reference to a function, trashing the lambda after initialization.
=> [tools] Fix segfault in `cudaq-translate` when `emit-llvm=0`

include/cudaq/Optimizer/Builder/Intrinsics.h, include/cudaq/Optimizer/Dialect/CC/CCTypes.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Intrinsics.cpp, test/AST-Quake/qalloc_state.cpp
Extend the init_state op to take !cc.state types.
This changes the semantics of init_state to be a family of initializations. It can use a vector of floats directly or a cudaq::state object. Additionally, it may use a runtime library call with move semantics if the initializer is a cudaq::state object.
Requires #1554 to be merged first.
=> [experimental/stateHandling] extend the semantics of quake.init_state

python/cudaq/kernel/kernel_decorator.py
This PR optimizes for potential future modifications to `examples/python/tutorials/hybrid_qnns.ipynb`.
Enumerating and looping over all elements in `inspect.stack()` was incredibly slow when **running in a Jupyter notebook**. (Interestingly enough, the slowness was not apparent when running a Python script with the `python3` command.)
Here are some sample timings before the change:
```python
qubit_count = 1
@cudaq.kernel
def kernel():
qubits = cudaq.qvector(qubit_count)
cudaq.sample(kernel)
%timeit cudaq.sample(kernel)
qubit_count = 1
kernel = cudaq.make_kernel()
qubits = kernel.qalloc(qubit_count)
cudaq.sample(kernel)
%timeit cudaq.sample(kernel)
```
And after the change:
```python
qubit_count = 1
@cudaq.kernel
def kernel():
qubits = cudaq.qvector(qubit_count)
cudaq.sample(kernel) …
```
=> Optimize kernel mode for hybrid QNN test case

include/cudaq/Frontend/nvqpp/AttributeNames.h, include/cudaq/Optimizer/Builder/Intrinsics.h, include/cudaq/Optimizer/CodeGen/Passes.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/LowerToQIR.cpp, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, lib/Optimizer/Transforms/EraseNopCalls.cpp, lib/Optimizer/Transforms/FactorQuantumAlloc.cpp, runtime/cudaq/qis/qvector.h, test/AST-Quake/qalloc_state.cpp
This is intended to lower the rvalue reference to a cudaq::state to the newly extended quake.init_state operation, which now supports lowering of move semantics.
=> [experimental/stateHandling] Add rvalue reference to bridge.

include/cudaq/Optimizer/CodeGen/Pipelines.h, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/Pipelines.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, runtime/common/RuntimeMLIRCommonImpl.h, tools/cudaq-translate/cudaq-translate.cpp
NFC adjacent.
- Remove the template code. Not needed. Simple overload is sufficient.
- Move definitions out of the header. Not performance critical. Have to link the lib anyway.
- Update doxygen to reflect changes.
- Use MLIR's "convert" and "translate" distinction in terminology.
- Update all callers.
=> Refactor pipelines.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, python/runtime/cudaq/domains/plugins/PySCFDriver.cpp, python/utils/LinkedLibraryHolder.cpp, runtime/nvqir/CircuitSimulator.h, tools/cudaq-quake/cudaq-quake.cpp, tools/cudaq-translate/cudaq-translate.cpp, tools/nvqpp/backendConfig.cpp
- Add a note that the backendConfig.cpp file and it's content can be done more cleanly by generating the string in the compiler when we deprecate support for library mode and server-side execution.
- Tweak a few definitions to be in "storage-class specifiers type name = init;" order for regularity.
=> [NFC] Code cleanup

test/Quake-QIR/emit-mlir.qke
This patch adds a test for the change introduced in #1557.
This test verifies that `cudaq-translate --emit-llvm=false` works as intended and produces MLIR instead of LLVM IR.
=> [test] Add missing test for #1557:

include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, python/tests/kernel/test_kernel_complex.py, python/tests/kernel/test_kernel_float.py, runtime/common/SimulationState.h, runtime/cudaq/qis/execution_manager.h, runtime/cudaq/qis/managers/default/DefaultExecutionManager.cpp, runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp, runtime/cudaq/qis/qvector.h, runtime/cudaq/qis/state.cpp, runtime/cudaq/qis/state.h, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu, runtime/nvqir/custatevec/CuStateVecState.h, runtime/nvqir/cutensornet/mps_simulation_state.cpp, runtime/nvqir/cutensornet/mps_simulation_state.h, runtime/nvqir/cutensornet/simulator_mps_register.cpp, runtime/nvqir/cutensornet/simulator_tensornet_register.cpp, runtime/nvqir/cutensornet/tn_simulation_state.cpp, runtime/nvqir/cutensornet/tn_simulation_state.h, runtime/nvqir/qpp/QppCircuitSimulator.cpp, runtime/nvqir/qpp/QppDMCircuitSimulator.cpp, unittests/integration/qubit_allocation.cpp, unittests/qir/NVQIRTester.cpp, unittests/qudit/simple_qudit/SimpleQuditExecutionManager.cpp
This is an alternative approach to https://github.com/NVIDIA/cuda-quantum/pull/1542 whereby the user-facing `state` is a thin wrapper around the underlying `SimulationState` data (i.e., passing by reference or value doesn't really matter); plus sub-state allocation should force an implicit copy, and `qvector` initialization from existing state + subsequent `get_state` should also force a copy.
- Implementations for in-source simulator backends (except MPS) are provided. 
- Adding an NVQIR function prototype (along the existing allocation from vector QIR functions)
- Adding NVQIR tests.
=> [StateHandling] State data with value semantics via `state` acting as a thin pointer wrapper   

lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake-QIR/argument.qke, test/Quake-QIR/return_values.qke
buffer when calling altLaunchKernel().
- update tests
=> [Core] Add a function to determine the offset of the return value in the

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/LowerToCFG.cpp, test/Quake/loop.qke, test/Quake/to_cfg.qke
Add an else region to cc.loop.
Add builders, verifiers, etc.
Add roundtrip test.
Add lowering of cc.loop to CFG.
Add test for python for-else to cfg conversion.
=> [Core] Add support for python's for-else to cc.loop.

lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/kernel/test_kernel_features.py
**Problem**
The structure we use for collecting arguments to pass to python is in non-packed form, but we rely on arguments to follow each other immediately (without alignment padding) when we try to find the return argument (last in that structure). This results in incorrect parameter passing to python when alignment padding is inserted (for example, in case of one bool and one int  argument).
**Solution**
Use `genReturnOffsetFunction` to create a `returnOffset` function and call it to compute the return offset for python kernels instead of performing incorrect manual calculations.
Closes: https://github.com/NVIDIA/cuda-quantum/issues/1580
=> Fix incorrect parameter copy when passing parameters to python kernel functions

.github/workflows/integration_tests.yml
The nightly tests are failing, which is expected while OQC machines are down for maintenance. Disable the OQC tests so it is easier to tell if our [nightly tests](https://github.com/NVIDIA/cuda-quantum/actions/workflows/integration_tests.yml) for the other targets are in good shape.
The tests will be restored once the OQC machines are enabled again.
=> Disable nightly tests for OQC due to maintenance

python/cudaq/kernel/analysis.py, python/tests/mlir/ast_conditionals.py, python/tests/mlir/target/conditional_sample.py
The current Python `MidCircuitMeasurementAnalyzer` visitor only supports certain expressions, e.g., `if val` but not `if val == boolVar`, where `val = mz(q)`.
Hence, it may mis-identify some kernels as non-measurement feedback, i.e., not setting `qubitMeasurementFeedback=true`, causing wrong sampling mode being used.
This PR:
- Add more handling cases: variable name or variable subscript; `CompareOp`; handle variables in `BoolOp` and `UnaryOp`.
- Add IR checks and target tests.
Note: this is not an exhaustive handling of all possible scenarios.
Resolves https://github.com/NVIDIA/cuda-quantum/issues/1618
=> Fixes for https://github.com/NVIDIA/cuda-quantum/issues/1618

docker/release/cudaq.nvqc.Dockerfile
The NVQC deployment is broken as a result of the recent rename. This fixes it.
=> Follow-up to #1587 - fix NVQC deployment

include/cudaq/Optimizer/Dialect/CC/CCInterfaces.h, include/cudaq/Optimizer/Dialect/CC/CCInterfaces.td, include/cudaq/Optimizer/Dialect/CC/CCOps.h, include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Dialect/CC/CMakeLists.txt, include/cudaq/Optimizer/Dialect/Quake/QuakeInterfaces.td, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.h, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.td, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/MemToReg.cpp, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, test/Quake/memtoreg-2.qke, test/Quake/roundtrip-ops.qke
A quantum type (!quake.wire) is a linear type. While this constraint was widely enforced previously, it was exempted when the linear value reached a control-flow conditional. This patch closes that loophole.
- Add a new Linear type trait to be used with high-level conditionals that are conceptually conditional control-flow. (cc.if)
- Modify cc.if to use the linear type trait. Implement parser and pretty printer, to support the sigma arguments on the blocks.
- Add roundtrip test.
- Fix check lines in existing tests.
=> [Core] Completes making quantum values a linear type.

runtime/common/Future.cpp, runtime/common/ServerHelper.h, runtime/cudaq/platform/default/rest/helpers/iqm/IQMServerHelper.cpp
CUDA Quantum runtime polls for a `RemoteRESTQPU` results quite aggressively, 100 microseconds is the hardcoded value. While this is ok for a QPU HTTP API located in the local network, when executing CUDA Quantum programs against a QPU HTTP API located in a cloud, it is very likely to hit a rate-limiter of sorts, like, for example, in case of IQM Resonance.
=> Support results polling interval override for RemoteRESTQPUs

.github/workflows/ci.yml, docker/build/devdeps.ompi.Dockerfile, docs/sphinx/using/install/data_center_install.rst, docs/sphinx/using/install/local_installation.rst
This PR pins the `-march=` compiler flag for OpenMPI build on ARM (similar to the approach taken for x86).
Currently, we're using `-march=native`, which is too broad, hence prone to runner's hardware update.
ARMv8.0-A was chosen as it's the first one in the v8 series (with 64-bit support).
Illegal instruction exception when using cuda-q docker container on some specific ARM platforms, e.g., failed on ARM Neoverse-N1, passed on Grace Hopper.
The illegal instruction was ARM's `STLUR`, an ARMv8.4 instruction.
The CI runner, `linux-arm64-cpu8`, is an AWS's `m7g.2xlarge` instance, which has a Graviton3 (ARMv8.5) processor.
**Notes:**
- CUDA-Q's v0.6 image doesn't have `STLUR` in the OpenMPI's binary. We might have switched the runner hardware some time in between that release and now.
**Tested …
=> Pin ARM's `-march` flag for OpenMPI build

docker/release/cudaq.wheel.Dockerfile, runtime/nvqir/cutensornet/mps_simulation_state.cpp, runtime/nvqir/cutensornet/mps_simulation_state.h, runtime/nvqir/cutensornet/simulator_cutensornet.h, runtime/nvqir/cutensornet/simulator_mps_register.cpp, runtime/nvqir/cutensornet/simulator_tensornet_register.cpp, runtime/nvqir/cutensornet/tensornet_state.cpp, runtime/nvqir/cutensornet/tensornet_state.h, runtime/nvqir/cutensornet/tn_simulation_state.cpp
Some non-trivial changes to the tensornet backend and state implementations required after merging from `main`.
In particular, the introduction of `cutensornetStateApplyControlledTensorOperator` in the latest cuquantum (pulled in from main) requires some code changes to the state implementation.
=> Update `tensornet` backend/state implementation post merge

docs/sphinx/using/backends/simulators.rst
This warning is no longer accurate since #1420 was merged.
=> [docs] Remove tensornet-mps limitation that is no longer accurate

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.h, include/cudaq/Optimizer/Dialect/Quake/QuakeTypes.h, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/Mapping.cpp, lib/Optimizer/Transforms/RegToMem.cpp
We were using the terminology "value-SSA" and "reference-SSA" from classical computing in some of the old code to distinguish between quantum values that are referred to by value and by reference. The value/reference model is clearly appropriate, but the SSA isn't quite correct, pedantically speaking.
Unlike SSA, in quantum computation a value has a linear quantum type. It must be used exactly once. This follows from the inability to "make a copy" of a quantum state. SSA values, on the other hand, cannot be redefined but one can make as many copies of them as one wants.
While tweaking this terminology (hopefully to make it easier on the reader), these changes tighten some of the IR checks. One can now test if an Operation is purely in linear-value or reference form (or neither).
=> Update the terminology used in the names of type testing functions.

runtime/cudaq/qis/managers/photonics/photonics_qis.h
`T` is often used for a type, but in this header it is used for the number of levels in a qudit.
=> Use a more meaningful template argument name.

include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h, lib/Optimizer/CodeGen/ConvertToQIR.cpp, runtime/nvqir/CircuitSimulator.h, runtime/nvqir/NVQIR.cpp, targettests/execution/qvector_mismatch.cpp, test/AST-Quake/qalloc_initialization.cpp
It may be the case that the state vector data is in a precision that does not match that of the simulator. The runtime library knows precisely what simulator has been selected and can therefore convert the state vector to the expected format at runtime. This conversion may be *expensive* if the state vector is quite long. As a result, the runtime may want to emit a warning when a conversion path is taken.
The following conversions happen at runtime with this change:
```
vector<float> -> vector<complex<float>>
vector<float> -> vector<complex<double>>
vector<double> -> vector<complex<float>>
vector<double> -> vector<complex<double>>
vector<complex<float>> -> vector<complex<double>>
vector<complex<double>> -> vector<complex<float>>
```
If the input is `vector<complex<float>>` or …
=> Fix mismatches between input state and simulation engine precision.

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
* Root cause: The 'break' statement visitor in Python AST bridge did not account for multiple nested loops
* Also fixed the same issue for 'continue' statement
* Added the example from issue #1682  as a test
=> [Bug-fix] [Python] Correctly handle 'break' within nested loops

python/tests/kernel/test_kernel_features.py
Resolves #1662 
Note: #1605 resolved the bug associated with #1662. This PR simply adds the appropriate test to ensure it doesn't break in the future.
=> [test] Add test for subtraction in Python kernel

runtime/common/BaseRestRemoteClient.h, runtime/common/NvqcConfig.h
This change is intended to have no effect on production usage of NVQC while making it simpler for developers to use the dev organization. (I.e. the `NVQC_NCA_ID` environment shouldn't be needed for most use cases anymore.)
=> NVQC: Auto-select NCA ID based on API key

include/cudaq/Optimizer/Dialect/CC/CCTypes.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, runtime/cudaq/qis/qvector.h, test/AST-Quake/qalloc_state.cpp
Follows the latest design change for ownership management of state objects. Remove the support for "move semantics" to allow the logical lifetime of a state object to escape into called functions and the swapping of any resources it may contain.
- remove the move constructor from qvector
- remove move attribute from init_state op
- remove explicit test for move semantics
- simplify the handling of init_state data: it has to be a pointer to a supported data type, floating-point, complex, or state.
=> [stateHandling] Remove swap semantics optimization support.

include/cudaq/Optimizer/CodeGen/QIRFunctionNames.h
Makes this file consistent with the rest of the code.
=> [NFC] Make the order storage-class before specifier.

.github/workflows/publishing.yml
Some of our nightly tests (e.g. https://github.com/NVIDIA/cuda-quantum/actions/runs/9262860346/job/25480432825) are failing because the publishes wheels expire too quickly. I think they were set to expire after 1 day to save space, but I think we can hold a reduced set of wheels longer.
=> Hold some published wheels longer

scripts/nvqc_proxy.py
Our NVQC logs have too much clutter originating from the utils container talking to the health endpoint, which we don't have any control over. Use this change to help reduce log clutter on the health endpoint.
=> Reduce NVQC server log file clutter

include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/CodeGen/QuakeToLLVM.cpp, test/Quake-QIR/basic.qke, test/Quake-QIR/exp_pauli-1.qke, test/Quake-QIR/exp_pauli-3.qke, test/Quake-QIR/issue_1703.qke, test/Quake-QIR/veq_or_qubit_control_args.qke
When a temporary has a constant size, it can be promoted to the entry block. This eliminates any control dependence that may creep in when the temporary, if added inline, may be in a block with control dependence. Leans into LLVM being able to do live range analysis and fuse/eliminate these allocations.
Add a new function in the factory to generate the pattern in LLVM-IR dialect.
Fixes #1703.  Adds regression test.
=> Allocate temporaries in conversion to LLVM in entry block.

include/cudaq/Optimizer/Dialect/Common/InlinerInterface.h, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, targettests/Kernel/inline-qpu-func.cpp
Fixes #1726 
The underlying problem is that `cudaq-entrypoint` attribute is applied to all `__qpu__` functions, but it is removed if there are any `cudaq::qubit` parameters. Downstream code was trying to prevent inlining of `cudaq-entrypoint` kernels for thunk functions, but it was preventing inlining of ALL `cudaq-entrypoint` kernels, which was a bit heavy handed.
=> Allow inlined calls to cudaq-entrypoint funcs as long as not in a thunk

include/cudaq/Optimizer/CodeGen/CodeGenOps.td, include/cudaq/Optimizer/CodeGen/Passes.h, include/cudaq/Optimizer/CodeGen/Passes.td, lib/Optimizer/CodeGen/ConvertToQIR.cpp, lib/Optimizer/CodeGen/Pipelines.cpp, runtime/cudaq/builder/kernel_builder.cpp, test/Quake/codegen_dialect.qke, unittests/Optimizer/QuakeSynthTester.cpp
Typed pointers have disappeared in the LLVM-IR dialect, so we needed a more coherent way of identifying the type of data passed to the initialization state. This change extends the op to keep track of the information so it isn't lost when lowering to opaque pointers.
Add a separate pass for testing and a regression test to make sure the RAII ops are being formed correctly.
=> [stateHandling] Future proofing codegen dialect.

python/cudaq/__init__.py, python/tests/mlir/target/callable_kernel_arg.py
Resolves #1745 
This makes it similar to the `nvq++` driver script so there isn't a discrepancy anymore.
=> Make Python support `--target=<target>` option (with `=`)

scripts/validate_container.sh
Validation is failing with
```
=============================
Testing builder:
Source: examples/cpp/other/builder/builder.cpp
Testing on default target...
Exited with code 0
Skipping density-matrix-cpu target.
Testing on qpp-cpu target...
Exited with code 0
Testing on remote-mqpu target...
Exited with code 134
loc("<builder>":1:1): error: 'func.call' op '__nvqpp_getStateVectorLength_fp64' does not reference a valid function
terminate called after throwing an instance of 'std::runtime_error'
what():  Could not successfully apply quake-synth.
```
=> [stateHandling] fix broken tests

.github/workflows/integration_tests.yml
Our A100 backend is under heavier load recently (as evidenced by 5 consecutive deployment failures during our nightly integration tests), so switch to a different one that should have more availability.
=> Update NGC_NVQC_DEPLOYMENT_SPEC for nightly tests

unittests/integration/qubit_allocation.cpp
* Reduce qubit count in the test for repeatability.
=> Fix `tensornet_mps_AllocationTester.checkStateFromMpsData`  test

runtime/common/JsonConvert.h, runtime/nvqir/custatevec/CuStateVecState.h
Fixing nightly integration failure: "Server error: simulation precision is FP32 but overlap requested with FP64 state data."
We need to use the proper `toHost` call since implicit conversion is disabled.
Also, fix the error messages.
=> Fix the Json conversion for custatevec-fp32 state data

runtime/common/JsonConvert.h
The `ExecutionContext::simulationData` (pre-state handling) type change from `std::tuple<std::vector<std::size_t>, std::vector<std::complex<double>>>` to `std::unique_ptr<SimulationState>` needs to be handle properly during JSON serialization.
In particular, an old/existing server instance adds `simulationData` with empty dim when no state data is available rather than non-data as we switch to the `unique_ptr` data type. 
- Manually run the `nvqc_integration_docker_test` of `nvqc_regression_tests.yml` with the locally-build cuda-q client against the prod nvqc service. 
Notes: 
- Will monitor wheel check post-merge.
- The docker test does include Python examples.
=> Fixes for backward compatibility with NVQC

unittests/integration/qubit_allocation.cpp
These test cases use `cudaq::sample`, hence need random seed set for repeatability.
=> Set random seed in sampling for repeatability

runtime/common/JsonConvert.h, unittests/CMakeLists.txt, unittests/utils/UtilsTester.cpp
`cudaq::optimizer` and `cudaq::gradient` are abstract virtual classes, so they need special handling for JSON serialization and deserialization. This PR adds that support.
These changes should be backwards compatible with the existing NVQC deployment as long as the new `std::optional<RestRequestOptFields> opt` field in the `RestRequest` is not populated. (And it is indeed not populated in any of our current code.)
This is all in support of remote VQE/optimizer execution on NVQC.
=> Add JSON serializers/deserializers for optimizers and gradients

targettests/Remote-Sim/args_synthesis.cpp, targettests/Remote-Sim/no_inline.cpp, targettests/execution/gen_device_code.cpp, tools/nvqpp/nvq++.in
Add a new option to be able to select the "assembly" specification to emit code for (e.g. "qir", "qir-adaptive", ...) and rename all the pass flag options to conform with the `-f*` and `-fno*` style seen in clang++, etc.
=> [driver] Add a new option, change names of flag options.

lib/Optimizer/CodeGen/ConvertToQIR.cpp, lib/Optimizer/CodeGen/ConvertToQIRProfile.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, runtime/common/JIT.cpp, runtime/cudaq/builder/kernel_builder.cpp, unittests/Optimizer/QuakeSynthTester.cpp
This PR also addresses some issues in QIR codegen that were found doing ad hoc testing. It could be the case that trying to use QIR with state handling is not supposed to work at all, however. To wit, there are checks made the verify that the code conforms with the QIR specification and these *will* be violated when using qubit allocations with state. For example, the state is not a literal constant but rather a buffer of values. The buffer will be in memory, which is not a constant. The LLVM optimizer may chose LLVM instructions and intrinsics that QIR doesn't consider "legal" as well.
=> [core] Teach synthesis how to unpack a vector of complex values.

python/utils/LinkedLibraryHolder.cpp
When using libc++ headers, the unistd.h file must be included explicitly.
=> [build] Add missing include file.

docs/sphinx/examples/cpp/providers/nvqc_state.cpp
`state.h` is deprecated (pragma warning). We need to use `get_state.h` in the example.
Also, did a quick search to make sure we don't use this `algorithms/state.h` in any other places.
=> Use `get_state.h` rather than the deprecated `state.h`

runtime/cudaq/qis/managers/default/DefaultExecutionManager.cpp, runtime/nvqir/CircuitSimulator.h
Measuring a `cudaq::spin_op` operation requires knowledge about the inner workings to the backend simulator, specifically we need to guarantee that the operation are applied and not left in the operation queue. To decouple the execution menager from the simulator, we move the implementation of this method to the simulator base class.
=> [rt] Move `measureSpinOp` impl. to the simulator.

.github/workflows/config/md_link_check_config.json
These servers go up and down enough to cause the CI to fail frequently enough to cause a lot of lost productivity. Just whitelist the domain to keep the CI from failing.
=> [ci] Whitelist microsoft and visualstudio.

runtime/cudaq/algorithms/optimizer.h
This allows the optimizer logic to be reused within the CUDA-Q source tree.
(No side effect observed on tests / application / user code)
=> Remove the redundant header from optimizer file 

python/utils/LinkedLibraryHolder.cpp
The simulator library loading order currently ends up being unspecified (due to directory_iterator order being unspecified by the C++ standard), and due to #698, this can have negative effects. This PR doesn't totally resolve any ordering issues, but it at least makes the consistent for different users and different platforms by sorting the library names alphabetically before processing them.
=> Make LinkedLibraryHolder.cpp ordering consistent

.github/workflows/config/gitlab_commits.txt, .github/workflows/config/md_link_check_config.json
Changes (compared to the previous sha):
- Minor code refactor.
- Fixed a bug in the `nvidia-mgpu` config: `CUDAQ_SIMULATION_SCALAR_FPXX` preprocessor define was not set. Hence, it does not report the proper precision in Python runtime target info (parsed from this config).
- Expose the `nvidia-mgpu-fp32` target. The Python config parser only supports simple config (e.g., switching simulator plugin based on extra arguments needs more investigation).
=> Update `mgpu` commit SHA

scripts/validate_wheel.sh
This resolves the Publishing failure seen in last night's run: https://github.com/NVIDIA/cuda-quantum/actions/runs/9674889993/job/26693187678.
`psutil` is a package needed by some of our tests so, like `numpy`, simply `pip install` it will doing validation.
=> Follow-up to #1824 - update validate_wheel.sh

runtime/common/BaseRestRemoteClient.h
Without this change, some uses of `backend='nvidia-mqpu'` for `nvqc` would cause a false warning message:
```
The requested backend simulator (nvidia-mqpu) is not capable of using all 4 GPUs requested.
Only one GPU will be used for simulation.
```
This change fixes that by adding it to an internal list of multi-GPU backends.
=> Add nvidia-mqpu as a valid multi-GPU backend for NVQC

runtime/nvqir/cutensornet/mps_simulation_state.cpp, runtime/nvqir/cutensornet/mps_simulation_state.h, runtime/nvqir/cutensornet/simulator_cutensornet.cpp, runtime/nvqir/cutensornet/simulator_cutensornet.h, runtime/nvqir/cutensornet/simulator_mps_register.cpp, runtime/nvqir/cutensornet/simulator_tensornet_register.cpp, runtime/nvqir/cutensornet/tensornet_state.cpp, runtime/nvqir/cutensornet/tensornet_state.h, runtime/nvqir/cutensornet/tn_simulation_state.cpp, runtime/nvqir/cutensornet/tn_simulation_state.h
Scratchpad (to use with tensornet 'compute' API) is created a single time, attached to the simulator class.
All other sub-classes (`state`-like objects) just keep a reference to this scratch pad.
**Rationale**:
We observed some performance degradation running these compute API (e.g., state/observe, etc.) in a loop. Theoretically, the performance should be better since the system is warmed up. 
The root cause is this scratch pad dealloc-realloc operations.
=> Use a single scratchpad for all tensornet operations

include/cudaq/Optimizer/Builder/Intrinsics.h, lib/Optimizer/Builder/Intrinsics.cpp
These changes add a pair of methods to correctly build a GlobalOp that corresponds with a `vector<complex<REAL>>` constant block. Using these functions will generate a GlobalOp which has the attributes that MLIR will lower to LLVM correctly (and without crashing).
=> [core] Add to the factory's IRBuilder the creating of vector<complex>

lib/Frontend/nvqpp/ConvertStmt.cpp
for vector<struct{...}> when the struct size is recorded from the AST.
=> [C++ bridge] Add lowering for vector<complex<REAL>> and

.github/workflows/nvqc_regression_tests.yml
This test is regularly failing because the deployed NVQC server does not support this yet. Skip it so that the test can pass (and it will be easier to identify test failures).
For an example failure, see: https://github.com/NVIDIA/cuda-quantum/actions/runs/9672862176
=> Skip state_overlap test for nightly NVQC test

cmake/Modules/CMakeLists.txt, cmake/Modules/NVQIRConfig.cmake
CUDAQ is hardcoded to install itself on `lib/`, while not all of our dependencies will do the same. For example, `fmt` installs itself on `CMAKE_INSTALL_LIBDIR`, which might be `lib` or `lib64/` depending on the system. Thus, when trying to create a downstream project that depends on CUDAQ cmake integration, the hardcoded paths set on our downstream cmake files might fail to find required dependencies. 
For example, trying to build a downstream project using:
```sh
cmake .. -G ninja -DCUDAQ_DIR=~/.cudaq/lib/cmake/cudaq
```
Might fail because it cannot find the required `fmt` lib. This partially fixes that by setting our hardcoded paths as HINTS in `find_dependency`. Now, user will be able to use:
```sh
cmake .. -G ninja -DCUDAQ_DIR=~/.cudaq/lib/cmake/cudaq …
```
=> [cmake] Fix downstream cmake

include/cudaq/Optimizer/Dialect/CC/CCOps.h, include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, python/cudaq/kernel/ast_bridge.py, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, runtime/common/BaseRemoteRESTQPU.h, runtime/common/BaseRestRemoteClient.h, test/Quake-QIR/const_array.qke, test/Quake/roundtrip-ops.qke, unittests/Optimizer/QuakeSynthTester.cpp
These are semantically the same operation. The distinction was a
manifestation of how LLVM works rather than what the operation did.
While we're here, add semantics verification tests. Also split apart the
get_const_element fold operation from a canonicalization. Make sure we
run canonicalization *after* parameter synthesis. Update affected tests.
Depends on merge of #1853
=> [core] Merge the get_const_element and extract_value operations.

include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/LiftArrayAlloc.cpp, lib/Optimizer/Transforms/PassDetails.h, test/Quake/lift_array.qke
This pass will promote an array constructed inline on the stack to a cc.const_array op.
TODO: when the array is used by quake.init_state, the verifier will fail. Nothing in the code base is built to accept an array *value* as an input to quake.init_state's second argument.
~Builds on #1862~
This pass will be useful to both the unitary custom op and state handling projects.
=> [core] Add -lift-array-value pass

include/cudaq/Optimizer/Builder/Intrinsics.h, include/cudaq/Optimizer/Dialect/CC/CCOps.h, lib/Frontend/nvqpp/ConvertStmt.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp
This refactors the common code that will generate expressions to determine the size of an object with a type that can be reified in memory statically. The code is moved to the IRBuilder and out from ConvertStmt and GenKernelExecution. (There may be other places that ought to use this new IRBuilder code.)
=> Fix #1886: refactoring of common code.

docker/build/devdeps.Dockerfile, tpls/customizations/llvm/fix_region_simplification.diff
Fixes #1799 
This fixes the underlying MLIR bug by applying a patch to our version of LLVM. The problem is that it was merging regions despite their block arguments being used differently downstream. It should not do that, so this patch fixes that.
We will work on getting it merged upstream in the coming weeks.
=> [llvm] Fix region simplification bug

python/cudaq/kernel/ast_bridge.py
Fixes for the failing tests under `python/tests/kernel/test_kernel_qvector_init.py`
=> [Bug-fix] Typos in variable names in '__copyVectorAndCastElements'

python/tests/remote/test_remote_code_exec.py, tools/cudaq-qpud/nvqc_proxy.py
It can still be enabled with the `CUDAQ_SER_CODE_EXEC` environment variable.
=> Disable remote serialized code execution by default

runtime/common/BaseRestRemoteClient.h
This small change copies function declarations from the "old" module to the new module to fix correctness issues. This will never be a problem if the old module is well formed. Dropping them on the floor is a bug because there may be calls to these functions in the selected kernel, and those calls will fail to verify after the declarations are dropped.
=> [runtime] Fix bug with function declarations being dropped on the floor

include/cudaq/Optimizer/CodeGen/Pipelines.h, lib/Optimizer/CodeGen/Pipelines.cpp, runtime/cudaq/builder/kernel_builder.cpp, runtime/cudaq/builder/kernel_builder.h
This simplifies kernel_builder and leverages that Quake already knows what to do with veq types.
Fix reset while we are here. There is no need to test the types of these arguments. The verifier already does that.
Fix std::string arguments to not make copies of the string at each call site.
=> Fix #17: don't generate loops in the kernel_builder for measurements

runtime/common/JIT.cpp, runtime/common/JIT.h, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp, runtime/cudaq/qis/execution_manager.h, targettests/Remote-Sim/custom_operation.cpp
Fixes #1922 
The problem was that the LLVM JIT objects were being destroyed right at the end of `invokeWrappedKernel()`, and the ExecutionManager's `registeredOperations` contained there were dangling pointers into object code created during that JIT (specifically the vtables for the custom operations' structs). The fix is to make the lifetime of the LLVM JIT last longer than it previously did.
Also, we have to provide a mechanism to clear the registered operations so that shutdown of `cudaq-qpud` doesn't attempt to call destructors in object code that was created during a JIT (again, vtables).
=> Fix custom operations on remote-mqpu (library mode)

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_kernel_features.py
Enable the following pattern 
```python
def localFunction():
@cudaq.kernel
def bell(i : int):
q = cudaq.qvector(i)
h(q[0])
x.ctrl(q[0], q[1])    
return bell 
opaqueBell = localFunction()
@cudaq.kernel
def kernel():
opaqueBell(2)
counts = cudaq.sample(opaqueBell)
```
=> Enable capture of opaque kernel functions

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/QuakeToLLVM.cpp, lib/Optimizer/Transforms/ExpandMeasurements.cpp, runtime/cudaq/builder/kernel_builder.cpp
Simplify the kernel_builder to use both qubit and veq forms of the reset op. Add a pattern to expand measurements that also expands resets.
~Requires #1910 to be merged first.~
=> [kernel_builder] Use quake.reset with a veq argument.

lib/Optimizer/Dialect/Quake/QuakeOps.cpp, test/AST-Quake/qalloc_initialization.cpp
There is no need to cast the state vector to unknown length, so this pattern will forward the vector and drop the use of an unused cast.
=> [core] Add a canonicalization rule for quake.init_state

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Frontend/nvqpp/AttributeNames.h, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Optimizer/Transforms/GenDeviceCodeLoader.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp
* Address the comment captured in issue #1918 
-- don't treat custom operation generator functions exactly like kernels.
* They are still processed similar to kernels but aren't entry-point kernels and skipped by kernel execution, and device code loader passes.
=> [refactoring] [C++] Clean-up for "generator" functions

lib/Optimizer/Transforms/MemToReg.cpp, test/Quake/memtoreg-7.qke
When the body of a loop defines a value that was live-in and live-out of that loop, the region arguments have to be added for all loop regions.
These arguments must be added to balance all the region arguments even if the argument is technically not live-in to the region because it is defined unconditionally therein.
=> [core] Fix memtoreg bug with loop body

python/cudaq/kernel/ast_bridge.py, python/tests/mlir/bool_var_scope.py, python/tests/mlir/bug_1777.py
* If a boolean variable is not the result of measurement then treat it as regular variable.
* Update the value of boolean if seen in outer scope.
=> [Python] [AST Bridge] Correctly distinguish measurement result and boolean variable

lib/Optimizer/Transforms/QuakeSynthesizer.cpp
When computing the size in pointer-free format, pointers have 0 size.
=> [QuakeSynth] Fix bug in pointer-free size calculation.

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/pauli_word.cpp
This fixes passing a cudaq::pauli_word as an argument. (This is only a front-end change.)
Requires #1966 to be merged first.
=> Fix #1957: accept pauli_word as an argument.

python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/register_op.py, python/tests/custom/test_custom_operations.py, python/tests/mlir/custom_op_builder.py
* Allow users to specify unitary as `np.matrix`, 2D array
* Make custom operations available to look up by name in the builder mode via attribute getter
=> [Python] Enhancements to the custom operations feature

lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, python/tests/kernel/test_kernel_features.py, test/Quake/control_and_adjoint.qke
* Handle case where both `control` and `adjoint` variants of a kernel are used.
* Fixes one of the issues captured in issue #1871
=> [Bug-fix] Support use of `control` and `adjoint` variants of a kernel

lib/Optimizer/Builder/Factory.cpp
The pauli_word used to be a std::string, but it was morphed to be a std::vector and the type signatures were not updated. This resulted in the host side function trying to pack the wrong datatype into the comm buffer and crashing with a SIGSEGV.
Related: #1957
=> [pauli_word] Update the C++ host type for pauli_word class.

.github/workflows/test_in_devenv.yml, targettests/CMakeLists.txt
Running these tests on a machine with too many cores can exhaust the GPU resources, so provide a reasonable limit here.
Also fix the CI to use the correct `-E` syntax. You cannot daisy chain multiple `-E` options together for `ctest` because it will only honor the last one. Due to our incorrect usage, we have been running duplicate tests with `ctest-nvqpp` for a while, and this change will fix that.
=> [test] Limit the number of llvm-lit workers for target tests

runtime/common/BaseRemoteSimulatorQPU.h, runtime/common/BaseRestRemoteClient.h
This is a minor change to allow developers to override the client's knowledge of remote-mqpu server capabilities similar to how we could already override the client's knowledge of NVQC server capabilities.
It also updates the code to use the new common `getEnvBool` function in both places.
=> Allow env var override for remote-mqpu capabilities

targettests/Remote-Sim/return_values.cpp
The following CI jobs have been hanging on this test. I believe this change will help.
* https://github.com/NVIDIA/cuda-quantum/actions/runs/10101453154/job/27935618355
* https://github.com/NVIDIA/cuda-quantum/actions/runs/10098919554/job/27927334686
* https://github.com/NVIDIA/cuda-quantum/actions/runs/10097769956/job/27923837081
=> [test] Follow-up to #1969 - set random seed in return_values.cpp test

.github/workflows/ci.yml, .github/workflows/create_cache_command.yml, .github/workflows/deployments.yml, .github/workflows/dev_environment.yml, .github/workflows/publishing.yml
This is required to eliminate warnings about upload/download artifacts v3 support going away: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
E.g.
```
[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/NVIDIA/cuda-quantum/actions/runs/10097651815/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: <snip>.
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
=> Update cloudposse/github-action-matrix-outputs-read/write versions

targettests/Remote-Sim/args_parsing.cpp, targettests/Remote-Sim/free_func-cpp17.cpp, targettests/Remote-Sim/free_func.cpp, targettests/Remote-Sim/get_state.cpp, targettests/Remote-Sim/kernel_builder.cpp, targettests/Remote-Sim/nested_vectors.cpp, targettests/Remote-Sim/no_inline.cpp, targettests/Remote-Sim/observe-cpp17.cpp, targettests/Remote-Sim/observe.cpp, targettests/Remote-Sim/observe_async-cpp17.cpp, targettests/Remote-Sim/observe_async.cpp, targettests/Remote-Sim/pauli_word.cpp, targettests/Remote-Sim/remote_test_assert.h, targettests/Remote-Sim/return_values.cpp, targettests/Remote-Sim/sample-cpp17.cpp, targettests/Remote-Sim/sample.cpp, targettests/Remote-Sim/sample_async.cpp, targettests/Remote-Sim/state_amplitude.cpp, targettests/Remote-Sim/state_overlap.cpp, targettests/Remote-Sim/unsupport_args.cpp, targettests/Remote-Sim/vqe_h2.cpp
Update `targettests/Remote-Sim/*.cpp` to use a new macro instead of `assert()` because the standard `assert()` calls are causing hangs during test failures rather than cleanly aborting with an error message. I manually tested this change by modifying one of the assertion checks to intentionally fail while running `llvm-lit`, and it failed as desired now.
=> Update remote-mqpu tests to cleanly abort during assertion checks

.github/workflows/integration_tests.yml, runtime/cudaq/platform/default/rest_server/helpers/RestRemoteServer.cpp, targettests/Remote-Sim/vqe_h2.cpp
This has 3 separate-but-related changes:
1. Update the NVQC server code (and `remote-mqpu` server code) to honor the number of shots in the request from the client when doing VQE optimizations.
2. Updated the targettests/Remote-Sim/vqe_h2.cpp test to set a random number seed and widen the tolerance of the assertion. This is required due to the variety of different ways the test can be executed (qpp-cpu, nvidia, new-nvqc, old-nvqc, and remote-mqpu).
3. Update the nightly integration test to set `CUDAQ_CLIENT_REMOTE_CAPABILITY_OVERRIDE=1` because the existing name of our deployed test doesn't follow any specific naming conventions that allow the client to infer anything about the server-side capabilities. The environment variable should only be set in integration_tests.yml when we are …
=> Follow-up to #1901 - fix shots-based VQE handling on server

.github/workflows/integration_tests.yml
This will resolve the following two test failures seen in https://github.com/NVIDIA/cuda-quantum/actions/runs/10155426211:
* examples/python/advanced_vqe.py
* examples/python/qaoa_maxcut.py
Also add the `RUN_AS_NOBODY` environment variable since our standard deployment process will utilize that.
=> [test] Update integration_test.yml to enable remote Python execution on server

.github/workflows/config/gitlab_commits.txt
1. Fix segfault during cudaq.draw()
2. Fix gate count telemetry to be consistent with other simulators
=> Update mgpu commit hash for two bugfixes

runtime/cudaq/platform/default/nvidia-fp64.yml, runtime/cudaq/platform/mqpu/nvidia-mqpu-fp64.yml, runtime/cudaq/platform/mqpu/nvidia-mqpu.yml, targettests/TargetConfig/RegressionValidation/nvidia-fp64.config, targettests/TargetConfig/RegressionValidation/nvidia-mqpu-fp64.config, targettests/TargetConfig/RegressionValidation/nvidia-mqpu.config, targettests/lit.cfg.py, targettests/lit.site.cfg.py.in, test/lit.cfg.py
- Enable the new custatevec-based simulators for all legacy targets (`nvidia-fp64`, `nvidia-mqpu`, and `nvidia-mqpu-fp32`) as the first option (to be taken if available).
- Update the config file regression checks.
- Fixed a fallout from https://github.com/NVIDIA/cuda-quantum/pull/1973, these `.config` files were not run in the new location unintentionally.
=> Config file update legacy nvidia targets

tools/cudaq-qpud/json_request_runner.py
Follow-up to #1914.
Fix the fact that `cudaq.mpi.rank()` was being called after `cudaq.mpi.finalize()`.
This issue was discovered during QA testing on multi-GPU systems for the release, but given our current plans, this probably does not have to be backported to 0.8.0 since we are probably not enabling this remote Python feature in 0.8.0.
=> Follow-up to #1914 - fix MPI shutdown problem

docs/sphinx/using/backends/platform.rst
We've had these two `get_state_async` (py and cpp) examples added and tested for some time.
However, they were not included in the docs. Hence, this PR fixes that.
**Note**: the [linked issue](https://github.com/NVIDIA/cuda-quantum/issues/775) also mentioned layout/format/etc. since it's from a long time ago when we didn't use tabs throughout the docs to show C++ and Python examples. Since then, they have all been reorganized. 
Resolved https://github.com/NVIDIA/cuda-quantum/issues/775
=> Add `get_state_async` examples to the `mqpu` platform docs

.github/workflows/integration_tests.yml, .github/workflows/nvqc_regression_tests.yml
These changes should fix the failures seen here:
* https://github.com/NVIDIA/cuda-quantum/actions/runs/10345233900
* https://github.com/NVIDIA/cuda-quantum/actions/runs/10345205153
=> Exclude tutorial-specific Python files from integration tests and NVQC tests

lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/Quake/kernel_exec-1.qke, test/Quake/return_vector.qke
Use the cc.offsetof operation to reduce the size of the code.
~Requires #2082 be merged first.~
=> [core] Simplify autogenerated code.

include/cudaq/Optimizer/Transforms/Passes.h, lib/Optimizer/Transforms/ArgumentSynthesis.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, python/extension/CMakeLists.txt, runtime/common/BaseRemoteRESTQPU.h, runtime/common/BaseRemoteSimulatorQPU.h, runtime/cudaq/platform/default/DefaultQuantumPlatform.cpp, runtime/cudaq/platform/mqpu/custatevec/GPUEmulatedQPU.cpp, runtime/cudaq/platform/orca/OrcaQPU.cpp, runtime/cudaq/platform/qpu.h, runtime/cudaq/platform/quantum_platform.cpp, runtime/cudaq/platform/quantum_platform.h, targettests/execution/test-6.cpp, targettests/execution/to_integer.cpp, tools/nvqpp/nvq++.in
- Add option to nvq++ to use the new kernel launcher.
- Add code to the runtime to implement the new launch sequence. This receives the new vector of arguments protocol, uses the new argument conversion, and then calls the new argument synthesis pass to specialize the kernel for JIT compilation.
-  Add a couple of tests to smoke test this new implementation.
~Requires #2083 to be merged first.~
=> [JIT] Hook everything up to use the new argument synthesis

python/tests/remote/test_remote_code_exec.py
Crashing with a stack trace when trying to run the tests gives an impression that the code quality is poor.
=> [python tests] Skip the remote tests if modules are not installed.

runtime/common/BaseRemoteSimulatorQPU.h, runtime/common/BaseRestRemoteClient.h, runtime/common/RemoteKernelExecutor.h
=> Add hooks for remote launch to use argument synthesis.

lib/Optimizer/Transforms/WiresToWiresets.cpp
Multiple functions that allocate qubits will cause `assign-wire-indices` to produce duplicate `borrow_wire` ops (i.e., two `borrow_wire` ops with the same index). This change ensures that `assign-wire-indices` refuses to run on kernels with multiple functions to ensure that each `borrow_wire` is unique.
=> Make assign-wire-indices skip functions with calls

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Builder/Runtime.h, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Transforms/AggressiveEarlyInlining.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, runtime/common/ArgumentConversion.cpp, runtime/cudaq.h, runtime/cudaq/builder/kernel_builder.cpp, targettests/Kernel/signature-2.cpp, test/AST-Quake/tuple-0.cpp, test/AST-Quake/tuple-1.cpp, tools/cudaq-quake/cudaq-quake.cpp
A std::tuple can be laid out in memory either like a struct or like the reverse of a struct. We need to be able to detect which one of these schemes is being used and it depends on the C++ headers being used. (libstdc++ is reversed, while libc++ is like a struct.)
Update tests.
=> [core] Add dynamic tuple layout handling.

include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, include/cudaq/Support/Device.h, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/Mapping.cpp, lib/Optimizer/Transforms/RegToMem.cpp, lib/Optimizer/Transforms/WiresToWiresets.cpp, python/runtime/mlir/py_register_dialects.cpp, runtime/common/RuntimeMLIR.cpp, runtime/cudaq/platform/default/rest/helpers/iqm/iqm.yml, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.yml, targettests/TargetConfig/RegressionValidation/iqm.config, targettests/TargetConfig/RegressionValidation/oqc.config, targettests/execution/mapping_test-1-cpp17.cpp, targettests/execution/mapping_test-1.cpp, targettests/execution/mapping_test-2-cpp17.cpp, targettests/execution/mapping_test-2.cpp, targettests/execution/qspan_slices.cpp, test/Quake/wires_to_wireset.qke, test/Transforms/mapping_errors.qke, test/Transforms/mapping_non_unitaries.qke, test/Transforms/mapping_phased_rx.qke, test/Transforms/mapping_qspan.qke, test/Transforms/mapping_unitaries.qke, test/Transforms/mapping_with_meas-1.qke, tools/cudaq-opt/cudaq-opt.cpp, utils/CircuitCheck/UnitaryBuilder.cpp
This PR contains a collection of changes that were originally developed on the `features/qubit-mgmt` branch, but they have been isolated such that they can be merged into `main`, independent of that feature branch. The changes have not been previously reviewed, so they need to be reviewed just like normal in this PR.
* ~~Make the `add-wireset` pass add one `quake.wire_set` per function. The problem with the old approach of one per module is shown in a newly added test case (`test/Quake/wires_to_wireset.qke`). (The problem was that nested functions could borrow the same wire twice, which is not a good idea.) I backed these changes out.~~ Edit: Adam is going to make a separate PR to resolve the issue.
* Make the `qubit-mapping` pass operate on wires from a wire set rather than unnumbered …
=> Update the qubit mapping pass to use wire sets

test/Quake/wireset_codegen.qke
This contains updates to account for the `cc.cast` operations added in 454b7ef509d4065949ccadb20a8fd3e226743b30.
=> Update wireset codegen check data

python/runtime/cudaq/algorithms/py_state.cpp, python/runtime/utils/PyRemoteSimulatorQPU.cpp, runtime/common/BaseRestRemoteClient.h, runtime/cudaq/qis/remote_state.cpp, runtime/cudaq/qis/remote_state.h, targettests/Remote-Sim/state_overlap.cpp
- Use the new `vector<void*>` arguments for streamline launch in `remote_state`.
- For Python, previously, we pack `void*` into an `ArgWrapper*` primarily to send on the `mlir::ModuleOp`. In the new streamline launch approach, use the first element in `vector<void*>` to store `mlir::ModuleOp*`, i.e., the rest will be actual arguments.
=> [Kernel Launch] Remote state to use new launch mode

lib/Optimizer/Transforms/RegToMem.cpp, test/Quake/regtomem.qke
The regtomem pass has pretty limited applicability. It can, under the correct preconditions, recover the quantum reference semantics model. However, it could fail in the presence of control-flow, so was only reliable when the kernel was a single block.
This PR reimplements much of regtomem to make it work with control-flow and the CC dialect's IfOp.
Add a test. The pass will no longer raise a fatal error if the input is in a form that shares quake operations ambiguously between multiple qubits.
A note on borrow/return: running this pass on borrow/return will *not* preserve the semantics of that form. The map from the virtual reference domain to a borrow set is a surjective function. We make this a quasi-bijective function but re-resolving the scope of the borrow to be global. The extra …
=> Update regtomem to handle more cases.

runtime/cudaq/qis/qubit_qis.h, targettests/TargetConfig/check_disable_mlir_links.cpp, tools/nvqpp/nvq++.in
When compiling quantum device code for libraries, it is beneficial for one to be able to avoid direct linking to libcudaq-mlir-runtime and libcudaq-builder. If removing these links is not possible, and one tries to expose compiled device code to Python, they will hit the LLVM static initialization errors due to LLVM/MLIR being provided twice (once in the python cudaq module, and then again from the device library). 
This PR enables one to turn off those links with a compiler flag. This PR also fixes one of the exp_pauli signatures (add const to the pauli_word argument) to fix downstream compilation issues.
=> enable downstream libraries to turn off direct cudaq-mlir-runtime linking with nvq++

cmake/Modules/CMakeLists.txt, cmake/Modules/CUDAQConfig.cmake, cmake/Modules/NVQIRConfig.cmake, cmake/Modules/NVQIRConfig.cmake.in, python/cudaq/kernel/ast_bridge.py, python/runtime/common/py_SampleResult.cpp, runtime/nvqir/CircuitSimulator.h
* Create imported CMake targets for cudaq targets.
* Enable downstream CMake to set the target. 
* Fix bug where fmtlib not found for downstream project import NVQIR config.
* Fix issue printing out call error in python bridge.
* Add serialize / deserialize to sample result in python bindings.
* carry the custom operator name through to the GateApplicationTask.
=> Minor updates for downstream projects. 

lib/Optimizer/Transforms/RegToMem.cpp
This is a follow up to Ben's review. Thanks, Ben.
=> [follow up] Use llvm::any_of to reduce argument clutter.

docker/build/assets.Dockerfile, include/cudaq/Frontend/nvqpp/ASTBridge.h, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertType.cpp, targettests/Kernel/signature-2.cpp, test/AST-Quake/tuple-0.cpp, test/AST-Quake/tuple-1.cpp
for small structs.
In libc++, the compiler uses a "zero-cost" model of passing small struct values. In libstdc++, this was never fixed in order to maintain backwards compatibility with older compilers. So small structs are passed on the stack via references.  See https://tinyurl.com/bdhrkx9x for more information.
These patches fix nvq++ to adapt the calling convention to the header files in use at compile time.
=> [core] Fix calling convention differences between libstdc++ and libc++

docs/sphinx/examples/python/providers/photonics.py, docs/sphinx/examples/python/providers/photonics_tbi.py, python/cudaq/handlers/photonics_kernel.py, python/cudaq/kernel/kernel_decorator.py, python/runtime/common/py_ExecutionContext.cpp, python/runtime/cudaq/algorithms/py_state.cpp, python/tests/handlers/test_photonics_kernel.py, runtime/cudaq/qis/managers/photonics/PhotonicsExecutionManager.cpp
=> [Python] [photonics] Enable 'get_state' API 

lib/Frontend/nvqpp/ConvertExpr.cpp, test/AST-Quake/vector.cpp
=> [C++ bridge] Add support for std::vector::data method.

.github/workflows/integration_tests.yml
This should fix the NVQC nightly integration test failures.
=> Update NVQC testing deployment spec

lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, python/tests/mlir/adjoint.py, python/tests/mlir/conditional.py, python/tests/mlir/control.py, python/tests/mlir/ctrl_gates.py, python/tests/mlir/one_qubit.py, targettests/execution/cudaq_observe.cpp, test/AST-Quake/vector_bool.cpp, test/AST-Quake/vector_int-0.cpp, test/AST-Quake/vector_int-1.cpp, test/AST-error/vector.cpp
Allow the use of the move constructor so that cases such as
std::vector<int> vectorValue(N);
...
return vectorValue;
will compile and simple vectors of arithmetic types may be used.  Note that this requires the CUDA-Q runtime to actually return these values to the caller rather than dropping them on the floor after a launched kernel has deactivated.  That is not always the case, however, since some launchers do not expect any return value(s).
=> [C++ bridge] Add support for move constructor of std::vector.

docs/sphinx/using/extending/cudaq_ir.rst, include/cudaq/Optimizer/Builder/Factory.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Frontend/nvqpp/ConvertDecl.cpp, lib/Frontend/nvqpp/ConvertType.cpp, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/AggressiveEarlyInlining.cpp, lib/Optimizer/Transforms/GenDeviceCodeLoader.cpp, targettests/SeparateCompilation/pure_device.cpp, test/AST-Quake/ctor-2.cpp, test/AST-error/quantum_struct_declarations.cpp, tools/nvqpp/nvq++.in
The bridge wasn't adding all possible `__qpu__` functions to the list, so the call converter wasn't converting a pure device kernel call on the device side. This change fixes that bug, updates the call converter to be able to add any missing declaration(s), and adds a regression test.
=> Fixes a bug with separate compilation.

docker/build/assets.Dockerfile, include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/Builder/Factory.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/LiftArrayAlloc.cpp, targettests/execution/auto_kernel-cpp17.cpp, targettests/execution/auto_kernel.cpp, test/AST-Quake/calling_convention.cpp, test/AST-Quake/vector_int-1.cpp, test/Quake-QIR/return_values.qke, test/Quake/return_vector.qke
native calling conventions.
As support for more types is added, it is required that the host side code have the same calling conventions as the native clang++ compiler. Otherwise, programs will simply fail to execute correctly.
This is part 1. The launch kernel execution path is broken, and those bugs will be addressed in the next PR.
=> [core] Fix various bugs when processing the host-side functions and the

lib/Optimizer/Builder/Factory.cpp, test/AST-Quake/calling_convention-aarch64.cpp
Fix calling conventions for aarch64 and add a regression test.
Requires #2268 to be merged.
=> [core] Add support for aarch64 calling conventions.

python/tests/interop/quantum_lib/CMakeLists.txt
A bad rebase removed the add_dependency line for the quantum_lib test library. Add that back here.
=> ensure quantum_lib is built after nvq++ components are built

include/cudaq/Optimizer/Transforms/Passes.h, lib/Optimizer/Transforms/ObserveAnsatz.cpp, python/tests/interop/quantum_lib/CMakeLists.txt
Replace some data structures with LLVM ADTs for consistency.
=> [core] Refactor observe-ansatz pass.

docs/sphinx/api/languages/cpp_api.rst, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, lib/Optimizer/Transforms/LiftArrayAlloc.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/runtime/utils/PyRemoteSimulatorQPU.cpp, runtime/common/BaseRemoteRESTQPU.h, runtime/common/BaseRemoteSimulatorQPU.h, runtime/common/KernelWrapper.h, runtime/common/ThunkInterface.h, runtime/cudaq/platform/default/DefaultQuantumPlatform.cpp, runtime/cudaq/platform/mqpu/custatevec/GPUEmulatedQPU.cpp, runtime/cudaq/platform/orca/OrcaQPU.cpp, runtime/cudaq/platform/orca/OrcaRemoteRESTQPU.cpp, runtime/cudaq/platform/orca/OrcaRemoteRESTQPU.h, runtime/cudaq/platform/qpu.h, runtime/cudaq/platform/quantum_platform.cpp, runtime/cudaq/platform/quantum_platform.h, runtime/cudaq/qis/remote_state.cpp, targettests/execution/vector_result.cpp, test/Quake-QIR/argument.qke, test/Quake-QIR/return_values.qke, test/Quake/kernel_exec-1.qke, test/Quake/kernel_exec-2.qke, test/Quake/return_vector.qke
The launchers ceased really supporting dynamic kernel results at some point. This PR adds that functionality back into the mix. This support is added pervasively across the runtime library calls.
Some notes:
- Return values of static size continue to be supported as they were before. Specifically, these values are stored into the data buffer by the thunk adaptor so they can be returned, ultimately, to the original caller.
- Return values of dynamic size follow exactly 1 of 2 possible calling conventions. The convention must be selected by the runtime layers.
1. Everything is running within a single process; i.e., this is a simulation. In this case, the kernel will  create a span of data and that span will be returned to the original caller which will use it to construct the std::vector …
=> [core, runtime] Modify the launchers to support returning results.

docs/sphinx/using/extending/cudaq_ir.rst, tools/nvqpp/nvq++.in
Make the option match the clang++ option name. Having access to both just causes confusion and crashed the compiler.
=> Rename --save-temps option to -save-temps.

include/cudaq/Optimizer/Builder/Intrinsics.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Transforms/CMakeLists.txt, lib/Optimizer/Transforms/ConstPropComplex.cpp, lib/Optimizer/Transforms/GlobalizeArrayValues.cpp, lib/Optimizer/Transforms/LiftArrayAlloc.cpp, lib/Optimizer/Transforms/QuakeSynthesizer.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/runtime/mlir/py_register_dialects.cpp, runtime/common/ArgumentConversion.cpp, runtime/common/BaseRemoteRESTQPU.h, runtime/cudaq/platform/default/opt-test.yml, runtime/cudaq/platform/default/rest/helpers/anyon/anyon.yml, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.yml, runtime/cudaq/platform/default/rest/helpers/iqm/iqm.yml, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.yml, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.yml, targettests/Remote-Sim/qvector_init_from_vector.cpp, targettests/TargetConfig/RegressionValidation/anyon.config, targettests/TargetConfig/RegressionValidation/ionq.config, targettests/TargetConfig/RegressionValidation/iqm.config, targettests/TargetConfig/RegressionValidation/oqc.config, targettests/TargetConfig/RegressionValidation/quantinuum.config, test/AST-Quake/custom_op_concrete_matrix.cpp, test/Quake/lift_array.qke, tools/nvqpp/nvq++.in
Start changing core code over to use SmallVector (and be more compatible with MLIR) instead of std::vector.  Refactoring lifting of array values.  Implement globalize array values. Update new pass and pass names across all the config and yaml files.
Requires merge of #2277
=> [core] Refactor the lift array alloc pass into two proper phases.

docs/sphinx/targets/python/orca_mqpu.py
* Use the environment variable to access `orca` target resources so that the integration test can pick correct URL.
* Fix for the CI failure seen here: https://github.com/NVIDIA/cuda-quantum/actions/runs/11422958329/job/31794055039#step:12:57
=> [testing] [fix] Follow-up to PR#2260

python/runtime/cudaq/algorithms/py_state.cpp, python/tests/builder/test_cupy_integration.py
- The `std::vector<py::object>` overload overshadowed the `py::object` one as a cupy array object also implements Python array interface. Thus, it might be casted to a `std::vector<py::object>`. Fixed by using the Python type (`py::list`) instead.
- Add a check for cupy array input case: if the simulator is not GPU-based, throw an error. Previously, the pointer will be presented to the simulator anyhow, causing a segfault.
=> Fix issues with `state.from_data` bindings

.github/workflows/docker_images.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml
=> Add more GHCR login steps

docker/build/cudaq.dev.Dockerfile, docker/release/cudaq.wheel.Dockerfile
The incorrect tag in the default argument will prevent the dev container from properly working.
=> Fixing dev container

runtime/cudaq/qis/state.cpp, scripts/configure_build.sh
* cuTensor version upgraded to 2.0.2.5
* Bug-fix for issue introduced in PR #2289
Tested in local dev environment. 
```
100% tests passed, 0 tests failed out of 709
Label Time Summary:
gpu_required    = 348.95 sec*proc (374 tests)
```
=> Update the `cuTensor` version and fix state retrieval logic for `tensornet`

.github/workflows/docker_images.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, .github/workflows/python_wheels.yml, docker/build/devdeps.ext.Dockerfile, docker/release/cudaq.ext.Dockerfile, docker/release/cudaq.wheel.Dockerfile, docker/test/installer/runtime_dependencies.sh, runtime/cudaq/qis/state.cpp, scripts/configure_build.sh, scripts/validate_container.sh, scripts/validate_wheel.sh
Now that I finally can test the publishing, I needed to fix a couple of oversights in the previous updates to add the cuda 12 builds.
=> Packaging fixes

unittests/backends/anyon/AnyonStartServerAndTest.sh.in, unittests/backends/anyon/AnyonTester.cpp, utils/mock_qpu/anyon/__init__.py
Changed from '5000' to '62446' to match other targets' ports.
=> Change the test port for `anyon` target 

.github/workflows/config/gitlab_commits.txt
Bump mgpu commit to include a fix for `getNumElements` when host-device migration is used (mgpu MR!32).
The base implementation of `getNumElements` iterates over tensors, which is not supported for host-device migration (throwing an error). Hence, adding a direct `getNumElements` implementation.
This issue was exposed by a recent change in https://github.com/NVIDIA/cuda-quantum/pull/2289, which calls `getNumElements` as part of state data indexing. The bug and fix can be checked by the existing mgpu unit tests.
=> Bump mgpu gitlab commit

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/pull_request_template.md, .github/workflows/codeql.yml, .github/workflows/integration_tests.yml, .github/workflows/nvqc_regression_tests.yml, .github/workflows/publishing.yml, .licenserc.yaml
This will allow to configure the repo such that all publishing runs bypass rebuilding these assets.
=> Allow to define publishing assets as repo variable, disable codeql for C++, and fix issue in nightly workflows

.github/workflows/nvqc_regression_tests.yml
Excluding building_kernels from NVQC integration test
This will fix the NVQC integration test below
https://github.com/NVIDIA/cuda-quantum/actions/runs/11789940366/job/32839604580#step:4:1667
=> Excluding building_kernels from NVQC integration test

runtime/common/BaseRemoteRESTQPU.h
Instead of erroneously trying to copy a part of the moduleOp, clone the entire moduleOp so that any referenced artifacts are properly copied.
Fixes issue #2383.
=> Fix for issue #2383.

include/cudaq/Optimizer/Dialect/Quake/Canonical.h, include/cudaq/Optimizer/Dialect/Quake/Canonical.td, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.h, include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Optimizer/CodeGen/QuakeToCC.cpp, lib/Optimizer/CodeGen/QuakeToLLVM.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/CombineQuantumAlloc.cpp, lib/Optimizer/Transforms/FactorQuantumAlloc.cpp, python/cudaq/kernel/ast_bridge.py, python/tests/mlir/ast_compute_action.py, python/tests/mlir/ast_lambda_tuple_stmts.py, python/tests/mlir/ast_qreg_slice.py, python/tests/mlir/ghz.py, test/AST-Quake/adjoint-3.cpp, test/AST-Quake/custom_operations.cpp, test/AST-Quake/qpe.cpp, test/Quake/canonical-1.qke, test/Quake/invalid.qke
There was some technical debt with quake.subveq where constant operands were not folded into the operation like extract_ref and many others.
=> [core] Modify quake.subveq such that it folds constant arguments.

runtime/common/NoiseModel.cpp, runtime/common/NoiseModel.h
`NoiseModel.cpp` is having some dangling dependency on `host_config.h` (defining target-dependent data type).
This may cause data corruption when a `fp32` backend links to `libcudaq-common`, which is always compiled with fp64 config. 
In particular,
- A single instance of `validateCompleteness` is called in `.cpp` file -> the fix is to move it to the header.
- The `kraus_channel::parameters` is declared as a `host_config.h`'s `real` type. As we don't expect channels with a long list of parameters, I think it makes sense to just use `double` type instead. This prevents subtle issues with copy operators being implemented in `NoiseModel.cpp`.
=> Fix `NoiseModel` for single-precision backends

lib/Optimizer/Transforms/LoopUnroll.cpp, python/tests/mlir/control.py, test/Quake/memtoreg-7.qke
Fixes some technical debt wrt loop unrolling to allow it to be used as it was intended. That is, as a nested pass on func::FuncOp ops. Tunes the loop unrolling pipeline to use strictly nested passes for better locality and performance.
=> [core] Let loop unrolling be added as a nested func pass manager.

python/tests/backends/test_braket.py
Multiple qubit and qvector allocations and measurements are supported on the `braket` target with changes from PR# [2416](https://github.com/NVIDIA/cuda-quantum/pull/2416) . Hence, two of the tests pass, no longer raising error(s) - mark them as such.
=> [testing] Update passing tests

runtime/common/NoiseModel.h, runtime/nvqir/CircuitSimulator.h, unittests/integration/noise_tester.cpp
- Add "mz" to the list of allowed ops (for validation purposes) in `NoiseModel`.
- Query noise channels for `mz` and apply them accordingly similar to the way we retrieve and apply gate noises.
- Add a unit test.
=> Allow setting noise on measurement operation and apply it accordingly

python/tests/operator/integrators/test_evolve_dynamics_torch_integrators.py
Skip the 'test_evolve_dynamics_torch_integrators.py' tests if `torch` package not found.
=> [testing] Skip Python tests if dependency package missing

lib/Optimizer/Transforms/PassDetails.h
We missed this spot when `qtx` was absorbed into `quake`. 👻
=> [nvq++] Remove use of QTX.

python/tests/backends/test_Infleqtion.py, runtime/cudaq/platform/default/rest/helpers/infleqtion/infleqtion.yml
* `cu1`, `cu3`, `swap`, `cswap` are supported
* Remove the decomposition patterns no longer required
* Added test
=> Follow-up for the `infleqtion` target - drop redundant conversion patterns

docs/sphinx/using/backends/simulators.rst
=> Fix wrong parameters in docs for Fermioniq backend

docs/sphinx/applications/python/digitized_counterdiabatic_qaoa.ipynb, docs/sphinx/applications/python/hadamard_test.ipynb
* Fix for invalid notebook - hadamard_test.ipynb
* Remove explicit setting of target (default target is `nvidia` if GPU(s) present) - digitized_counterdiabatic_qaoa.ipynb
Address CI failures [here](https://github.com/NVIDIA/cuda-quantum/actions/runs/12283525967/job/34278485828?pr=2469).
Follow-up to PR# [2455](https://github.com/NVIDIA/cuda-quantum/pull/2455) and PR# [2467](https://github.com/NVIDIA/cuda-quantum/pull/2467)
=> Fixes for Python notebooks

runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cpp
The kron kernel performs an accumulation-type operation (not an assignment) on the result buffer. Hence, this buffer must be initialized.
https://github.com/NVIDIA/cuda-quantum/blob/5785e44256b757263879580c82cb84adc85bcf5a/runtime/nvqir/custatevec/CuStateVecCircuitSimulator.cu#L81
This issue only popped up intermittently if `cudaMalloc` returns a dirty buffer but can be observed reliably with `compute-sanitizer` (thanks @bmhowe23)
=> Fix uninitialized memory issue for the result buffer in kron call

.github/workflows/docker_images.yml, docs/sphinx/applications/python/divisive_clustering_src/main_divisive_clustering.py, docs/sphinx/applications/python/vqe_advanced.ipynb, docs/sphinx/examples/python/building_kernels.ipynb, docs/sphinx/examples/python/building_kernels.py, docs/sphinx/examples/python/executing_kernels.ipynb, docs/sphinx/releases.rst
Forgot to do that before...
Links to docs in notebooks and python files are generally suboptimal; there is no way for them to link to the correct docs version, so we need to necessarily direct them to the latest. The links are also not validated, and will break without anything failing if the page is removed in future versions on the docs. I don't have a better idea than to try and keep them somewhat general and unlikely to break.
=> Updating docs version index

lib/Optimizer/CodeGen/ConvertToQIRProfile.cpp
Make this static data structure constant for efficiency and to eliminate an initialization ctor.
=> Convert static variable to a constexpr.

docker/build/devdeps.manylinux.Dockerfile, scripts/build_llvm.sh
This PR fixes an LLVM discrepancy in our Docker images vs our Python wheels. This should fix #1421 and #1799 for our Python wheels. (The Docker images were already correct.)
| Platform  | Are CUDA-Q Python Wheels Sensitive to the [LLVM ARM Relocation Overflow](https://github.com/llvm/llvm-project/issues/71963)?  | Are CUDA-Q Python Wheels Sensitive to the [MLIR Region Simplification Bug](https://github.com/llvm/llvm-project/issues/94520)? |
| ------ | ------------- | ------------- |
| **x86_64**  | 🟢 --> 🟢 (already good)  | 🔴 --> 🟢   |
| **aarch64**  | 🔴 --> 🟢    | 🔴 --> 🟢   |
Just to complicate things even more than they already are, our 0.9.*, the Python wheels were already showing correct behavior for the exact test case in #1799. The exact reason is spelled out in the details of …
=> Apply LLVM customizations for Python wheel build

.github/workflows/docker_images.yml
Many of our deployment jobs have been failing, presumably due to running out of memory during the build process, e.g. https://github.com/NVIDIA/cuda-quantum/actions/runs/12759701909/job/35565063041
=> [ci] Update docker_images jobs to use more CPUs for build

runtime/nvqir/cutensornet/simulator_cutensornet.cpp, runtime/nvqir/cutensornet/tensornet_utils.h, unittests/CMakeLists.txt, unittests/mpi/tensornet_mpi_tester.cpp
`ScratchDeviceMem` allocates memory based on memory availability on construction. This mechanism is not compatible with multi-GPU code path (MPI execution), whereby the CUDA device is selected in the simulator constructor; hence we need to defer the allocation until the device is selected.
Fixed by having a separate `allocate` method to be called once during the simulator backend constructor after device selection.  
This bug was introduced in https://github.com/NVIDIA/cuda-quantum/pull/1865, where the scratch pad is allocated once (scratch pad is a member variable of the simulator class) rather than on-demand to improve performance.
Add a unit test for this case, to be executed when there are multiple GPUs.
=> Fix a bug in tensornet backend scratch pad allocation in multi-GPU mode

docs/sphinx/using/backends/simulators.rst, docs/sphinx/using/install/data_center_install.rst, docs/sphinx/using/install/local_installation.rst, docs/sphinx/using/quick_start.rst
New link: https://pypi.org/project/cudaq/
=> [docs] Update the link to Python wheels

runtime/cudaq/platform/quera/CMakeLists.txt, runtime/cudaq/platform/quera/QuEraBaseQPU.h, runtime/cudaq/platform/quera/quera.yml, targettests/quera/unsupported_arbitrary_kernel.cpp
As of CUDA-Q release version 0.9.1, the `quera` backend is supported only on Python frontend.
Prior to the changes proposed in this PR, if `quera` target was set from C++, it proceeded to use the default simulator and executed the circuit. With this change, an error will be thrown.
=> [quera] Fix C++ frontend behavior

targettests/quera/unsupported_arbitrary_kernel.cpp
Check if `quera` target is available - which in turn depends on `braket`
=> Follow-up to PR#2528: Make the newly added target test run conditionally

docs/sphinx/using/backends/simulators.rst, runtime/nvqir/cutensornet/simulator_cutensornet.cpp, runtime/nvqir/cutensornet/simulator_cutensornet.h, runtime/nvqir/cutensornet/tensornet_state.cpp, runtime/nvqir/cutensornet/tensornet_state.h, unittests/CMakeLists.txt, unittests/integration/observe_result_tester.cpp
- Restore the code path for computing expectation value by `cutensornetNetworkOperator_t`. This was removed in https://github.com/NVIDIA/cuda-quantum/pull/2397.
- Add an environment variable to select the two modes.
- Remove the state norm calculation.
=> [Tensornet] Update observe calculation

python/tests/backends/test_braket.py, runtime/common/BaseRemoteRESTQPU.h
Manually tested:
```
python3 -m pytest -rP python/tests/backends/test_braket.py
======================= 23 passed in 205.77s (0:03:25) =======================
```
Note: 
Following non-fatal error observed:
`loc("-":2:3): error: 'func.func' op Invalid number of binary-symplectic elements provided. Must provide 2 * NQubits = 0`
Will review this separately.
=> [braket] Add support for `observe` API

.github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/generate_cc.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml
This reverts commit 5ee448d2f901c4924b0a37ed26a52e516bc3a75f.
Since https://github.com/nv-gha-runners/vm-images/pull/113 has been merged, we can revert our temporary change.
=> Revert "[ci] Update runners to use -testing suffix for now (#2543)"

Building.md, scripts/build_cudaq.sh
This is needed for some build environments that have a high CPU-to-memory ratio because without this change, ninja spawns too many jobs, and the machine can run out of memory.
=> Add support for -j option for build_cudaq.sh script

.github/workflows/config/gitlab_commits.txt, runtime/common/NoiseModel.h
(1) Adding a const `enum` data member to `kraus_op`, which tracks the actual data type of the matrix at the point of construction.
This allows introspection when not all codes are compiled in the same compilation unit, e.g., our Python binding lib and the backend lib. 
Addressing https://github.com/NVIDIA/cuda-quantum/issues/2550
This issue only surfaced since https://github.com/NVIDIA/cuda-quantum/pull/2466, which adds an fp32 simulator backend that can handle noise.
(2) Update the downstream gitlab commit hash containing the corresponding change.
=> Add a precision `enum` to `kraus_op` to track the underlying data type

runtime/cudaq/qis/pauli_word.h
Missing `cstdint` header for `std::uint64_t`.
=> [rt] Add missing header.

runtime/nvqir/cudensitymat/CMakeLists.txt
When bulding the `cudensitymat` backend, finding this header is a requirment. The build will fail otherwise.
=> [rt] Add requirement to find `cudensitymat.h`

lib/Optimizer/Transforms/LoopAnalysis.cpp, test/Quake/loop_normalize.qke
Normalize loops with negative upper boundaries
Example of a loop that was not previously normalized and subsequently not unrolled
```
%1 = cc.loop while ((%arg0 = %c0_i32) -> (i32)) {
%2 = arith.cmpi slt, %arg0, %c-1_i32 : i32
cc.condition %2(%arg0 : i32)
} do {
...
```
Towards: https://github.com/NVIDIA/cuda-quantum/pull/2458
=> Normalize loops with negative upper bounds

runtime/cudaq/platform/default/rest/helpers/braket/braket.yml
This also fixes the following (non-fatal) error seen during 'observe' `error: 'func.func' op Invalid number of binary-symplectic elements provided. Must provide 2 * NQubits = 0`
(Ref: https://github.com/NVIDIA/cuda-quantum/pull/2539)
* Manually ran the Braket test suite.
```
root@87c14fc11e0a:/workspaces/cuda-quantum/build# python3 -m pytest -rP ../python/tests/backends/test_braket.py
...                                                                                                                                   
../python/tests/backends/test_braket.py .......................                                                                                  [100%]
================================= PASSES =====================================
...
====================== 23 passed in …
```
=> [braket] Add the `symbol-dce` pass to the lowering pipeline

python/cudaq/kernel/kernel_decorator.py
Not all objects that pass the `isinstance(var, type)` check have the `__annotations__` attribute.
This is a quick fix, i.e., the change does not address the much deeper underlying issue: this code should not be globing all globals within a frame, and perhaps using `__annotations__` is undesirable. (Also, the best practices regarding the use of annotations have changed in python 3.10, so there are still unaddressed landmines here.)
Fixes #2586 #2531 #2579
=> [py] Fixes #2586 and #2531 and #2579

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, python/tests/mlir/ast_elif.py, python/tests/mlir/ast_list_init.py, python/tests/mlir/ast_list_int.py, python/tests/mlir/ast_qreg_slice.py, python/tests/mlir/ghz.py, runtime/test/test_argument_conversion.cpp, test/Quake/arg_subst-3.txt, test/Quake/arg_subst-4.txt, test/Quake/arg_subst_func.qke, test/Quake/invalid.qke, test/Quake/kernel_exec-1.qke, test/Quake/kernel_exec-2.qke, test/Quake/return_vector.qke, test/Quake/roundtrip-ops.qke, test/Translate/return_values.qke
Fixes a typo in the syntax so that the argument order matches the type of the arguments.
Adds a verifier. Fix up the tests to reflect the changes.
=> [core] Some enhancements to the cc.insert_value op.

runtime/cudaq/algorithms/run.h
Once the decoder produces a buffer of values, as interpreted from the output log, one can use this function to convert to buffer into a std::vector<T> object. This function transfers the ownership of the data buffer to the vector instead of making another copy of the data.
=> [features/run] Add function to convert data buffer to a std::vector.

include/cudaq/Optimizer/CodeGen/Pipelines.h, lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/GlobalizeArrayValues.cpp, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/mlir/adjoint.py, python/tests/mlir/ast_elif.py, python/tests/mlir/ast_list_init.py, python/tests/mlir/ast_list_int.py, python/tests/mlir/ast_qreg_slice.py, python/tests/mlir/conditional.py, python/tests/mlir/control.py, python/tests/mlir/ghz.py, python/tests/mlir/measure.py, python/tests/mlir/swap.py, python/tests/mlir/test_output_qir.py, python/tests/mlir/test_output_translate_qir.py, runtime/common/Trace.cpp, runtime/cudaq/builder/kernel_builder.cpp, runtime/nvqir/NVQIR.cpp, test/Quake/OpenQASM/bugReport_641.qke, test/Quake/OpenQASM/callOp_380.qke, test/Quake/OpenQASM/topologicalSort_603.qke
Remove the python hooks to the old codegen. This exposes all the python problems in the tests.
Eliminate the expansion of python enumerate().
Remove use of empty labels for all measurements.
This eliminates a loop, a data structure, and the invalid mixing of quantum and classical data values in classical memory.
Fix bugs in AST bridge.
Fix https://github.com/NVIDIA/cuda-quantum/issues/2538 - measurement register name cannot be empty
Same code as in PR #2587
=> [core] enable the new QIR codegen for python

unittests/CMakeLists.txt
The `CUDAQ_BRAKET_RUNTIME_TEST_SOURCES` were set up to use `qpp` and simply re-running with a simulator. Appropriate
set of tests already covered in `unittests/backends/braket/CMakeLists.txt`. Hence removing these.
=> [testing] Clean-up unit tests

python/tests/backends/test_IQM.py, utils/mock_qpu/iqm/__init__.py
Found during the development of PR https://github.com/NVIDIA/cuda-quantum/pull/2567
=> [testing] Fix for IQM mock server when generating sample results

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, test/Quake/roundtrip-ops.qke
This op allows CC code to call a variadic function without having to prematurely convert all the arguments to LLVM dialect and clutter the code with casts. The LLVMIR dialect's LLVMFuncOp does allow us to declare a variadic function, however.
Use the new Op in the QIR codegen to prevent the LLVMIR verifier from whining about the use of LLVM types.
=> [core] Add call with vararg to CC dialect.

python/tests/backends/test_braket.py, runtime/cudaq/platform/default/rest/helpers/braket/BraketExecutor.cpp
Manually tested `test_braket.py`
```
python3 -m pytest -rP python/tests/backends/test_braket.py
================================================================== test session starts ===================================================================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0
rootdir: /workspaces/cuda-quantum
configfile: pyproject.toml
plugins: anyio-4.8.0
collected 24 items                                                                                                                                       
python/tests/backends/test_braket.py ........................                                                                                      [100%]
========================================================================= PASSES …
```
=> [braket] Follow-up to PR#2539: Add missing logic for processing sample results when using `observe` API

lib/Optimizer/Dialect/Quake/CanonicalPatterns.inc, python/tests/mlir/invalid_subrange.py
Add checks for invalid ranges on the input veq. If the ranges are constant and invalid, then turn the subveq operation into a poison value. If this value is not optimized away, then the user's code contains errors per the CUDA-Q Spec.
Add regression test.
=> Fix #2625: reduce invalid subvec operations to poison values.

python/cudaq/operator/integrators/cuda_torchdiffeq_integrator.py
Check if the installed pytorch is cuda aware.
This seems to only be an issue in the field on `aarch64` systems where the pytorch in the default pip repository is not cuda aware.
This is a code check of the warning described in https://nvidia.github.io/cuda-quantum/latest/using/backends/dynamics.html#numerical-integrators.
=> cuda_torchdiffeq_integrator.py: check if pytorch is built with cuda capabilities

docs/sphinx/using/backends/sims/noisy.rst, docs/sphinx/using/backends/simulators.rst
Ported from PR #2466
Follow-up to PR #2481
=> [docs] Restore the docs for trajectory noisy simulators 

lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp
Add output_name map when generating adaptive profile.
=> Fix for nightly tests.

.github/workflows/dev_environment.yml, .github/workflows/docker_images.yml, .github/workflows/generate_cc.yml, .github/workflows/gh_registry.yml, .github/workflows/integration_tests.yml, .github/workflows/prebuilt_binaries.yml, .github/workflows/publishing.yml, .github/workflows/publishing_stable.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml
[BuildKit v0.20.0](https://github.com/moby/buildkit/releases/tag/v0.20.0) was just released, and it is segfaulting for us, possibly due to this change:
> Embedded binfmt emulators in the release image have been updated to QEMU v9.2.0 https://github.com/moby/buildkit/pull/5695 https://github.com/moby/buildkit/pull/5736
Ref: https://github.com/tonistiigi/binfmt/issues/240#issuecomment-2675891118 and https://github.com/tonistiigi/binfmt/issues/240#issuecomment-2675900299
Note: this may or may not be related, but our GHA runners are currently pinned to an old kernel version due to https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/2096782. However, I have done prior testing using a newer kernel combined with QEMU v9.2.0, and it was not working on our runners.
Specific logs that were working …
=> Pin buildx/buildkit to v0.19.0 to fix qemu crashes during multi-platform build

runtime/common/NoiseModel.cpp, runtime/common/NoiseModel.h, runtime/nvqir/cutensornet/simulator_cutensornet.cpp, unittests/integration/noise_tester.cpp
In support of the upcoming simulator work that is related to https://github.com/NVIDIA/cuda-quantum/pull/2635, this PR performs some refactoring that will enable easier support of the additional incoming noise models.
The basic idea of this PR is to move some logic that was only in the `tensornet` simulators and move it into the common `NoiseModel` section of code. There were a few minor changes as a result of those moves. For review purposes, those important changes are isolated to 06c8cf203d39948efbbb3fa1bac81589a2244936. (It is still worth reviewing the other commits, too.)
Note: despite this being related to #2635, this can go in independently of that PR.
Note, since the per-PR CI does not test tensornet, I ran these local tests to verify correctness:
```bash
$ ctest -R NoiseTest
Test …
```
=> Refactor noise model for unitary mixtures

runtime/cudaq/qis/qubit_qis.h, test/AST-error/apply_noise.cpp
=> Make use of apply_noise with client/server targets emit an error.

include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/CodeGen/QuakeToLLVM.cpp, lib/Optimizer/Dialect/Quake/CanonicalPatterns.inc, lib/Optimizer/Dialect/Quake/QuakeOps.cpp, lib/Optimizer/Transforms/ApplyControlNegations.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, lib/Optimizer/Transforms/DecompositionPatterns.cpp, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/kernel_builder.py, python/tests/mlir/exp_pauli.py, runtime/cudaq/builder/kernel_builder.cpp, runtime/nvqir/NVQIR.cpp, test/AST-Quake/exp_pauli-1.cpp, test/AST-Quake/exp_pauli-2.cpp, test/AST-Quake/exp_pauli-3.cpp, test/AST-Quake/pauli_word.cpp, test/Quake/roundtrip-ops.qke, test/Transforms/DecompositionPatterns/ExpPauliToHRyRzCX.qke, test/Transforms/qir_base_profile.qke, test/Translate/exp_pauli-1.qke, test/Translate/exp_pauli-3.qke
These changes extend the quake.exp_pauli operation to be more fully functional like the other builtin quake operators.  This operator will now use a similar syntax, support adjoint, controls, etc.
Update the roundtrip test for syntax changes. Update tests. Add a new python regression test from the issue #2525.
=> Fix #2525: Make exp_pauli a fully functional operator.

.github/workflows/python_wheels.yml
An older version (4.0.5) of openmpi was being installed in the conda environment for redhat. This change bumps the minimum version to 5.0.7 which is the current latest version.
See: https://github.com/NVIDIA/cuda-quantum/issues/2623
=> .github/workflows/python_wheels.yml: bump openmpi version for MPI test

lib/Optimizer/Transforms/ObserveAnsatz.cpp, python/tests/backends/test_Ionq_LocalEmulation_kernel.py, python/tests/backends/test_Quantinuum_LocalEmulation_kernel.py, python/tests/kernel/test_kernel_features.py, targettests/execution/cudaq_observe_qvector.cpp, test/Quake/observeAnsatz.qke
Handle missing cases in ObserveAnsatz
- Handles veqs without ExtractRefOps in ObserveAnsatz` pass
- Add tests
Towards: https://github.com/NVIDIA/cuda-quantum/issues/2545
Closes: https://github.com/NVIDIA/cuda-quantum/issues/2662
=> Handle missing cases in ObserveAnsatz

docs/notebook_validation.py
The `docs/sphinx/applications/python/afqmc.ipynb` notebook has failures originating potentially from third-party libraries. This
issue is captured in #2577. While we work on a fix separately, this PR proposes to skip that specific notebook in validation stage to get rest of the CI pipeline to succeed.
=> [CI] Skip validation on an erroneous application notebook

.gitlab/workflows.yml
The tags for 'installer' are showing up as `$os` and `$perflab` instead of their values. 
Hence adding a matrix similar to the Docker image job (since that has correct tags).
=> [ci] Fix tags

python/tests/backends/test_braket.py, runtime/common/BraketExecutor.h, runtime/cudaq/platform/default/rest/helpers/braket/BraketExecutor.cpp, runtime/cudaq/platform/default/rest/helpers/braket/braket.yml
Increase default polling interval for Braket to 2000ms, and introduce a polling_interval_ms argument to make it user-configurable.
=> Update polling interval for Braket backend

.github/workflows/integration_tests.yml
* Follow-up to PR https://github.com/NVIDIA/cuda-quantum/pull/2665
* The syntax check tests are still getting skipped if one of the previous steps failed. See [here](https://github.com/NVIDIA/cuda-quantum/actions/runs/13578480396/job/37960023854) 
* Run it unconditionally.
=> [CI] Follow-up to PR#2665

runtime/cudaq/platform/orca/OrcaRemoteRESTQPU.h
The `resetExecutionContext` was previously a no-op, except for resetting the context, since no 'qubits' are involved in this job.
Recent changes check for presence of qubits and flag errors accordingly.
This change removes the invocation of that function. We reset the context in next line anyway.
Should fix the nightly integration test failures for `orca` seen [here](https://github.com/NVIDIA/cuda-quantum/actions/runs/13582771746/job/37971715501).
Manually tested by locally running all the nightly integration tests.
=> [orca] Skip unnecessary call and avoid error condition

.gitlab/workflows.yml
We don't want to populate full matrix.
x86 installer only on x86 and arm64 installer only on arm64.
Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-adding-configurations
=> [CI] Fix the asset creation for installer

python/cudaq/operator/integrators/cuda_torchdiffeq_integrator.py
Fix publishing error
```
RuntimeError: from_dlpack received an invalid capsule. Note that DLTensor capsules can be consumed only once, so you might have already constructed a tensor from it once.
```
Making from_dlpack compatible with both CuPy versions v13.4+ and v13.3 (and older).
=> Fix publishing error

docs/notebook_validation.py
This is to enable the publishing pipeline to pass. The test fails due to timeout.
See: https://github.com/NVIDIA/cuda-quantum/issues/2689
Failing pipeline: https://github.com/NVIDIA/cuda-quantum/actions/runs/13640844145/job/38132888363#step:5:1361
=> docs/notebook_validation.py: skip quantum_transformer.ipynb

docs/sphinx/targets/python/pasqal.py, docs/sphinx/using/backends/hardware/neutralatom.rst
In #2632 there were some left-over comments on the documentation from @efratshabtai. This PR attempts to address them.
[x] Discourage password in env var (https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974132495)
[x] Link to machine names (https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974133825)
[x] Up to date token link - Note, we will add a section on our docs too to make this clearer (https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974150935)
[x] Clarify the `cudaq.set_target` options (https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974162081)
[x] Typos in neutralatoms section (https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974170087 and https://github.com/NVIDIA/cuda-quantum/pull/2632#discussion_r1974170542)
=> Add documentation missing from #2632 initial pasqal integration

runtime/cudaq/distributed/builtin/activate_custom_mpi.sh
Check the compilation status in before setting the `CUDAQ_MPI_COMM_LIB` environment variable to ensure it is not set to an invalid value.
See: https://github.com/NVIDIA/cuda-quantum/pull/2691#discussion_r1982194213
=> Improve error handling in script to activate custom MPI

docs/sphinx/using/backends/hardware/neutralatom.rst, runtime/cudaq/platform/pasqal/PasqalBaseQPU.h, runtime/cudaq/platform/quera/QuEraBaseQPU.h
Local emulation is not yet supported on analog hardware targets like `pasqal` and `quera`. Prior to the changes proposed in this PR if user set `emulate=True`, it was ignored and proceeded as if the flag was not present. This change will throw an error.
=> Improve error handling for analog targets when local emulation is requested

.github/workflows/ci.yml, .github/workflows/config/validation_config.json, .github/workflows/docker_images.yml, .github/workflows/python_wheels.yml, .github/workflows/test_in_devenv.yml, docker/test/wheels/debian.Dockerfile, docker/test/wheels/fedora.Dockerfile, docker/test/wheels/opensuse.Dockerfile, docker/test/wheels/redhat.Dockerfile, docker/test/wheels/ubuntu.Dockerfile
Undoing some of the build changes I did in https://github.com/NVIDIA/cuda-quantum/pull/2705, and putting in what I hope should mitigate the issue we were seeing.
Keeps opensuse removed from validation (seems to be flaky regarding finding its repo currently - we can check back on that in a week)
=> Mitigating against network issues

scripts/validate_container.sh
Skipping non-dynamics examples for dynamics target
=> Skipping non-dynamics examples for dynamics target

python/tests/domains/test_qnn.py
On systems with more than 2 GPUs, we got this error
```
ValueError: array split does not result in an equal division
```
Hence, limit a maximum of 2 virtual QPUs to participate in this test.
=> Fix `test_qnn.py` for more than 2 GPUs

python/tests/kernel/test_explicit_measurements.py
Make the `braket` and `quera` Python tests conditional - run only if the target is available.
(Note: The `quera` target has a dependency on `braket`)
Addresses: https://github.com/NVIDIA/cuda-quantum/issues/2641
=> [testing] [Python] Fix issue#2641

runtime/cudaq/operators.h, runtime/cudaq/operators/boson_op.cpp, runtime/cudaq/operators/fermion_op.cpp, runtime/cudaq/operators/product_op.cpp, runtime/cudaq/operators/sum_op.cpp, runtime/cudaq/qis/execution_manager.h
This PR changes some of the operator functions to not use `std::move` when it is preventing Return Value Optimization, as that causes additional unnecessary processing.
=> Allow Return Value Optimization instead of forcing moves

.devcontainer/devcontainer.json
For those of us using VSCode dev containers, this makes the `psi-header` extension work with other projects that don't all have 2022 as a starting point. More specifically - with this change, the extension will attempt to retain the existing starting copyright year and update only the ending copyright year if it exists (rather than updating both the start copyright year and current copyright year).
Additionally, if the file is a new file, it will use "now" as the starting copyright year, which is more correct anyway.
Ref: https://github.com/davidquinn/psi-header
> A particularly useful case is yeartoyear(fc!P, now) to use file creation date for a new header, and then always keep the same from date no matter how the file migrates filesystems, version control systems, etc.
=> Dev Container psi-header extension: retain original copyright year

python/cudaq/handlers/photonics_kernel.py, python/cudaq/kernel/analysis.py, python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/captured_data.py, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/kernel_decorator.py, python/cudaq/kernel/quake_value.py, python/cudaq/kernel/register_op.py, python/cudaq/kernel/utils.py, python/cudaq/kernels/hwe.py, python/cudaq/operator/cudm_helpers.py, python/cudaq/operator/cudm_solver.py, python/cudaq/operator/cudm_state.py, python/cudaq/operator/definitions.py, python/cudaq/operator/evolution.py, python/cudaq/operator/expressions.py, python/cudaq/operator/helpers.py, python/cudaq/operator/integrator.py, python/cudaq/operator/manipulation.py, python/cudaq/runtime/observe.py, python/cudaq/runtime/sample.py, python/cudaq/runtime/state.py, python/cudaq/runtime/utils.py, python/cudaq/util/timing_helper.py, python/cudaq/visualization/bloch_visualize.py
Cleans up imports throughout the python runtime. I trie following the principles in [PEP8](https://peps.python.org/pep-0008/#imports).
The changes include:
* Grouping imports two blocks: external and internal, w.r.t cudaq.
* Not using relative paths when the module is in a parent dir (`..`)
* Not using wildcard imports
* Remove unused ones
=> [py][nfc] `import`s clean up.

.github/workflows/config/gitlab_commits.txt, docs/sphinx/using/backends/sims/svsims.rst
- Add an option to change the mgpu backend transfer buffer size and the corresponding doc.
- Add the doc for the option to enable/disable math mode emulation (fp32).
- Fix a bug in multi-process random seed initialization (in 0.10) - https://github.com/NVIDIA/cuda-quantum/issues/2760
- Initial state vector allocation optimization.
- Handle certain cases (relatively sparse Pauli operators) in host-device simulation at high memory utilization: https://github.com/NVIDIA/cuda-quantum/issues/2749. Adding a note in the docs regarding this use case.
=> Update mgpu sha and docs

python/metadata.cmake, scripts/build_cudaq.sh
Using lld instead of ld improves my link times when I make one small change and simply type `ninja` to rebuild. For example, some links would take ~10 seconds, and this improved it to ~2 seconds. This did not help _full-up_ builds in any significant way during my testing, but the improvement during the incremental builds still makes this worthwhile in my opinion.
=> Use lld for builds if available

.github/workflows/config/spelling_allowlist.txt, .licenserc.yaml, include/cudaq/Optimizer/CodeGen/OptUtils.h, lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/CodeGen/CMakeLists.txt, lib/Optimizer/CodeGen/OptUtils.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, runtime/common/RuntimeMLIRCommonImpl.h, targettests/execution/to_integer.cpp, test/AST-Quake/to_integer.cpp, tools/cudaq-translate/cudaq-translate.cpp
This brings in MLIR's `makeOptimizingTransformer` function under our control since the one built-in to MLIR does not allow us to disable vectorization. The reason this change is important is because no QIR-based targets support LLVM's vectorized intrinsics. Maybe they will in the future, but I haven't heard of that being on anybody's near-term roadmap, so it would be best to disable that for now.
For review purposes, see 592d632f02aa004ea67c47549e163f10d3f95ca3 for the custom changes to the MLIR `makeOptimizingTransformer` function. (612d198bbda8d093c6f583a5f71b49c0c2df0ce5 is just bringing the original files into our source tree.)
=> Remove vectorized instructions from LLVM IR for `cudaq::to_integer()`

lib/Optimizer/Transforms/ObserveAnsatz.cpp
Use of the pattern rewriter is not needed in this case because we are explicitly modifying the IR in this pass; we don't need any pattern folding capabilities here.
GitHub is showing the diffs strangely for this PR, so I will highlight what is actually changing by adding comments to the PR.
=> Change ObserveAnsatz pass to directly manipulate IR

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/Dialect/CC/CCOps.cpp, test/Quake/canonical-3.qke
=> [core] Add direct simplification of cc.if when condition is a constant.

scripts/build_cudaq.sh
Some environments (like our manylinux build environment that is based off of AlmaLinux) don't support things like `-fuse-ld=ld`. That is - even if `ld` is the system linker, the compiler doesn't support being told `-fuse-ld=ld`. This change omits setting CMake variables for cases like that, while still allowing the lld linker to be used in environments that support it.
This is needed for the CUDA-QX builds, which invoke the `build_cudaq.sh` script for the manylinux environment.
Example failure (before this PR): https://github.com/NVIDIA/cudaqx/actions/runs/14544697190/job/40808489265
=> Follow-up to #2809 - only set linker flags if environment supports it

lib/Optimizer/CodeGen/ReturnToOutputLog.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, test/AST-Quake/cudaq_run.cpp
calling all at once.
The original design of obliterating the return values from kernels wreaked havoc for the compiler. Because the signature of the kernel was being modified, the kernel became decoupled from what the C++ compiler expected, breaking things such as the library invocation template, device-side calling between kernels (which never expected a return value to simply vanish, memory leaks, etc.
All these issues will not happen if we simply acknowledge that the kernel has and should always have a C++ signature that is consistent. Returning a result from the kernel is left as part of the generated code. In addition the kernel will use the output logging functions to record the return values to a "file".
This means that on hardware, we will expect the controller to simulate the …
=> Change the design to support both cudaq::run calling and direct

lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp
=> Drop the result_record_output call when using cudaq::run.

python/runtime/cudaq/algorithms/py_sample_async.cpp, runtime/common/Future.h
There is an oversight in PR #2800, where we created a wrapper for the underlying `async_sample_result` type.
This type is directly exposed in other binding code paths, hence a binding is required for the underlying type.
Hence, refactoring the implementation to make the wrapper a proper trampoline class of the `async_sample_result`.
Also, add a virtual destructor to enable trampoline inheritance.
=> Restructure `AsyncSampleResult` binding

docs/sphinx/using/backends/sims/tnsims.rst, docs/sphinx/using/backends/simulators.rst, runtime/nvqir/cutensornet/mps_simulation_state.h, runtime/nvqir/cutensornet/mps_simulation_state.inc, runtime/nvqir/cutensornet/simulator_mps.h, runtime/nvqir/cutensornet/tensornet_state.h, runtime/nvqir/cutensornet/tensornet_state.inc
- Add docs for single-precision tensor network backends (related to https://github.com/NVIDIA/cuda-quantum/pull/2820)
- Expose the gauge option for MPS (a new option in cuquantum 25.03 release, which was not exposed https://docs.nvidia.com/cuda/cuquantum/latest/cutensornet/release-notes.html#cutensornet-v2-7-0) and the associated doc.
=> Update tensornet backend docs + expose MPS Gauge option (cuquantum 25.03 feature)

lib/Optimizer/Dialect/CC/CCOps.cpp
Adds a bit of documentation and refactors to physically partition the canonicalization patterns of two completely unrelated Ops that happen to use the same hook for convenience. (One of the Ops is defined in MLIR, so this adds a canonicalization pattern by letting it ride the coattails of another Op and evade security.)
=> Maintenance: refactor canonicalization patterns for clarity.

docs/sphinx/targets/python/pasqal.py, docs/sphinx/targets/python/quera_basic.py, docs/sphinx/targets/python/quera_intro.py
* Fixes for the `quera` and `pasqal` target examples to comply with the latest changes for operators.
* Should fix the failing nightly test for Pasqal. (Ref: https://github.com/NVIDIA/cuda-quantum/actions/runs/14787999707/job/41519909590)
* Manually tested
=> Follow-up to PR#2817: Update the user facing Python examples

docs/sphinx/targets/cpp/pasqal.cpp, docs/sphinx/targets/cpp/quera_basic.cpp, docs/sphinx/targets/cpp/quera_intro.cpp
* Follow-up to PR #2705 
* Update the analog target examples (`quera`, and `pasqal`) according to the spec
* Manually tested
```
{ 000:45 001:18 010:19 100:17 101:1 }
```
=> Follow-up to PR#2705: Update the C++ examples of analog targets

python/tests/dynamics/integrators/system_models.py
* Follow-up to PR #2817 
* Should fix the error -
`E   ModuleNotFoundError: No module named 'system_models'`
=> [Python] [testing] Restore the symbolic link to `system_models.py` from the `integrators`

docs/sphinx/examples/cpp/basics/noise_depolarization.cpp, unittests/integration/noise_tester.cpp
The depolarizing noise channel test used an incorrect `p` value to create a complete depolarizing channel. The check conditions are designed for a maximally mixed state.
This leads to test instability, especially for tensornet trajectory-based simulators, where the noise channel sampling doesn't support setting the random seed.
This relates to https://github.com/NVIDIA/cuda-quantum/issues/1813, for which we have updated the documentation accordingly.
=> [Testing] Fix noise channel test: use `p=0.75` for complete depolarizing channel

runtime/common/MeasureCounts.cpp
This is a regression since PR#2710.
Previously, `sample_result::expectation` would return 0.0 if the register name could not be found. 
In 2710, we changed it to a 'strict' version (`retrieve_result`), which throws.
This PR changes it back to a non-throw `try_retrieve_result` and returns 0.0 if not found.
This caused problems (exceptions) when observing an empty spin op, e.g., when distributing observe over more QPUs than the number of terms.
=> Gracefully handle expectation of an empty `sample_result`

unittests/backends/anyon/AnyonStartServerAndTest.sh.in, unittests/backends/braket/BraketStartServerAndTest.sh.in, unittests/backends/infleqtion/InfleqtionStartServerAndTest.sh.in, unittests/backends/ionq/IonQStartServerAndTest.sh.in, unittests/backends/iqm/IQMStartServerAndTest.sh.in, unittests/backends/oqc/OQCStartServerAndTest.sh.in, unittests/backends/quantinuum/QuantinuumStartServerAndTest.sh.in
Importing `cudaq` is taking a long time, especially in Debug builds. Since QA is doing some of their testing with Debug builds, we need to extend the timeouts for some mock server tests.
See nvbug 5268521.
=> Update mock server test timeouts

.github/workflows/integration_tests.yml
Follow-up to PR #2875 
* Fix the import statement in Python script.
* Update quotes for correct evaluation.
Manually tested in local environment as -
```
$ PASQAL_AUTH_TOKEN=$(python3 -c "from pasqal_cloud import SDK; import os; import sys; sdk = SDK(username=os.environ.get('PASQAL_USERNAME'), password=os.environ.get('PASQAL_PASSWORD')); sys.stdout.write(str(sdk.user_token()))")
$ export PASQAL_AUTH_TOKEN
$ bin/nvq++ --target pasqal  --pasqal-machine $PASQAL_MACHINE_TARGET ../docs/sphinx/targets/cpp/pasqal.cpp
$ ./a.out 
{ 000:52 001:14 010:19 100:15 }
```
Should fix the nightly integration test failure seen [here](https://github.com/NVIDIA/cuda-quantum/actions/runs/14963104309/job/42028329960#step:15:92).
=> [CI] [Testing] Follow-up to PR#2875

runtime/nvqir/NVQIR.cpp
The circuit simulator has a dedicated method for applying `phased_rx` operations. If we don't use it, then printing circuits that use this operation will incorrectly print them as "unknown op".
=> [nvqir] Fix handling of `phased_rx` gate.

lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, test/AST-Quake/adjoint-3.cpp, test/Quake/adjoint-2.qke, test/Quake/apply-1.qke
This pass was too presumptive about its ability to translate all quake apply ops into calls. Turning it into a greedy pass and turning the pass into a compositional pass without hard crashes. The intention being that this pass need not fail in the AOT compiler, but can be run at JIT time after argument synthesis to achieve the desired IR.
=> [core] Turn apply op specialization into a greedy pass.

docs/sphinx/using/examples/dynamics_examples.rst, python/runtime/cudaq/operators/py_boson_op.cpp, python/runtime/cudaq/operators/py_fermion_op.cpp, python/runtime/cudaq/operators/py_matrix_op.cpp, python/runtime/cudaq/operators/py_spin_op.cpp, runtime/cudaq/operators/sum_op.cpp
Concludes the fix for https://github.com/NVIDIA/cuda-quantum/issues/2437. 
Timing on my machine for the case reported in https://github.com/NVIDIA/cuda-quantum/issues/2437:
Version 0.8.0:
SpinOperator creation: 0.0391254186630249
cudaq.observe duration: 0.4048661708831787
Version with this PR:
SpinOperator creation: 0.015355110168457031
cudaq.observe duration: 0.2769707441329956
Edit: timing varies a bit though, and I've only run it a couple of times. All in all, comparable perf I'd say.
=> Fixing performance of the python bindings

lib/Frontend/nvqpp/ConvertExpr.cpp, lib/Optimizer/Builder/Intrinsics.cpp, test/AST-Quake/call_qpu.cpp, test/AST-Quake/qalloc_initialization.cpp, test/AST-Quake/vector_int-1.cpp
Entry-point kernels expect vector data to be deallocated properly by mechanisms in the kernel launch (such as code in the host-side entry point). However, device kernels were simply leaking the memory.  This patch fixes the memory leak for device kernel calls.
=> [core] Fix memory leak when device kernels return vectors.

docs/sphinx/examples/cpp/dynamics/heisenberg_model_mpi.cpp, python/cudaq/dynamics/cudm_solver.py, runtime/nvqir/cudensitymat/CuDensityMatOpConverter.cpp, unittests/dynamics/test_CuDensityMatTimeStepper.cpp
Follow up for https://github.com/NVIDIA/cuda-quantum/pull/2853
- Default integrator in case the optional integrator is not provided. This was an oversight when I re-wrote the `evolve_dynamics` body.
- Handle a constant (no operator) term in conversion. This was handled in the original Python operator conversion utility but not in the C++ implementation.
- Handle no-mpi environment for the new example.
- Remove a stale test case, as we have removed the unused `step_size` argument.
=> Fix publishing pipeline after dynamics migration to pybind11 binding

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, test/Transforms/DecompositionPatterns/ExpPauliToHRyRzCX.qke, test/Translate/cast.qke
The cc.func_ptr op has been around forever in the project but is no longer really needed as the dialects have evolved. This PR starts the process of making cc.func_ptr obsolete by making cc.cast a capable alternative.
Includes some reorgnization of the .td file.
=> [core] Start to make cc.func_ptr obsolete.

python/runtime/cudaq/dynamics/CMakeLists.txt
When invoking some Python checks hooked to cmake (ctest), we use the CUDA-Q Python package in build directory, not install directory. Hence, the path must be consistent.
Thanks, @khalatepradnya for spotting it!
=> Fix binary output directory of dynamics bindings to be compatible with using CUDA-Q python from build directory

runtime/cudaq/algorithms/evolve.h, runtime/cudaq/algorithms/evolve_internal.h, runtime/nvqir/cudensitymat/CuDensityMatContext.h, runtime/nvqir/cudensitymat/CuDensityMatEvolution.cpp
The input state to `evolve_async` may be constructed on a different device (GPU), as this state is built on the main thread before the async. functor is executed.
Hence, adding a helper function to detect and migrate the state data if needed.
=> Proper handling of `evolve_async` input state 

.github/workflows/repo_checks.yml
Due to the changes in PR #2929 , the spell checker is run on tests file as well. We want to skip those.
Use a separate configuration for formatter and spell checker
=> [CI] Skip `python/tests` directory in spell checker

docs/sphinx/examples/cpp/dynamics/qubit_dynamics_batched.cpp, docs/sphinx/examples/python/dynamics/cross_resonance.py, docs/sphinx/examples/python/dynamics/qubit_dynamics_tomography.py, python/cudaq/dynamics/cudm_solver.py, python/cudaq/dynamics/evolution.py, python/cudaq/dynamics/integrators/cuda_torchdiffeq_integrator.py, python/cudaq/dynamics/integrators/scipy_integrators.py, python/runtime/cudaq/dynamics/pyDynamics.cpp, python/tests/dynamics/integrators/test_evolve_dynamics_torch_integrators.py, python/tests/dynamics/system_models.py, python/tests/dynamics/test_evolve_dynamics.py, runtime/common/EvolveResult.h, runtime/cudaq/algorithms/evolve.h, runtime/cudaq/algorithms/evolve_internal.h, runtime/nvqir/cudensitymat/CuDensityMatEvolution.cpp, runtime/nvqir/cudensitymat/CuDensityMatExpectation.cpp, runtime/nvqir/cudensitymat/CuDensityMatExpectation.h, runtime/nvqir/cudensitymat/CuDensityMatOpConverter.cpp, runtime/nvqir/cudensitymat/CuDensityMatState.cpp, runtime/nvqir/cudensitymat/CuDensityMatState.h, runtime/nvqir/cudensitymat/CuDensityMatTimeStepper.cpp, runtime/nvqir/cudensitymat/CuDensityMatTimeStepper.h, unittests/dynamics/test_CuDensityMatExpectation.cpp, unittests/dynamics/test_CuDensityMatState.cpp, unittests/dynamics/test_CuDensityMatTimeStepper.cpp, unittests/dynamics/test_EvolveApi.cpp, unittests/dynamics/test_RungeKuttaIntegrator.cpp
Aggregate input states into a batch for more efficient cudensitymat simulation.
Note: We already had this API (list of states as initial states). Previously, we ran them sequentially. Now, we combine them into a batched state.
=> Support input state batching in dynamics `evolve`

docker/build/assets.Dockerfile, include/cudaq/Optimizer/Dialect/CC/CCOps.td, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/DeleteStates.cpp, lib/Optimizer/Transforms/GlobalizeArrayValues.cpp, lib/Optimizer/Transforms/StatePreparation.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, runtime/common/ArgumentConversion.cpp, runtime/cudaq/platform/default/opt-test.yml, runtime/cudaq/platform/default/rest/helpers/anyon/anyon.yml, runtime/cudaq/platform/default/rest/helpers/braket/braket.yml, runtime/cudaq/platform/default/rest/helpers/infleqtion/infleqtion.yml, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.yml, runtime/cudaq/platform/default/rest/helpers/iqm/iqm.yml, runtime/cudaq/platform/default/rest/helpers/oqc/oqc.yml, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.yml, runtime/cudaq/platform/fermioniq/fermioniq.yml, runtime/test/test_argument_conversion.cpp, targettests/TargetConfig/RegressionValidation/anyon.config, targettests/TargetConfig/RegressionValidation/ionq.config, targettests/TargetConfig/RegressionValidation/iqm.config, targettests/TargetConfig/RegressionValidation/oqc.config, targettests/TargetConfig/RegressionValidation/quantinuum.config, test/AST-Quake/custom_op_concrete_matrix.cpp, test/Quake/lift_array.qke, test/Quake/reify_span-2.qke, test/Translate/openqasm2_vector.cpp, tools/nvqpp/nvq++.in
For codegen, the pass must expand the `reify_span` macro operation into a collection of smaller step primitives and thereby eliminate the `reify_span` and (most likely) the constant array value as well. This adds a new test for the new production in the globalize-array-values pass.
Add argument conversion to use reify span.  Add tests for vector of vector.  Add constant-propagation pass to the pipelines. Fix tests and pipelines.
Requires #2953 be merged first.
=> [core] Add argument conversion and code gen components to constant propagate through spans

docs/sphinx/api/languages/cpp_api.rst, runtime/cudaq/boson_op.h, runtime/cudaq/fermion_op.h, runtime/cudaq/operators.h, runtime/cudaq/operators/boson_op.cpp, runtime/cudaq/operators/fermion_op.cpp, runtime/cudaq/operators/helpers.cpp, runtime/cudaq/operators/helpers.h, runtime/cudaq/operators/product_op.cpp, runtime/cudaq/operators/spin_op.cpp, runtime/cudaq/operators/sum_op.cpp, runtime/cudaq/spin_op.h, runtime/cudaq/utils/matrix.cpp, runtime/cudaq/utils/matrix.h, unittests/CMakeLists.txt, unittests/operators/boson_op.cpp, unittests/operators/fermion_op.cpp, unittests/operators/utils.cpp, unittests/operators/utils.h, unittests/spin_op/SpinOpTester.cpp
This PR
- Adds support for creating the multi-diagonal sparse matrix representation for spins, bosons, and fermions. The format is suitable for direct consumption by cudensitymat.
- Leverages the existing operator's `create_matrix` facility to construct the multi-diagonal representations.
- Implements a simple add function to compute the whole multi-diagonal representation for `sum_op`.
- Adds unit tests.
=> Support conversion from operators to multi-diagonal matrix representation 

python/runtime/cudaq/platform/py_alt_launch_kernel.cpp
Addressing https://github.com/NVIDIA/cuda-quantum/issues/2991
=> Fix for potential memory leak in launch kernel when exception is thrown

runtime/common/RecordLogParser.cpp, runtime/common/RunTheKernel.cpp, runtime/common/Timing.h
Use `CUDAQ_TIMING_TAGS=8`
Sample output:
```
$ CUDAQ_TIMING_TAGS=8 ./a.out 
[2025-06-04 17:22:28.605] - [tag=8] [RecordLogParser.cpp:14] RecordLogParser::parse executed in 0.255 ms.
[2025-06-04 17:22:28.605] [tag=8] [RunTheKernel.cpp:107] runTheKernel executed in 1836.06 ms.
```
=> Added timing tag for `run` API

python/cudaq/kernel/ast_bridge.py
PR #2956 change the way to print verbose messages. With multiple PRs changing the bridge around the same time, these statements ended up left behind.
=> [py] Remove wrong verbose prints in the bridge

python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/tests/interop/test_interop.py
Fix failing to get a python kernel function pointer
Cudaqx code uses `jitAndGetFunctionPointer` that passes a function name with `__nvqpp__mlirgen` prefix to `jitAndCreateArgs`, which in turn that expects the name without the suffix (the name was not used in case of getting a function pointer before `cudaq.run` implementation added a function lookup in the module).
For the purposes of getting the pointer we don't need the code creating the args from `jitAndCreateArgs`, just jit code is enough.
Moved out the jit code into `jitKernel`, updated `jitAndGetFunctionPointer` to use `jitKernel` instead.
=> Fix failing to get a python kernel function pointer

include/cudaq/Optimizer/Transforms/Passes.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, python/runtime/utils/PyFermioniqRESTQPU.cpp, python/runtime/utils/PyRemoteRESTQPU.cpp, runtime/cudaq/builder/kernel_builder.cpp
This updates the apply-op-specialization pass to be a "modern" MLIR pass as supported with more boilerplate code generation.
=> [core] Make apply specialization a modern MLIR pass.

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_direct_call_return_kernel.py, python/tests/kernel/test_run_kernel.py
Towards https://github.com/NVIDIA/cuda-quantum/issues/3013
Python counterpart for https://github.com/NVIDIA/cuda-quantum/pull/3010
=> [Python] Disallow returning `list` from CUDA-Q kernels for now

include/cudaq/Optimizer/Dialect/CC/CCOps.td, lib/Optimizer/CodeGen/CCToLLVM.cpp, lib/Optimizer/CodeGen/ConvertToQIRAPI.cpp, lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/GenKernelExecution.cpp, python/runtime/cudaq/platform/py_alt_launch_kernel.cpp, targettests/execution/trivial_inliner.cpp, test/Quake/kernel_exec-1.qke, test/Quake/return_vector.qke, test/Translate/return_values.qke
Fix #3037.
We generally want the inliner to be super aggressive and inline all calls everywhere. Except in the case where the thunk layer is calling the kernel proper. In that one instance, inlining must be prevented. The existing checks do a decent job of preventing this from happening in the typical case, but there were some cases (involving trivial kernels) that leaked through.
This adds a special NoInlineCallOp to fool the Inliner into thinking it can't perform the inlining.
=> [core] Workaround overly excitable MLIR inliner.

python/runtime/cudaq/algorithms/py_run.cpp, python/tests/kernel/test_direct_call_return_kernel.py, python/tests/kernel/test_run_kernel.py
Towards https://github.com/NVIDIA/cuda-quantum/issues/3013
=> [Python] [run] Disallow returing `list` from entry-point kernels only for now

python/tests/builder/test_cupy_integration.py, python/tests/builder/test_kernel_builder.py, python/tests/builder/test_qalloc_init.py, python/tests/builder/test_qalloc_init_state.py, python/tests/kernel/test_kernel_qvector_init.py, python/tests/kernel/test_state_kernel.py
cudaq.set_target('nvidia-fp64') has been deprecated since 0.8.
This commit mass updates these targets to the following:
```
cudaq.set_target('nvidia', option='fp64')
```
=> Mass update deprecated nvidia-fp64 target

runtime/common/RecordLogParser.cpp, unittests/output_record/RecordParserTester.cpp
The records log parser should not assume packed data layout - it leads to erroneous behavior.
=> [run] [parser] Throw error if missing data layout info when parsing struct / data class

lib/Frontend/nvqpp/ConvertDecl.cpp, test/AST-error/static_var.cpp
Kernels may not contain static and extern declared variables.
=> [C++ bridge] Emit an error for bad storage classes.

lib/Frontend/nvqpp/ConvertDecl.cpp, test/AST-Quake/unwind_return.cpp
Need to support a richer set of function signatures when adding the default func.return to a function which only has unwind_return ops.
=> [C++ bridge] Fix bug with injected func.return.

tools/nvqpp/nvq++.in
As the `nvidia` target configuration can pick up the closed-source `cusvsim-fp32` if available (in addition to the open-source `custatevec-fp32`), we need to set the `nvidia` target when choosing the default simulator.
This also matches the Python implementation, whereby we [selected](https://github.com/NVIDIA/cuda-quantum/blob/189f9bec98f081d899f8f923adb8e280d7a28d11/python/utils/LinkedLibraryHolder.cpp#L340) the default target by name. 
Related to https://github.com/NVIDIA/cuda-quantum/pull/1890, where we introduced the ability to match different lib files to the target based on availability.
=> Make sure that we also set the default target name in the `nvq++` driver script

include/cudaq/Optimizer/Transforms/Passes.td, lib/Optimizer/Transforms/Mapping.cpp, test/Transforms/mapping_errors.qke
This restores some of the error reporting functionality that was baked into the mapping pass. The user must explicitly set a flag to make these passes non-composable.
TODO: finish removing the non-compositional aspects of these passes in general.
=> Restore error reporting under non-composable option.

runtime/nvqir/CircuitSimulator.h
Closes #3088
Updates the wording for the warning given when a circuit simulator doesn't support noise.
=> [readability] Update warning for applyNoise

runtime/cudaq/qis/qubit_qis.h, runtime/cudaq/qis/qview.h, test/AST-Quake/slice.cpp
over qview types.
We were getting type checking errors when passing a qview to `mz` as there wasn't a proper overload.
Fix #3092.
=> [CUDA-Q] Extend the implementation to support measurements

lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Transforms/ApplyOpSpecialization.cpp, python/tests/mlir/exp_pauli.py, runtime/common/RuntimeMLIRCommonImpl.h, runtime/cudaq/platform/default/rest/helpers/ionq/ionq.yml, runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.yml, targettests/TargetConfig/RegressionValidation/ionq.config, targettests/TargetConfig/RegressionValidation/quantinuum.config, targettests/execution/grover.cpp, tools/nvqpp/nvq++.in
[core] Continue work on improving apply specialization.
We want to specialize and constant prop into apply callees. This constant prop should be used to convert the specialized callee into a DAG form. Also specialize any relaxed veq types while we're at it.
Adjust pipelines and such on Ionq and Quantinuum to allow for Grover example to JIT compile and execute.
Also tidy up the nvq++ driver a bit.
Add test.
=> Ties the various pieces together to allow the grover example code to compile and execute

.github/workflows/clean_up.yml
With ongoing experiments with deployments, cache has been getting overwritten frequently. This is an issue as cudaqx needs devdeps images.
The max cache size is 10GB.
I don't recall seeing any warnings of us nearing cache limits, so this should be fine. Github will warn and automatically evict older manifests if it reaches the cache limit anyways.
=> Update untagged manifests limit from 200 to 400

python/cudaq/kernel/ast_bridge.py, python/cudaq/kernel/captured_data.py, python/cudaq/kernel/kernel_builder.py, python/cudaq/kernel/quake_value.py, python/cudaq/kernel/utils.py, python/runtime/mlir/py_register_dialects.cpp, python/tests/mlir/bare.py
This commit updates argument ordering in several type retrieval functions, e.g., `cc.PointerType.get(...)`. The current ordering is different from MLIR's core IR one. More importantly, however, is the fact that our current ordering adds awkwardness and prevents supporting the composability of function arguments. For example, `cc.PointerType.get`, requires `Context` as the first argument, even when using a context manager.
In Python, trailing keyword arguments to the right are the most composable, enabling a variety of strategies such as kwarg passthrough, default values, etc. Thus, keeping function signatures composable can reduce boilerplate in IR construction. Indeed, by being consistent here, we can avoid most needs for explicit contexts, locations and insertion points when building …
=> [py] Update bindings to follow MLIR arg ordering.

runtime/common/RestClient.cpp
Updating cpr seems to have broken our homebrew gzip decompression, likely because cpr handles that transparently now.
https://github.com/NVIDIA/cuda-quantum/commit/b89969d4c2a258a01fa3cd0ba37302eccdec141d
This essentially reverts https://github.com/NVIDIA/cuda-quantum/commit/ad164b9089f25928979289aab5de3bfcc8319b3d which is no longer needed.
Manually verified with the following script:
```
nvq++ -v bug_qubit.cpp --target ionq
./a.out
```
(`IONQ_API_KEY` env var is necessary to run the above)
Before this PR, it throws an error:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  Exception during zlib decompression
Aborted (core dumped)
```
Printing the payload given to `decompress_gzip` shows it is, in fact, not gzip encoded, even though the `Content-Encoding` …
=> Remove homebrew gzip decompress

lib/Optimizer/CodeGen/Pipelines.cpp, lib/Optimizer/Transforms/DeadStoreRemoval.cpp, python/tests/backends/emulateInfleqtion.py
The OpenQASM assembly format does not support exp_pauli nor the string data type.  This requires that (1) the exp_pauli operations are decomposed and (2) residual string literals are cleaned up.
This PR addresses these issues and adds a regression test for Python.
=> [OpenQASM] Fixes the OpenQASM2 backend for use with exp_pauli.

.gitlab/workflows.yml
Allow failure was on, this could lead to interesting scenarios where publishing thinks everything is okay and continues on when waiting for assets. This caused an issue recently when doing the native ARM build where the python wheel name changed, and so the assets were just a text files, and no shared libraries were provided.
=> Do not allow failure for Python Wheels,Installer,Docker Image

.gitlab/workflows.yml
Add set -x to the loop logic so gitlab doesn't minimize the output.
add a debug statement for the wheel being installed to make sure the glob matching worked.
=> Python Wheels: Add additional debugging information

.gitlab/workflows.yml
The Installer portion has been failing for a while. I manually confirmed the assets files are available, and they should be good. The downstream installer tests are also happy.
Let's re-enable allow failure for now.
The issue is that it tries to use the same sha256 for both amd64/arm64:
```
Pulling docker image ghcr.io/nvidia/cuda-quantum-assets@sha256:a8c3e8564fbffe120a4547d70ab31563a65c9b552fd9a9cec00394f85a6284b8 ...
WARNING: Failed to pull image with policy "always": no matching manifest for linux/arm64/v8 in the manifest list entries (manager.go:251:0s)
```
Whereas the manifest looks like this:
```
$ docker buildx imagetools inspect ghcr.io/nvidia/cuda-quantum-assets@sha256:a8c3e8564fbffe120a4547d70ab31563a65c9b552fd9a9cec00394f85a6284b8              
Name: …
```
=> Allow Installer failure

python/runtime/cudaq/algorithms/py_run.cpp, python/tests/remote/test_remote_platform.py, runtime/common/RunTheKernel.cpp, runtime/cudaq/algorithms/run.h, targettests/Remote-Sim/cudaq_run_async.cpp
Propagate `qpu_id` so it can be set correctly on the platform
=> [run] [bug-fix] Asynchronous API requires proper handling of QPU ids

.github/workflows/deployments.yml, .github/workflows/docker_images.yml, .github/workflows/publishing.yml, docker/build/assets.Dockerfile, docker/build/devdeps.ext.Dockerfile, docker/build/devdeps.manylinux.Dockerfile, docker/release/cudaq.ext.Dockerfile, docker/release/cudaq.wheel.Dockerfile, docker/test/installer/runtime_dependencies.sh, pyproject.toml, runtime/nvqir/cudensitymat/CMakeLists.txt, runtime/nvqir/cudensitymat/CuDensityMatContext.cpp, runtime/nvqir/cudensitymat/CuDensityMatOpConverter.cpp, scripts/configure_build.sh, unittests/CMakeLists.txt
- Remove dependency to cuquantum-**python**, just the binary distribution.
**Note**: cuquantum-python 25.06 no longer supports Python 3.10.
- Add cusparse dependency. This is a new dependency of cudensitymat.
- Fix cudensitymat API usage according to the new version, need the new gradient callback param.
- Modify the dynamics CMake to check cudensitymat version as the code is no longer compatible with the previous version.
- Workaround spurious error log (related to synchronization) from cudensitymat during shutdown. We will look into the issue later. This occurs during the final shutdown, hence it is safe to ignore for the time being.
- Fix a typo in audit-wheel exclude: cusolver doesn't follow the cuda version, e.g., it has version 11.7 in CUDA toolkit 12.x …
=> Update to cuquantum 25.06

python/tests/parallel/test_mpi_mqpu.py, python/tests/parallel/test_mqpu.py
When running the full test suite, the `nvidia-mqpu` target might be initialized without any actual QPUs being available. With the fix in PR #3163, this throws error instead of silently failing. Updating the tests to check QPU availability before proceeding. 
Note - these tests don't fail if run in isolation.
Fixes following crash when running full Python test suite:
```python/tests/parallel/test_mpi_mqpu.py::testMPI Fatal Python error: Floating point exception```
=> [testing] [Python] Follow-up to PR#3163

.github/workflows/deployments.yml
we have:
```
DIGESTS_JSON:
{
"digest": {
"arm64-cu11.8-image": "sha256:a76f90f777b8c18c78e6e4cfcfe2544422b1e7ab3fd38490d60097523a4d3771",
"arm64-cu12.0-dev-image": "sha256:0857505fab3a625c62134f0d1ed09db08030e0c7bd68809c732d7c8608c15b3e",
"arm64-cu12.0-image": "sha256:05c2d2aa62b27d5c5d850b9bdb29b25c4895b730f4935d33d9851b8a79e12382",
"amd64-cu11.8-dev-image": "sha256:01651c6401a4a0d6cff7678ce926dd699d56e4655ac097adc9167081f01b7334",
"arm64-cu11.8-dev-image": "sha256:6a70316f0b6c3a0c246ce7c7de792d28869591c027fa8abfaea89260f2fc52c7",
"amd64-cu11.8-image": "sha256:6709a4c2b8176c839f43e68924198cfd729f4b19ea693ffb72f3244e48d6b70c",
"amd64-cu12.0-dev-image": "sha256:a3fcfd79d57ab806eb50cecbfe4f1442c4cfff9f9ac5f846bd9036d72632fb7a",
"amd64-cu12.0-image": …
```
=> deployments: also stitch devdeps

.github/workflows/deployments.yml
This will produce a devdeps image at
http://ghcr.io/nvidia/cuda-quantum-devdeps:ext-cu12.0-gcc11-main
Like it was before. The incorrect key was used previously, publishing the regular devdeps image, not ext.devdeps. This now publishes ext.devdeps with the extra dependencies such as cuQuantum, cuTensor, and the CUDA packages necessary.
Removes stitching the development dependencies image, as no one consumes that tag, and the build pipeline uses hashes instead.
=> Fix devdeps tag, remove regular devdeps as unneeded

docs/notebook_validation.py
I tested like so:
```
$ docker run --rm --gpus all --network host -it nvcr.io/nvidia/nightly/cuda-quantum:cu12-latest-base
$ git clone https://github.com/mitchdz/cuda-quantum.git -b main
$ cd cuda-quantum/docs
$ echo "nvidia" | python3 notebook_validation.py
::warning::Skipped validation for the following notebook(s):
quantum_transformer.ipynb unitary_compilation_diffusion_models.ipynb
```
=> Skip unitary compilation diffusion models

python/runtime/cudaq/algorithms/py_sample_async.cpp, python/tests/builder/test_NoiseModel.py
This reverts commit f8415288570c32ca1db90e429a46856da07b74a8.
=> Revert "[Python] Expose noise model to the asynchronous sample API (#3054)"

.github/workflows/deployments.yml
When creating a release branch for example, the tag is `releases/v0.12.0`. This breaks because you can not have slashes in the docker tag.
This updates the tag to pull it from the JSON files created from `docker_images.yml` and strips away the arch tag.
To help with reviewing this PR, DIGEST_JSON looks like this:
```
{
"digest": {
"arm64-cu12.0-image": "sha256:b225393b9a8baf7ba1e6e6a1cc9096b0b03eba1b669bf0774b6a6e73d6ffa68c",
"arm64-cu12.0-dev-image": "sha256:9488561a700173b6ddebd09a03ce923e30ebfb44adf8afd38bcfb1b86d2bac45",
"arm64-cu11.8-dev-image": "sha256:06c3c7dd943ba7911f6e51a7b82c31e46015b60db664692ade3e278acc1d2228",
"arm64-cu11.8-image": "sha256:f327b06340617c8d5d6b0a18ebe0f1daa13c045e7866992281a5fa2d29458387",
"amd64-cu11.8-image": …
```
=> Sanitize tag in deployments stage

include/cudaq/Frontend/nvqpp/ASTBridge.h, include/cudaq/Optimizer/Transforms/Passes.td, lib/Frontend/nvqpp/ASTBridge.cpp, lib/Optimizer/Builder/Intrinsics.cpp, lib/Optimizer/Dialect/CC/CCOps.cpp, lib/Optimizer/Transforms/EraseVectorCopyCtor.cpp, lib/Optimizer/Transforms/MemToReg.cpp, lib/Optimizer/Transforms/VariableCoalesce.cpp, test/AST-Quake/compute_action-2.cpp, test/AST-Quake/qpe.cpp, test/AST-Quake/vector_vector.cpp, test/Quake/canonical-1.qke, test/Quake/coalesce.qke, test/Quake/erase_vcc.qke, test/Quake/memtoreg-6.qke
Guard against nullptr.
Fix bug in memtoreg. When an entry block has no definitions other than from within an enclosed Region, the live-in set must be promoted to block arguments, since there is no dominating Block in the Region.
Add checks to verify that variable-coalesce is run as a FuncOp pass.
Add hoist-only option.
Fine tune canonicalization of cc.scope.
=> Misc. bug fixes and improvements.

.github/workflows/deployments.yml
release refactoring https://github.com/NVIDIA/cuda-quantum/commit/50510ffb8adf6434db9f4794c4ec1e9a64dae708 accidentally removed the registry from devdeps, which is still needed for the publishing metadata.
=> Add missing registry to devdeps publishing data

runtime/common/Future.cpp, runtime/cudaq/platform/default/rest/helpers/quantinuum/QuantinuumServerHelper.cpp
- Populate the sub-register results (indexed by register names) in the `sample_result`.
- Update the token expiry duration to 5 minutes.
- Update the result polling loop to check cookies during the loop, as the cookies may have expired while waiting.
=> Support parsing register names and populate the `sample_result`

.github/workflows/publishing.yml
We have seen strange behavior in CI that is not reproducible locally.
The error is:
```
./a.out: error while loading shared libraries: libcublas.so.12: cannot open shared object file: No such file or directory
```
e.g. https://github.com/NVIDIA/cuda-quantum/actions/runs/16464800187/job/46543007819
There is a theory that installing cublas first will fix this.
=> Try installing cublas first

.github/workflows/docker_images.yml
Finished test - https://github.com/NVIDIA/cuda-quantum/actions/runs/16523873753/job/46735217782
Tested `test_native_arm` branch to make sure the manifest looks good for regular images -
```
$ cudaq_image=ghcr.io/nvidia/cuda-quantum@sha256:3d91d5e2efda119a44b5a5b2aad08b341f5eaf1b116b21c48daea87ae5cb2244
$ docker inspect $cudaq_image --format='{{json .Config.Labels}}' | jq -r '."org.opencontainers.image.version"'
amd64-cu11-test_native_arm-base
```
This is attempting to fix the releases image. Due to how releases works, it pulls the docker container and then looks at `org.opencontainers.image.version` from `docker inspect`.
Which causes it to be:
```
$ base_tag=`docker inspect $cudaqbase_image --format='{{json .Config.Labels}}' | jq -r '."org.opencontainers.image.version"'`
$ echo $base_tag …
```
=> docker_images: pull is_versioned for all images

runtime/cudaq/platform/default/rest/helpers/quantinuum/quantinuum.yml, targettests/TargetConfig/RegressionValidation/quantinuum.config, test/AST-Quake/bug_3270.cpp
Addresses issue #3270 
Follow-up to PR #3130 
The order of passes should be - expand measurements, loop unrolling and then update register names (the last two are part of classical optimization pipeline).
=> [bug-fix] Restore the pass to expand measurements for `quantinuum` target

lib/Frontend/nvqpp/ConvertDecl.cpp, test/AST-Quake/separate_compilation.cpp
Add code in the bridge to translate calls to host-side entry-point kernels directly into device-side calls in the bridge. This is meant to prevent exposing mysterious calling convention failures to the user.
Fixes #3239
=> [C++ bridge] Fix for issue 3239

.github/workflows/ci.yml
Build Python 3.11 as the minimum version for CI, since we now build Python 3.13 and will drop 3.10 soon.
=> ci: bump python 3.10 -> python 3.11

.github/workflows/config/ghcr_config.json, .github/workflows/config/validation_config.json, docker/test/wheels/fedora.Dockerfile, docs/sphinx/using/install/data_center_install.rst, docs/sphinx/using/install/local_installation.rst
We are seeing network errors with Fedora:39 https://github.com/NVIDIA/cuda-quantum/actions/runs/16786910932/job/47541785386?pr=3309#step:6:67
Fedora:39 has been EOL for almost a year. Update our runners to use a supported version.
Also, remove suggestion for supported on Fedora:38/39 and update to Fedora:41
Upstream fedora bug - https://discussion.fedoraproject.org/t/error-504-404-when-updating-fedora-39/161798/2
=> Bump to Fedora:41 as Fedora:38/39 are EOL

.github/workflows/config/ghcr_config.json
Fedora 42 is out as the latest version, and so is redhat10.
Fedora always has a 13 month cadence to EOL versions. Fedora 41 will EOL this year, 2025 on November 19th[0].
[0] - https://fedorapeople.org/groups/schedule/f-41/f-41-key-tasks.html
=> Cache Fedora 42 && redhat10

python/tests/dynamics/integrators/test_evolve_dynamics_torch_integrators.py, python/tests/dynamics/system_models.py, python/tests/dynamics/test_evolve_dynamics.py, runtime/nvqir/cudensitymat/CuDensityMatCallbackConverter.cpp, runtime/nvqir/cudensitymat/CuDensityMatOpConverter.cpp, runtime/nvqir/cudensitymat/CuDensityMatOpConverter.h
The wrapper for the tensor callback shouldn't use the `mode_extents` callback arguments as the dimension map, as it was referring to the extents of the tensors, not the sub-systems' dimensions.
Hence, add the dimension map, which is required by `op.to_matrix`, to the wrapper context.
Adding test cases based on bug reports.
Resolved #3326
=> Fix bug#3326: tensor wrapper needs to use global dimension map

.github/workflows/config/ghcr_config.json
The CI currently uses the following versions:
* redhat/ubi8:8.0
* redhat/ubi9:9.2
`8.0` and `9.2` is EOL.[0]
Update to use the latest tags which will be supported until 2029 for `8.10` and 2027 for `9.6`. This PR just adds the newest tags so they can be tested in a future PR. Once the old tags are not being used, they will be removed.
[0] - https://access.redhat.com/support/policy/updates/errata
=> Cache redhat/ubi8:8.10 and redhat/ubi9:9.6

runtime/nvqir/cutensornet/tensornet_state.inc
This Flops info is exposed by cutensornet and could be useful to assess the optimality of the contraction path, e.g., to debug runtime variation.
=> [Logging] Log tensornet expectation calculation Flops as info

lib/Optimizer/Transforms/QuakePropagateMetadata.cpp, python/tests/kernel/test_sample_kernel.py, test/Transforms/propagate_metadata_apply.qke
* Update the pass to propagate quake metadata to be skipped if the module has `quake.apply` instruction.
* The pass is expected to be called again in the QIR pipeline by the time apply specialization and other passes have been run.
https://github.com/NVIDIA/cuda-quantum/issues/2830
=> Addressing issue# 2830

python/cudaq/kernel/ast_bridge.py, python/tests/kernel/test_cast_kernel.py
Follow-up to PR https://github.com/NVIDIA/cuda-quantum/issues/3084
Operand type conversion when dealing with arithmetic operations like `add`, `sub`, `mult` and `div`, should not demote floating point type to integer types.
Note that demotion is allowed when dealing with return types - which is explicitly specified by the type.
Renaming the function because `promoteOperandType` is a misnomer. Also added a flag to allow / disallow demotion of operand types.
=> [Python] [bug-fix] Incorrect operand type conversion for some arithmetic operations

python/cudaq/kernel/captured_data.py, python/cudaq/kernel/kernel_builder.py
Before this fix, using Python kernel builder in docker image for released version 0.12.0 gave following error message at end of execution.
```
cudaq@48488c09e93b:~$ python3 test.py
Exception ignored in: <function PyKernel.__del__ at 0x7d2125e643a0>
TypeError: 'NoneType' object is not callable
Exception ignored in: <function CapturedDataStorage.__del__ at 0x7d2125e1b010>
TypeError: 'NoneType' object is not callable
```
Note that the results were not affected. But, this is a nuisance message and should be removed.
=> [Python][builder mode] Replace `__del__` methods with `weakref.finalize`

.github/workflows/config/validation_config.json
ubi8 was mistakenly added to the validation for python3.10.
ubi8 does not have python3.10 in the repository available for download, thus deployments will fail when attempting to do the full verificaiton.
See https://github.com/NVIDIA/cuda-quantum/actions/runs/16979068912/job/48136131947#step:6:90
=> Remove ubi8 from validation python3.10

python/metapackages/setup.py
For now, cuda 13 is not built. Fall back to cuda 12.
Fixes https://github.com/NVIDIA/cuda-quantum/issues/3354
=> setup.py: fall back to cu12 when CUDA 13 is detected

runtime/cudaq/algorithms/evolve.h, runtime/nvqir/cudensitymat/CuDensityMatSim.cpp, unittests/mqpu/dynamics_async_tester.cpp
We are using `set_exec_ctx` as a mechanism to set the GPU ID for `evolve_async`, as it doesn't perform a kernel launch. 
This was not properly `reset` afterward. Hence, adding the missing `reset_exec_ctx` calls.
The CudensityMat simulator handles (ignores) execution context resets, as the base implementation involves circuit simulation logic, such as qubit deallocation.
Adds a test for `evolve_async` to cover the `super_op` overload.
=> Add missing `reset_exec_ctx` call in `evolve_async`

tools/nvqpp/nvq++.in
This enables variable coalescing by default in the driver.
=> Enable variable coalescing by default.

python/cudaq/kernel/kernel_builder.py, python/runtime/common/py_NoiseModel.cpp, python/tests/builder/test_NoiseModel.py
- Add missing support for `apply_noise` in Python builder mode.
- In builder mode, as we have full access to the surrounding Python context, we support inline noise applications of Kraus matrices. This is to support this [feature request](https://github.com/NVIDIA/cuda-quantum/issues/3116), e.g., translating from cirq to cudaq via builder mode.
- Add tests.
Fixed https://github.com/NVIDIA/cuda-quantum/issues/3115 and https://github.com/NVIDIA/cuda-quantum/issues/3116
=> Support `apply_noise` in builder mode 

docs/sphinx/examples/python/random_walk_qpe.py
Follow-up to similar change in PR https://github.com/NVIDIA/cuda-quantum/pull/3332
The change improves the correctness of the quantum walk by resetting the `aux` qubit after each iteration.
=> [fix] Update example - reset qubit after measurement

python/tests/backends/test_braket.py, runtime/cudaq/platform/default/rest/helpers/braket/BraketServerHelper.cpp
Checklist:
I added a mapping from `ccx`->`ccnot` since that's the name of the gate on Braket in the exact same manner `cx` is already mapped to `cnot`.
This problem was mentioned on this previous issue:
https://github.com/NVIDIA/cuda-quantum/issues/2325#issuecomment-2518222251
=> Update BraketServerHelper to use ccnot instead of ccx

include/cudaq/Optimizer/Builder/Factory.h, lib/Optimizer/Builder/Factory.cpp, python/extension/CUDAQuantumExtension.cpp, unittests/Optimizer/CMakeLists.txt, unittests/Optimizer/FactoryMergeModuleTest.cpp
This fixes bug in `checkRegisteredCppDeviceKernel` which dropped everything on the floor which is not `func::FuncOp`.
* Adding mergeModules utility function
* Avoid using walk as it is wrong. Filtering artifacts by their IR node type is incorrect.
* Adding unit tests
co-authored by: Eric Schweitz <eschweitz@nvidia.com>
=> MergeModules utility function

runtime/common/RecordLogParser.cpp, runtime/common/RecordLogParser.h
This PR simplifies the code that deals with different QIR versions in the metadata handling in the `RecordLogParser`.
Also makes Boolean value parsing more robust. 
Attempt to break up large PR https://github.com/NVIDIA/cuda-quantum/pull/3448 into smaller chunks.
=> [runtime refactoring] Simplify handling of QIR attributes and avoid re-lookup

runtime/common/Future.cpp, runtime/common/ServerHelper.h, runtime/cudaq/platform/default/rest/helpers/quantinuum/QuantinuumServerHelper.cpp
This PR refactors how sample results are created from QIR output logs in the `QuantinuumServerHelper`, moving logic from the implementation file into a reusable method in the base server helper class.
Attempt to break up large PR #3448 into smaller chunks.
=> [refactoring] Common code for QIR processing

.github/workflows/config/gitlab_commits.txt
This mgpu commit update handles the updated Ubuntu 24.04 changes in the gitlab CI.
=> update mgpu commit to fix publishing pipeline
